### ISSUE TITLE
Adjustment to the mean internal temperature

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#100]
*Worksheet (93m): Adjustment to the mean internal temperature from table 4e* is not implemented

  carlos

**Comment by cagabi** [comment]
Argg, it was so easy that i had to do it ;)

  carlos

**Comment by gervasemangwana** [comment]
Ok now we aim for 200!!!

Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk
