### ISSUE TITLE
SAP worksheets

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#101]
I am implementing this right now in order to be able to check results against other SAP calculators.

I open this issue to keep track of things that are missing. So far:
- 8c Space cooling requirement
- 8f Fabric energy efficiency: MHEP currently calculates it but not as described in section 11, p.31 SAP2012

  Carlos

**Comment by marianneURBED** [comment]
Hi Carlos,

I think the cooling section was never implemented cause we'd need it so
rarely in the north of England - but definitely good to have for
completeness.

The FEES is definitely very useful though - we should be able to report on
that.

Thanks

Marianne

On Thursday, March 3, 2016, carlos Alonso Gabizón <notifications@github.com>
wrote:

> I am implementing this right now in order to be able to check results
> against other SAP calculators.
>
> I open this issue to keep track of things that are missing. So far:
>
>    - 8c Space cooling requirement
>    -
>
>    8f Fabric energy efficiency: MHEP currently calculates it but not as
>    described in section 11, p.31 SAP2012
>
>    Carlos
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emoncms/MyHomeEnergyPlanner/issues/101>.
>


-- 
*Marianne Heaslip*
Architect/Sustainability Consultant

*URBED (Urbanism Environment Design) Ltd *a. 5th Floor, 10 Little Lever
Street, Manchester, M1 1HR
t. +44 (0)161 200 5500
e. marianne@urbed.coop
w. www.urbed.coop

Fire destroys Toxteth Food Central - we need your help!
<http://us6.campaign-archive1.com/?u=47ce46e3ee9278b42c90d7d62&id=a927286bfc&e=e1c312350a>

URBED is 40 and hosting 7 unique events over 2015 to celebrate.
<http://urbed.coop/events>
Urban Design Group Awards 2015 - Winner in the Best Practice Category for
Trent Basin
Wolfson Economics Prize 2014 - Winner: Uxcester Garden City Proposal
Community Land Trust Network Awards 2012 - Awarded for excellence in
community engagement 2Up 2Down / Homebaked
URBED (Urbanism Environment & Design ) Ltd is a limited company with
co-operative rules registered in England and Wales NO. 5741006. Please
access the attached hyperlink for an important electronic communications
disclaimer: http://www.urbed.coop/emaildisclaimer
<http://www.urbed.coop/emaildisclaimer.>

**Comment by cagabi** [comment]
SAP worksheet view done.I leave the issue open to keep track of comments above.

   Carlos
