### ISSUE TITLE
Form that could populate the ‘householdquestionnaire’ in advance of the visit

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#102]
A form that ca be sent to the household to prefill and then to be importted byt the assesor into MHEP. Options a csv file or copy and paste from a spread sheet.

  Jonathan

**Comment by cagabi** [comment]
I have made an online form  that households can fill before you go to do the house visit. Once they submit it, you can donwload a csv file via google forms interface and upload it in the Household Questionnaire page in MHEP

The download of the form into the csv file has the inconvenience that if there is more than one response saved in google forms, then all the responses are exported. In this case, before the import in MHEP you will have to remove all the rows except the one of the form you want to import.

I know it sounds complicated but it is very simple, please ask if you need to.

To send the link to the household you can copy and paste the link in the email edit invitation I have sent via google forms.

Only us can see the replies, anyway, for data protection it would be great if you delete the responses from Google forms once you have imported them into MHEP

Carlos

**Comment by cagabi** [comment]
I forgot to say that in the online form we don't ask for the periods of heating on/off during weekdays and weekends. I couldn't find an easy way to ask for them, so you have to be aware of this when you review the questionnaire with the householders

**Comment by marianneURBED** [comment]
I think the questions in this form need review - a problem for me rather than you though Carlos! Re-opening so I don't forget to look at this.

**Comment by marianneURBED** [comment]
Tackling this in a different way - looking to be able to use the tool, or just part of it, offline - for example during surveys.
