### ISSUE TITLE
When creating new element from existing shows ALL not just from element type

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#104]
When Wall is selected still shows windows doors etc

**Comment by gervasemangwana** [comment]
I've got a vague memory we talked about this but can't think why we would want it like this. Makes the drop down list very long. Would be better I think if element type is walls then only walls shown.

**Comment by gervasemangwana** [comment]
This only happens when selecting Wall as type when in Wall section of fabric as far as I can make out

**Comment by marianneURBED** [comment]
Done and fixed as far as I can tell.
