### ISSUE TITLE
U-value for Floors should be a separate data entry and appear in a box

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#109]
So in the library U-value should be 0

**Comment by cagabi** [comment]
I have done the box but have not changed the u-values in libraries. Don't you think it would be better having something that can be used if you are not sure?

   Carlos

**Comment by gervasemangwana** [comment]
I don’t think so no.


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by marianneURBED** [comment]
Agree with Gervase. It's pretty much always going to differ depending on
the geometry of the floor.

Marianne.

On Monday, March 21, 2016, gervasemangwana <notifications@github.com> wrote:

> I don’t think so no.
>
>
> Gervase Mangwana
>
> Waxwing Energy
> 07956378981
> info@waxwingenergy.co.uk
> <javascript:_e(%7B%7D,'cvml','info@waxwingenergy.co.uk');>
>
>
>
> > On 20 Mar 2016, at 23:39, carlos Alonso Gabizón <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > I have done the box but have not changed the u-values in libraries.
> Don't you think it would be better having something that can be used if you
> are not sure?
> >
> > Carlos
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub <
> https://github.com/emoncms/MyHomeEnergyPlanner/issues/109#issuecomment-199060152
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/emoncms/MyHomeEnergyPlanner/issues/109#issuecomment-199170841>
>


-- 
*Marianne Heaslip*
Architect/Sustainability Consultant

*URBED (Urbanism Environment Design) Ltd *a. 5th Floor, 10 Little Lever
Street, Manchester, M1 1HR
t. +44 (0)161 200 5500
e. marianne@urbed.coop
w. www.urbed.coop

Fire destroys Toxteth Food Central - we need your help!
<http://us6.campaign-archive1.com/?u=47ce46e3ee9278b42c90d7d62&id=a927286bfc&e=e1c312350a>

URBED is 40 and hosting 7 unique events over 2015 to celebrate.
<http://urbed.coop/events>
Urban Design Group Awards 2015 - Winner in the Best Practice Category for
Trent Basin
Wolfson Economics Prize 2014 - Winner: Uxcester Garden City Proposal
Community Land Trust Network Awards 2012 - Awarded for excellence in
community engagement 2Up 2Down / Homebaked
URBED (Urbanism Environment & Design ) Ltd is a limited company with
co-operative rules registered in England and Wales NO. 5741006. Please
access the attached hyperlink for an important electronic communications
disclaimer: http://www.urbed.coop/emaildisclaimer
<http://www.urbed.coop/emaildisclaimer.>

**Comment by cagabi** [comment]
Ok, u-values set to zero in default library  and user ones

   carlos
