### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by lowwintersun** [emoncms/MyHomeEnergyPlanner#11]
Homepage not displaying as expected
![heat_loss_house](https://cloud.githubusercontent.com/assets/7352302/11784626/46a65b90-a275-11e5-97dd-5cd61ddb28b8.png)

**Comment by helen-urbed** [comment]
Is this a test?

Helen Grimshaw
Sustainability Consultant
URBED (Urbanism Environment Design) Ltd

Fire destroys Toxteth Food Central - we need your help! <http://us6.campaign-archive1.com/?u=47ce46e3ee9278b42c90d7d62&id=a927286bfc&e=e1c312350a>

a. 5th Floor, 10 Little Lever Street, Manchester, M1 1HR
t. +44 (0)161 200 5504
e. helen@urbed.coop <mailto:sange@urbed.coop>
w. www.urbed.coop <http://www.urbed.coop/>

URBED is 40 and hosting 7 unique events over 2015 to celebrate, see here for more details. <http://urbed.coop/events>
Urban Design Group Awards 2015 – Winner in the Best Practice category for Trent Basin, Nottingham
Wolfson Economics Prize 2014 – Winner: Uxcester Garden City Proposal
Community Land Trust Network Awards 2012 – Awarded for excellence in community engagement 2Up 2Down/ Homebaked, Liverpool

URBED (Urbanism, Environment & Design) Ltd is a limited company with co-operative rules registered in England and Wales No. 5741006.  Please access the attached hyperlink for an important electronic communications disclaimer: http://www.urbed.coop/email-disclaimer <http://www.urbed.coop/email-disclaimer> 

Please save paper and only print this email if you have to.

**Comment by cagabi** [comment]
Having a look now.

   carlos

**Comment by cagabi** [comment]
I can see that what is making the application to crash is the gas boiler for space cooling which is still the old pre-library format.

Right now,  as far as i know,  it is not possible to add this wrong gas boiler, Can you please let me know how did you add the gas boiler.

Thanks, 

  Carlos

**Comment by cagabi** [comment]
Ok, so it looks like this is a simple test. 

Jonathan can you confirm this and close the issue please.

Thanks,

   carlos
