### ISSUE TITLE
Could we rename 'floors' page as 'Basic Dwelling Data'?

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#113]
This is a minor point, but the 'Floors' page under 'Core Input' actually includes more than just info about floors, and doesn't actually have all the info about floors - only area not construction etc. 

I think it would be better if this were renamed 'Basic Dwelling Data' or something similar, as it's less confusing.

This is also probably the only bit that doesn't really change between scenarios (assuming one of your retrofit measures isn't  to make one of the occupants move out!).

**Comment by marianneURBED** [comment]
Similarly, could we rename 'Ventilation' as 'Ventilation and Infiltration'. Thanks!

**Comment by gervasemangwana** [comment]
Good suggestion. Have thought about this too.

Although significant internal wall insulation does actually reduce floor area.

Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by cagabi** [comment]
I have done the changes as it was quick,

Question before closing the issue: right now we are not modifying the internal area when we apply internal wall insulation, should we?? If we are ok not doing that shall i move  *Basic Dwelling Data* to the Project menu?

**Comment by marianneURBED** [comment]
Hi Carlos,

I think we leave it where it is for now - there are potential scenarios
where people change floor area (and no. of windows etc) between scenarios -
for example it they are planning an extension or loft conversion. It's not
something that comes up often, but we should probably keep it so it's
possible to do this.

As to changing the floor area when we do IWI -  in most instances we deal
with, where IWI is not the first preference and its area is usually kept to
a minimum, this would change the overall floor area in a very limited
fashion, so wouldn't make a huge difference - given the overall level of
accuracy we're aiming for (say 8 linear metres of wall, IWI 0.1m wide, so
0.8m change).

This is maybe something for the manual/ user guide, but suspect in most
instances we wouldn't bother changing it - but would be nice to be able to
if we thought it was necessary.

So, short answer - leave it where it is.

Thanks,

Marianne

On 20 March 2016 at 22:40, carlos Alonso Gabizón <notifications@github.com>
wrote:

> I have done the changes as it was quick,
>
> Question before closing the issue: right now we are not modifying the
> internal area when we apply internal wall insulation, should we?? If we are
> ok not doing that shall i move *Basic Dwelling Data* to the Project menu?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/emoncms/MyHomeEnergyPlanner/issues/113#issuecomment-199052452>
>



-- 
*Marianne Heaslip*
Architect/Sustainability Consultant

*URBED (Urbanism Environment Design) Ltd *a. 5th Floor, 10 Little Lever
Street, Manchester, M1 1HR
t. +44 (0)161 200 5500
e. marianne@urbed.coop
w. www.urbed.coop

Fire destroys Toxteth Food Central - we need your help!
<http://us6.campaign-archive1.com/?u=47ce46e3ee9278b42c90d7d62&id=a927286bfc&e=e1c312350a>

URBED is 40 and hosting 7 unique events over 2015 to celebrate.
<http://urbed.coop/events>
Urban Design Group Awards 2015 - Winner in the Best Practice Category for
Trent Basin
Wolfson Economics Prize 2014 - Winner: Uxcester Garden City Proposal
Community Land Trust Network Awards 2012 - Awarded for excellence in
community engagement 2Up 2Down / Homebaked
URBED (Urbanism Environment & Design ) Ltd is a limited company with
co-operative rules registered in England and Wales NO. 5741006. Please
access the attached hyperlink for an important electronic communications
disclaimer: http://www.urbed.coop/emaildisclaimer
<http://www.urbed.coop/emaildisclaimer.>

**Comment by cagabi** [comment]
Ok, easy.

Thanks.

   Carlos
