### ISSUE TITLE
Ventilation Types

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#114]
There are currently 4 types of ventilation listed in the drop down for ventilation - but there are more types of ventilation than this, which, though they might not change the calcs (much), does mean there is potential for confusion, especially when it comes to applying measures. Can I suggest the following categories are included, with the following effect on calculations: 

NEW CATEGORY = OLD CATEGORY (FOR REFERENCE IN CALCS)
'Natural ventilation only (NV)' = 'Natural ventilation or whole house positive input ventilation from loft' 
'Intermittent extract ventilation (IE)' = 'Natural ventilation or whole house positive input ventilation from loft' 
(Note, for this, would assume you'd entered right number of intermittent fans in section above - the logic of this when applying measures might need some thought). 
'Continuous decentralised mechanical extract ventilation (DEV)' =  'Whole house extract ventilation or positive input ventilation from outside'. 
'Continuous whole house extract ventilation (MEV)' = 'Whole house extract ventilation or positive input ventilation from outside'. 
'Balanced mechanical ventilation without heat recovery (MV)' = 'Balanced mechanical ventilation without heat recovery (MV)'
'Balanced mechanical ventilation with heat recovery (MVHR)' = 'Balanced mechanical ventilation with heat recovery (MVHR)'

There is no scenario where we'd specify positive input ventilation - it's a supposed miracle cure for condensation issues that has me really worried about pushing warm moist air into vulnerable building fabric, and has been installed in some social housing in my neck of the woods and seems to be costing the residents a silly amount of money to run, so I'd always avoid. 

Thanks, 

Marianne

**Comment by marianneURBED** [comment]
Apologies, should also include: 

'Whole House Passive Stack Ventilation System (PS)' = 'Natural ventilation or whole house positive input ventilation from loft'

**Comment by cagabi** [comment]
Hi,

I have replaced the old categories with the new ones.

I have a question with regards to *Natural ventilation only (NV)* and *Whole House Passive Stack Ventilation System (PS)*: should they make *Intermittent fans* to be automatically zero.

And about *Intermittent extract ventilation (IE)* when doing the calculation it becomes *Natural ventilation or whole house positive input ventilation from loft*. But in this case the looses for Ventilation is always 0 as only infiltration is taken into account. The calculation of these loses is made from 24d in the worksheets SAP2012 (p. 180). If it's not clear we may want to discuss it on wednesday.

  Carlos

**Comment by cagabi** [comment]
Agreed that choosing *NV* or *PS* will set *intermitents fans* and *passive vents* to zero, this deals with previous commment.
