### ISSUE TITLE
Ventilations: clothes drying facilities

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#117]
Add library to add them to assesment but also same library for adding them as measures

**Comment by marianneURBED** [comment]
I've duplicated the list of measures and edited it in the gsheet, so can be used for existing condition too. Is that what was required? If not, let me know.

**Comment by cagabi** [comment]
Thank you, for doing it but i didn't mean anything, this was another one that i just had to do. And done :)
