### ISSUE TITLE
Update SAP data tables

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#12]
Update SAP data tables (the most recent version of SAP v9.92) and change solar gains calculation. Eg Table U5. Check issues raised by Tom (see spreadsheet called 'Tom tests')

**Comment by cagabi** [comment]
Trystan has been looking at this, Carlos check to stage in which stage this is

**Comment by cagabi** [comment]
Trystan updated the tables that is done.

I started having a look yesterday at the test from Tom and some are still failing. I am having a look at his code but also could be handy if i have a spread sheet that does SAP calculations, this way (if it is not too difficult) i can check some other calculations myself.

  Carlos

**Comment by helen-urbed** [comment]
Hi Carlos

The spreadsheet we use is in Numbers (mac version of excel), so probably not much use to you. I've exported it to excel, but whether this is fit for purpose is another question - all of the formatting has gone and some of the calculations might not work. 
Also, the Numbers spreadsheet wasn't upgraded to the latest version of SAP so big health warning there too. 

Depending on what you need, there might be some other free software out there that you could check against - for example, FSAP by Stroma. Elmhurst also have a free demo version- but you won't necessarily be able to see what's going on behind the scenes. 

I'll send you the spreadsheets by a separate email. 

Thanks,
Helen

**Comment by cagabi** [comment]
Thak you very much, i'll if i can use it.

  carlos

**Comment by cagabi** [comment]
I'll close this issue as the title has nothing to do with what is left to do.

I've opened another issue #94 - *Check results against other SAP tools*
