### ISSUE TITLE
Library manager crashes when added a measure 

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#124]
When you finish after adding the add button no longer works. When you refresh the page goes blank apart from headings and arrows on image disappear.
If you go out to assessments and back in the arrows come back but when you click library manager it is blank. Same prob in all asssessments of that user (GervaseMangwana) tried my other user (GervaseCooke) repeated process by adding a measure to Carbon Co Op library. Successfully added but then the same thing happened. 

Have added several fabric elements without problems.

**Comment by marianneURBED** [comment]
Just tried replicating. Got the same problem. Screenshot attached. 
<img width="1440" alt="screen shot 2016-03-24 at 14 44 44" src="https://cloud.githubusercontent.com/assets/16305707/14020448/15ca0da6-f1cf-11e5-9236-38c37130e5a8.png">

**Comment by cagabi** [comment]
I have found the bug, not easy. The *notes* of *FLIT_01* finished in a carrier return (INTRO key). That MHEP go nuts when converting the library from a string to something that can be used in the program.

I have manually fixed the library and in the process I think i have created several copies of your assesment Marianne.

I haven't fixed the bug yet, so please be careful and don't press intro.

  Carlos

**Comment by gervasemangwana** [comment]
Do you mean "Enter" key. I don't know the "Intro" key. 
But anyway I won't be working until next Wednesday.

**Comment by cagabi** [comment]
Yes that was the key i meant.

ANyway it is fixed now.

   Carlos
