### ISSUE TITLE
Summer ventilation measures

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#126]
Intended to help prevent over-heating, They won't affect the calcs as they stand - though if we ever got into calculating over-heating risk they would.

![image](https://cloud.githubusercontent.com/assets/7636325/14311187/02882cd2-fbde-11e5-8ddf-002e6ab11e34.png)

**Comment by marianneURBED** [comment]
Need to add these to the library and work out how to apply them in an assessment so they show up in a report.

**Comment by cagabi** [comment]
Dis you close this issue intentionally?
It looks to me it's open

**Comment by marianneURBED** [comment]
No, sorry – did than one ‘on accident’. Not high priority, but best to leave open.
