### ISSUE TITLE
Structural infiltration redoing

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#127]
Chimneys, Open flues, etc to be inputed as we do with elements in fabric. They all are defined by typical fields and *Ventilation rate*.

In terms of measures: add, remove or change ventilation rate.

   carlos

**Comment by cagabi** [comment]
After conversation with Marianne:
- Intermitent fans and passsive vents are inputs to be displayed under *Ventilation system*, we can still apply measures to them
- List of *Intentional vents, flues* at the bottom of the page and we can apply measures: just change ventilation rate (will be zero if we want to remove it)

  carlos

**Comment by cagabi** [comment]
Done.

We can say the the whole *Ventilation* section has been remade so it would be great if somebody has a good look and tell me if this how we want it to be

Comments:
- Changing the *Ventilation type* behaves like the Measures in terms of setting the value for fans, vents, air change rate and HRE
- I am not sure if we wanted to be able to set the air change rate for intermittent fans. This could be a bit complicated but possible using 10 (SAP value) as the default one. The reason to be complicated is how it would work when changing the Ventilation system to IE
- I was finding incredibly annoying the way we show/hide sections of the page (like when changing the Ventilation system) as it made me to visually loose track of what is going on. I have added some transitions everywhere :)
- I leave the issue open just in case

  carlos

**Comment by marianneURBED** [comment]
Hi Carlos,

I've had a play with this and it looks really good - think we've just about
cracked it.

One thing I noticed, though will do more testing to check - when you change
the number of sheltered sides, it doesn't change the structural
infiltration rate. It probably should.

Thanks,

Marianne

On 13 April 2016 at 12:34, carlos Alonso Gabizón <notifications@github.com>
wrote:

> Done.
>
> We can say the the whole *Ventilation* section has been remade so it
> would be great if somebody has a good look and tell me if this how we want
> it to be
>
> Comments:
>
>    - Changing the *Ventilation type* behaves like the Measures in terms
>    of setting the value for fans, vents, air change rate and HRE
>    - I am not sure if we wanted to be able to set the air change rate for
>    intermittent fans. This could be a bit complicated but possible using 10
>    (SAP value) as the default one. The reason to be complicated is how it
>    would work when changing the Ventilation system to IE
>    - I was finding incredibly annoying the way we show/hide sections of
>    the page (like when changing the Ventilation system) as it made me to
>    visually loose track of what is going on. I have added some transitions
>    everywhere :)
>    -
>
>    I leave the issue open just in case
>
>    carlos
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/emoncms/MyHomeEnergyPlanner/issues/127#issuecomment-209380273>
>



-- 
*Marianne Heaslip*
Associate Principal

*URBED (Urbanism Environment Design) Ltd *a. 5th Floor, 10 Little Lever
Street, Manchester, M1 1HR
t. +44 (0)161 200 5500
e. marianne@urbed.coop
w. www.urbed.coop

Fire destroys Toxteth Food Central - we need your help!
<http://us6.campaign-archive1.com/?u=47ce46e3ee9278b42c90d7d62&id=a927286bfc&e=e1c312350a>

*Please note I work Wednesday to Friday. *On other days, please contact my
colleague Lorenza Casini.

Urban Design Group Awards 2015 - Winner in the Best Practice Category for
Trent Basin
Wolfson Economics Prize 2014 - Winner: Uxcester Garden City Proposal
Community Land Trust Network Awards 2012 - Awarded for excellence in
community engagement 2Up 2Down / Homebaked
URBED (Urbanism Environment & Design ) Ltd is a limited company with
co-operative rules registered in England and Wales NO. 5741006. Please
access the attached hyperlink for an important electronic communications
disclaimer: http://www.urbed.coop/emaildisclaimer
<http://www.urbed.coop/emaildisclaimer.>

**Comment by cagabi** [comment]
Hi,

You were right, the value we were showing for the *structural infiltration rate* was not including the *sheltered sides*.

I have also done a bit more of restructuring of the content as the input for *sheltered sides* was hidden when using the tightness test.

   Carlos
