### ISSUE TITLE
Create new library categories

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#128]
Need the following

Extract Ventilation points (existing)

Ventilation Systems (existing)

Hot water systems (existing)

Hot water systems (measures)

**Comment by cagabi** [comment]
After phone conversation:
- Extract Ventilation points (existing): new issue opened #132 
- Ventilation Systems (existing): not needed anymore as they are in the drop down
- Hot water systems (existing): new issue #133 
- Hot water systems (measures): issues #133 and #134
