### ISSUE TITLE
Deleting element in Library doesn't seem to work

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#129]
Tried deleting LRI_01.5 from CC fabric elements/roofs. Appears to complete task but element is still in library.

**Comment by gervasemangwana** [comment]
Editing also not working. I'm sure this was fixed some time ago.

**Comment by gervasemangwana** [comment]
Can delete elements in my own standard library.

**Comment by cagabi** [comment]
The problem was because of the dot in the tag. I have manually changed it in the database and also ensure that it doesn't happen again.
