### ISSUE TITLE
Manual adjustment of Thermal Bridging - Fabric page

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#13]
CARLOS ADD LIBRARY FUNCTIONALITY TO ENABLE MANUAL ADJUSTMENT OF THERMAL BRIDGING

**Comment by cagabi** [comment]
I am not clear what this means.

I think i remember from the meeting that we want *Thermal bridging* to be adjusted as a *meaasure*. Does it  makes sense??

   Carlos

**Comment by cagabi** [comment]
Library functionality not to be implemented.

What we'll do add an *Apply measure* button. In the pop up ask for the new value but also have a *Description* box.

  Helen and Calos

**Comment by cagabi** [comment]
Done

  carlos

**Comment by cagabi** [comment]
I am making the list of measures for Ed and have just realized that this measure only changes the value of the thermal bridging but there is no other information like description, cost, maintenance, etc

So there  is nothing really to go into the report, is that right?

  Carlos

**Comment by marianneURBED** [comment]
Hi Carlos,

Yes, that's right. At the moment we're just adjusting it on the basis of
the assessor's judgement - so for a house with full EWI it should be pretty
low, but in other cases it may be mid-point, or not change at all from the
default.

I think for a future iteration of the report this is something to consider
and make more explicit - as it ties up with trying to get better quality
outcomes - but for now we can leave as-is, and nothing needs to be
displayed in the report (other than general guidance about
avoiding/minimising thermal bridging).

Thanks,

Marianne



On 20 April 2016 at 11:53, carlos Alonso Gabizón <notifications@github.com>
wrote:

> I am making the list of measures for Ed and have just realized that this
> measure only changes the value of the thermal bridging but there is no
> other information like description, cost, maintenance, etc
>
> So there is nothing really to go into the report, is that right?
>
> Carlos
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/emoncms/MyHomeEnergyPlanner/issues/13#issuecomment-212378788>
>



-- 
*Marianne Heaslip*
Associate Principal

*URBED (Urbanism Environment Design) Ltd *a. 5th Floor, 10 Little Lever
Street, Manchester, M1 1HR
t. +44 (0)161 200 5500
e. marianne@urbed.coop
w. www.urbed.coop

Fire destroys Toxteth Food Central - we need your help!
<http://us6.campaign-archive1.com/?u=47ce46e3ee9278b42c90d7d62&id=a927286bfc&e=e1c312350a>

*Please note I work Wednesday to Friday. *On other days, please contact my
colleague Lorenza Casini.

Urban Design Group Awards 2015 - Winner in the Best Practice Category for
Trent Basin
Wolfson Economics Prize 2014 - Winner: Uxcester Garden City Proposal
Community Land Trust Network Awards 2012 - Awarded for excellence in
community engagement 2Up 2Down / Homebaked
URBED (Urbanism Environment & Design ) Ltd is a limited company with
co-operative rules registered in England and Wales NO. 5741006. Please
access the attached hyperlink for an important electronic communications
disclaimer: http://www.urbed.coop/emaildisclaimer
<http://www.urbed.coop/emaildisclaimer.>

**Comment by cagabi** [comment]
Ok good, i re-close this issue.

  Carlos
