### ISSUE TITLE
Hot water systems library and measures

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#133]
We want to implement them but it needs to be specified which are the fields in the hot water systems (for example tick box to say there is a storage or any other preselected possibilities.

**Comment by cagabi** [comment]
Hi, 

This issue is mostly done but needs a bit more thinking to be completely finished. Comments:
- I have attached the plan that Marianne did as this has been my reference, i know the file is too big but I want be sure it's readable
- Water efficiency measures: I have already created the library that was in GDocs. I have left the delete icon so the *standard use* can be removed but i don't like those icons there
- Hot water energy system: if there is any system added in the *Energy systems* page it will be displayed here but I have left the original dropdown list of SAP systems as these are the ones we use in the calculations
- Combi boilers: they have extra losses (tables 3b and 3c), if you select *Combi boiler* as the water energy system you will see that *combi boiler dropdown* is shown under *Storage losses*, what shall we do with this? I guess we need to keep it
- Pipework insulation: i have implemented it but according to SAP table 3 it will only been taking into account in the calculations when the water energy system is set to *Other*. Now it is always displayed but can change it to only be displayed when *Other* is chosen

So, I think an extra bit of thinking is needed to find the best way to link the water energy systems that SAP uses with the use of a storage and insulated pipework.

Cheers

![water_heating_plan](https://cloud.githubusercontent.com/assets/7636325/15356558/64fd9512-1cf1-11e6-8cbb-ef4e5509da8e.jpg)

**Comment by marianneURBED** [comment]
Hi Carlos,

I think this does need a bit of further thought. When Gervase and myself
left this last week, the plan was that I would look at the logic of the
energy systems library, which this is connected to. I probably won't get
chance to do this until the end of the week.

What would be really good is if we can avoid having to essentially put the
same data in twice - as this is liable to lead to conflicts and confusion -
so for example, could we not say in the systems library which 'type' of
system each item is as far as SAP is concerned, and add in things like
additional losses for combis where they apply. That way you're only
thinking about it once, and there's not room for a conflict to arise? That
might not be the best or only way round it. Let me have a think about it
and we'll catch up next week when Gervase is back from his hols.

Marianne

On 18 May 2016 at 12:10, carlos Alonso Gabizón <notifications@github.com>
wrote:

> Hi,
>
> This issue is mostly done but needs a bit more thinking to be completely
> finished. Comments:
>
>    - I have attached the plan that Marianne did as this has been my
>    reference, i know the file is too big but I want be sure it's readable
>    - Water efficiency measures: I have already created the library that
>    was in GDocs. I have left the delete icon so the *standard use* can be
>    removed but i don't like those icons there
>    - Hot water energy system: if there is any system added in the *Energy
>    systems* page it will be displayed here but I have left the original
>    dropdown list of SAP systems as these are the ones we use in the
>    calculations
>    - Combi boilers: they have extra losses (tables 3b and 3c), if you
>    select *Combi boiler* as the water energy system you will see that *combi
>    boiler dropdown* is shown under *Storage losses*, what shall we do
>    with this? I guess we need to keep it
>    - Pipework insulation: i have implemented it but according to SAP
>    table 3 it will only been taking into account in the calculations when the
>    water energy system is set to *Other*. Now it is always displayed but
>    can change it to only be displayed when *Other* is chosen
>
> So, I think an extra bit of thinking is needed to find the best way to
> link the water energy systems that SAP uses with the use of a storage and
> insulated pipework.
>
> Cheers
>
> [image: water_heating_plan]
> <https://cloud.githubusercontent.com/assets/7636325/15356558/64fd9512-1cf1-11e6-8cbb-ef4e5509da8e.jpg>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/emoncms/MyHomeEnergyPlanner/issues/133#issuecomment-219995437>
>



-- 
*Marianne Heaslip*
Associate Principal

*URBED (Urbanism Environment and Design) Ltd *a. 5th Floor, 10 Little Lever
Street, Manchester, M1 1HR
t. +44 (0)161 200 5500
e. marianne@urbed.coop
w. www.urbed.coop

Fire destroys Toxteth Food Central - we need your help!
<http://us6.campaign-archive1.com/?u=47ce46e3ee9278b42c90d7d62&id=a927286bfc&e=e1c312350a>

*Please note I work Wednesday to Friday. *On other days, please contact my
colleague Lorenza Casini.

Urban Design Group Awards 2015 - Winner in the Best Practice Category for
Trent Basin
Wolfson Economics Prize 2014 - Winner: Uxcester Garden City Proposal
Community Land Trust Network Awards 2012 - Awarded for excellence in
community engagement 2Up 2Down / Homebaked
URBED (Urbanism Environment & Design ) Ltd is a limited company with
co-operative rules registered in England and Wales NO. 5741006. Please
access the attached hyperlink for an important electronic communications
disclaimer: http://www.urbed.coop/emaildisclaimer
<http://www.urbed.coop/emaildisclaimer.>

**Comment by marianneURBED** [comment]
I've done some work on what has now become the 'heating' page. The idea is that you select all the different heat systems on one page - for both space heating and hot water. 

I've done a sketch of the page (attached) and put some detail on this into the g-sheet library. Hopefully is to some degree self-explantory. 

I'm pretty happy with the logic, but there's some detail to sort out. 

Carlos, could you have a look, see if you get where I'm driving at, and let me know if you think it's workable? Then I can try to flesh out the detail before you're here next Thursday. Thanks!

[Heating Page Sketch.pdf](https://github.com/emoncms/MyHomeEnergyPlanner/files/354657/Heating.Page.Sketch.pdf)

**Comment by cagabi** [comment]
Hi,

I have had a good look at it now. I am with you as *I'm pretty happy with the logic, but there's some detail to sort out.* And this will be complicated as it feels we are making our own model.

I have focused more in the Hot Water and can already see several things that will have to be discussed, the problem is that more will come while we work on it:
- adding *insulation* for the storage may have to do with *thickness* (Bredem) of *declared loss factor* (SAP). 
- We also need a way of identifying when a combi boiler is added in order to calculate its looses (could be another tick box). 
- Will be only allow the controls in SA, in that case we don't need the library and would be enough with a drop down but it would be very limited.

I don't think these points above need an immediate answer as they are more a kind of example of things we may have to deal with.

I am wondering how will be the best way to do it. Maybe i can start working but would probably have to ask you many questions as I go. I am in the office on Thursday (i have a meeting too) and Friday. Also thinking it may make sense to plan me going next week.

   Carlos

**Comment by cagabi** [comment]
Done as part of the _Heating_ section

  carlos
