### ISSUE TITLE
Integrate report functionality from Fieldwork staging site

### ISSUE THREAD

**Issue by lowwintersun** [emoncms/MyHomeEnergyPlanner#135]
We want to begin testing the Carbon Co-op report functionality - I think this requires Fieldwork's reporting module to be merged with the My Home Energy Planner core functionality?

**Comment by cagabi** [comment]
Hi, it looks to me that last new addintions to the report were done a long ago and are already merged with the current version in http://myhome.carbon.coop/. 

I am checking with Ed, though.

  Carlos

**Comment by cagabi** [comment]
Add measures to report

Display EVP and IVF properly

**Comment by cagabi** [comment]
HHi, I have done most of it. Comments questions:
- I haven't added *water efficiency measures* as i have realized I implemented them wrong. I'll redo the measures and add them to the report
- There is the option to remove as measure for fabric elements, energy systems and extract ventilation points. The problem with this is that these measures have not got any description, performance, cost, etc, associated. This doesn't work when adding them to the report. I think we should delete the option to *remove as measure* (proper measures with the same effect should be created in the library) or if we want to keep it at least all the typical fields (description, cost, etc) should be shown and filled before clicking on applying the measure. The first option is the easy one for me but I am happy to implement the other one
- *Thermal bridging* and *Piperwork insulation* measures have not been added to the report as they also haven't got the information (description, cost....) once again the options could be to create a library for them or display of those fields to be inputed by the assesor before applying the mesaure.

  Carlos

**Comment by cagabi** [comment]
Sorry, I don't know but it is only working on my local machine. If you try now you will not be able to see the measure in the report. I don't know why, checking now

  carlos

**Comment by cagabi** [comment]
Working now

**Comment by cagabi** [comment]
*Water efficiency measures" added to report now

**Comment by cagabi** [comment]
After conversation:
- Remove the *Remove* option, this option will be implemented as a library item.
- Thermal bridging and pipe insulation not to be shown in the report.

  Carlos

**Comment by cagabi** [comment]
Done
