### ISSUE TITLE
draught-proofing measures - Ventilation / infiltration

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#15]
Need to be able to apply particular draught-proofing measures 

DECISION: CREATE NEW LIBRARY FOR THIS

AP! CARLOS - WHEN 'CALCULATE BASED ON AIR TIGHTNESS TEST' IS TICKED LIBRARY CAN BE APPLIED TO - AIR PERMEABILITY VALUE

**Comment by lowwintersun** [comment]
@marianneURBED and I will look at resourcing @gervasemangwana to populate this library

**Comment by cagabi** [comment]
Add a button for *Apply draught proofing measures*. Clicking will apply measure from library.

Draught proofing library items fields:
- Name
- Air permeability value, q50, expressed in cubic metres per hour per square metre of envelope area
- Typical ones for measures: description, performance, etc.

To help to choose the value of * Air permeability value* we will add the *Structural Infiltration value"

Also move *Structural Infiltration* secttion above *Enter number of*

**Comment by cagabi** [comment]
Keep *Lobby draught* when we hide all the *Strucutral infiltration* block.

Add 'Apply measure" which would tick the box.

**Comment by cagabi** [comment]
I have done it except for the lobby. Ill do it with the other ventilation measures.

   carlos
