### ISSUE TITLE
Fuel to be inputted in specific pages instead of Systems page

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#158]
There is not really an issue for this so i have decided to open one. I have closed the #143 *Inputting some data in two places* as this issue will cover it as well.

So far the systems used for lighting, cooking, appliances, space heating and water heating were inputted in the *Systems* page but because of SAP worksheet we were asking for similar information in all the specific pages. In order to avoid this we decided to use the *Systems* page as a display of information about fuel totals (emissions, primary energy and annual cost per type of fuel). The info about fuel (type and fraction of demand) and system efficiency will only be inputted in the specific pages.

  carlos

**Comment by marianneURBED** [comment]
Yep, that's my understanding too.

M.

On Tuesday, 21 June 2016, carlos Alonso Gabizón <notifications@github.com>
wrote:

> There is not really an issue for this so i have decided to open one. I
> have closed the #143
> <https://github.com/emoncms/MyHomeEnergyPlanner/issues/143> *Inputting
> some data in two places* as this issue will cover it as well.
>
> So far the systems used for lighting, cooking, appliances, space heating
> and water heating were inputted in the *Systems* page but because of SAP
> worksheet we were asking for similar information in all the specific pages.
> In order to avoid this we decided to use the *Systems* page as a display
> of information about fuel totals (emissions, primary energy and annual cost
> per type of fuel). The info about fuel (type and fraction of demand) and
> system efficiency will only be inputted in the specific pages.
>
> carlos
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/emoncms/MyHomeEnergyPlanner/issues/158>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/APjOK45MpBRedFDSy4X_hb0WaFvqQsdMks5qN7H2gaJpZM4I6ipU>
> .
>


-- 
*Marianne Heaslip*
Associate Principal

*URBED (Urbanism Environment and Design) Ltd*a. 5th Floor, 10 Little Lever
Street, Manchester, M1 1HR
t. +44 (0)161 200 5500 <%2B44%20%280%29161%20200%205509>
e. marianne@urbed.coop <vicky@urbed.coop>
w. www.urbed.coop

*Please note I work Wednesday to Friday. *On other days, please contact my
colleague Lorenza Casini.

Urban Design Group Awards 2015 - Winner in the Best Practice Category for
Trent Basin
Wolfson Economics Prize 2014 - Winner: Uxcester Garden City Proposal
Community Land Trust Network Awards 2012 - Awarded for excellence in
community engagement 2Up 2Down / Homebaked
URBED (Urbanism Environment & Design ) Ltd is a limited company with
co-operative rules registered in England and Wales NO. 5741006. Please
access the attached hyperlink for an important electronic communications
disclaimer: http://www.urbed.coop/emaildisclaimer
<http://www.urbed.coop/emaildisclaimer.>

Please save paper and only print this email if you have to.

**Comment by cagabi** [comment]
Thanks Marianne.

Now the real reason why i opened the issue is that i have a question.

I am almost done with adding the fuel to LAC using SAP calculations but i have a doubt: the fuel input (currently in Energy Systems) is calculated taking the efficiency of the system. I am assuming that for lighting and appliances (as they are electric) efficiency will be 1, but what about cooking **what efficiency should i assume if the fuel for cooking is different than electric??**

**Comment by marianneURBED** [comment]
For the basic SAP calculations I think we just assume that all cooking is
electric - I'm pretty sure this is what most SAP calculators do, and we
won't be using this method much anyway.

For when we're entering in the Carbon Coop appliances list, can we not
enter the efficiency on a per appliance basis? This is something we can
probably work out/ get some monitored figures for.

I'm on my way to London today, so won't be able to look at this in detail
til tomorrow afternoon - let me know if you need to chat then.

Marianne

On 21 June 2016 at 10:55, carlos Alonso Gabizón <notifications@github.com>
wrote:

> Thanks Marianne.
>
> Now the real reason why i opened the issue is that i have a question.
>
> I am almost done with adding the fuel to LAC using SAP calculations but i
> have a doubt: the fuel input (currently in Energy Systems) is calculated
> taking the efficiency of the system. I am assuming that for lighting and
> appliances (as they are electric) efficiency will be 1, but what about
> cooking *what efficiency should i assume if the fuel for cooking is
> different than electric??*
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/emoncms/MyHomeEnergyPlanner/issues/158#issuecomment-227394277>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APjOKwoVF-ggG9Tecn1kEMoaRuTM7K9mks5qN7USgaJpZM4I6ipU>
> .
>



-- 
*Marianne Heaslip*
Associate Principal

*URBED (Urbanism Environment and Design) Ltd*a. 5th Floor, 10 Little Lever
Street, Manchester, M1 1HR
t. +44 (0)161 200 5500 <%2B44%20%280%29161%20200%205509>
e. marianne@urbed.coop <vicky@urbed.coop>
w. www.urbed.coop

*Please note I work Wednesday to Friday. *On other days, please contact my
colleague Lorenza Casini.

Urban Design Group Awards 2015 - Winner in the Best Practice Category for
Trent Basin
Wolfson Economics Prize 2014 - Winner: Uxcester Garden City Proposal
Community Land Trust Network Awards 2012 - Awarded for excellence in
community engagement 2Up 2Down / Homebaked
URBED (Urbanism Environment & Design ) Ltd is a limited company with
co-operative rules registered in England and Wales NO. 5741006. Please
access the attached hyperlink for an important electronic communications
disclaimer: http://www.urbed.coop/emaildisclaimer
<http://www.urbed.coop/emaildisclaimer.>

Please save paper and only print this email if you have to.

**Comment by cagabi** [comment]
With regards to SAP cooking, that works for me. In fact I'm now looking in detail how we calculate annual demand for SAP cooking and we do it from the cooking emissions (which calculation is defined in SAP) applying electricity CO2 factor, So your answer makes total sense.

About Carbon Coop appliances and detailed list, yes the solution is to input the efficiency there as well

Thanks

**Comment by cagabi** [comment]
I am working on Carbon Coop appliances and cooking:
- As we will give the option to choose the fuel, I am splitting the items in the list in between the ones that use gas or electricity. But i don't know what to do with DHW (I guess it is Direct Hot Water)
- What is the menaing of *Reference quantity*
- What is the *Utilisation factor*? is it the efficiency?
- I am implementing this list of appliances and cooking as a proper library so we can easily add new items.

**Comment by marianneURBED** [comment]
Hi Carlos,


   - DHW = domestic hot water. So it means this appliance uses hot water
   from the main house hot water system, and therefore whatever fuel that
   uses. Might need a bit of thought about how to account for this.
   - Reference quantity = no of these appliances or number of people (this
   varies by appliance if I remember right). We can look to change/ simplify
   this if needed.
   - Utilisation factor is a standard multiplier for how much a thing is
   used. It's just a multiplier that accounts for the fact you (probably)
   don't have your washing machine on 24 hrs/day.
   - Great, thanks.

Marianne


On 21 June 2016 at 12:41, carlos Alonso Gabizón <notifications@github.com>
wrote:

> I am working on Carbon Coop appliances and cooking:
>
>    - As we will give the option to choose the fuel, I am splitting the
>    items in the list in between the ones that use gas or electricity. But i
>    don't know what to do with DHW (I guess it is Direct Hot Water)
>    - What is the menaing of *Reference quantity*
>    - What is the *Utilisation factor*? is it the efficiency?
>    - I am implementing this list of appliances and cooking as a proper
>    library so we can easily add new items.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/emoncms/MyHomeEnergyPlanner/issues/158#issuecomment-227415248>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APjOK35fTYnS3RsUkBabB3z6hIwyvRIYks5qN832gaJpZM4I6ipU>
> .
>



-- 
*Marianne Heaslip*
Associate Principal

*URBED (Urbanism Environment and Design) Ltd*a. 5th Floor, 10 Little Lever
Street, Manchester, M1 1HR
t. +44 (0)161 200 5500 <%2B44%20%280%29161%20200%205509>
e. marianne@urbed.coop <vicky@urbed.coop>
w. www.urbed.coop

*Please note I work Wednesday to Friday. *On other days, please contact my
colleague Lorenza Casini.

Urban Design Group Awards 2015 - Winner in the Best Practice Category for
Trent Basin
Wolfson Economics Prize 2014 - Winner: Uxcester Garden City Proposal
Community Land Trust Network Awards 2012 - Awarded for excellence in
community engagement 2Up 2Down / Homebaked
URBED (Urbanism Environment & Design ) Ltd is a limited company with
co-operative rules registered in England and Wales NO. 5741006. Please
access the attached hyperlink for an important electronic communications
disclaimer: http://www.urbed.coop/emaildisclaimer
<http://www.urbed.coop/emaildisclaimer.>

Please save paper and only print this email if you have to.

**Comment by cagabi** [comment]
Thanks for that Marianne for the clarifications,

For now I am not going to add the DHW. Once the Hot Water section is sorted we will find the way to get the info we need from there.

 Carlos

**Comment by cagabi** [comment]
Hi,

I have done and uploaded the changes:

- Fuel to be inputted in LAC
- *Systems* page has been replaced by *Fuel requirements*

There has been quite a lot of changes in the code and calculations but it is worth. This approach works very well and clear to me. It would be great Marianne if you can have a look. I am working this afternoon and can have a chat or do a screen share if this speeds up the process. Need to finish organizing my week and will be able to say which other days I'm working so thatwe can talk about next steps (heating/water systems)

  Carlos

**Comment by marianneURBED** [comment]
Hi Carlos,

I'm afraid I have other stuff I need to do today and tomorrow (non-URBED
things), then I'm on site visits and out and about on Wednesday, but can
look at this on Thursday/Friday. Was planning on spending some time on
those days fiddling and testing and populating libraries.

Thanks,

Marianne



On 27 June 2016 at 10:40, carlos Alonso Gabizón <notifications@github.com>
wrote:

> Hi,
>
> I have done and uploaded the changes:
>
>    - Fuel to be inputted in LAC
>    - *Systems* page has been replaced by *Fuel requirements*
>
> There has been quite a lot of changes in the code and calculations but it
> is worth. This approach works very well and clear to me. It would be great
> Marianne if you can have a look. I am working this afternoon and can have a
> chat or do a screen share if this speeds up the process. Need to finish
> organizing my week and will be able to say which other days I'm working so
> thatwe can talk about next steps (heating/water systems)
>
> Carlos
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/emoncms/MyHomeEnergyPlanner/issues/158#issuecomment-228698922>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/APjOK1qiNeJaJxixkG2pN4mtNIOgEm3Jks5qP5qBgaJpZM4I6ipU>
> .
>



-- 
*Marianne Heaslip*
Associate Principal

*URBED (Urbanism Environment and Design) Ltd*a. 5th Floor, 10 Little Lever
Street, Manchester, M1 1HR
t. +44 (0)161 200 5500 <%2B44%20%280%29161%20200%205509>
e. marianne@urbed.coop <vicky@urbed.coop>
w. www.urbed.coop

*Please note I work Wednesday to Friday. *On other days, please contact my
colleague Lorenza Casini.

Urban Design Group Awards 2015 - Winner in the Best Practice Category for
Trent Basin
Wolfson Economics Prize 2014 - Winner: Uxcester Garden City Proposal
Community Land Trust Network Awards 2012 - Awarded for excellence in
community engagement 2Up 2Down / Homebaked
URBED (Urbanism Environment & Design ) Ltd is a limited company with
co-operative rules registered in England and Wales NO. 5741006. Please
access the attached hyperlink for an important electronic communications
disclaimer: http://www.urbed.coop/emaildisclaimer
<http://www.urbed.coop/emaildisclaimer.>

Please save paper and only print this email if you have to.

**Comment by cagabi** [comment]
This was done a while ago :)

  Carlos
