### ISSUE TITLE
Add appliances that feed from the Domestic Hot Water system (in Carbon Coop appliances and cooking)

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#159]
To be done once the Water Heating is redone.

**Comment by marianneURBED** [comment]
Agreed. Doesn't need to be done now, so removing the 'for release' tag.

**Comment by marianneURBED** [comment]
Sorry, just re-read your email, so leaving this here for you.

**Comment by cagabi** [comment]
I took this issue to bed with me yesterday and after a lot of thinking I couldn't see an easy coding solution. Then while i was writing this comment this morning I thought _come on you can do it_. Three hours later i go back to the original thought and i don't think it is worth to implement this :(

First we need a way of telling the appliance is hot feed (this would be easy, just a tick box in the library item) and when that happens we need to to ask for the fraction of electricity and the fraction from the hot water system. Once the appliance is added we need to display all the water heating systems and finally do the calculations of energy demand and fuel input. So I know all the things to do but the implementation is very difficult, requires many changes everywhere and so it is messy.

But i think there is a workaround to it which would work despite it is not very elegant: a hot feed dishwasher is equivalent to an electric dishwasher and a "gas" dishwasher, the fraction of energy coming from each fuel can be set in the utilisation factor of the appliance. It's not ideal as the assesor should check the efficiency of the hot water system and then copy it into the _hot feed_ dishwasher efficiency.

What do you think? If you really want it there i can do it, but i prefer to check before spending more time

**Comment by marianneURBED** [comment]
Hi Carlos, 

We come across 'hot feed' appliances so infrequently that I don't think this is worth it right now. Pretty much all washing machines and dishwashers are cold feed. 

Just leave things as they are for now. I think if/when we review the whole hot water section (to take better account of water used for showering in particular) we can look at this again - bit it's not a significant enough issue for it to be worth spending time on for this release. 

Hope that takes a weight off your mind!

M

**Comment by marianneURBED** [comment]
Showering issue to be dealt with elsewhere - in hot water calc changes under SAP 10 review - otherwise hot water feed appliances are so rare we should just close this.
