### ISSUE TITLE
Measures for ventilation systems - Ventilation / planned

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#16]
Need to be able to add ventilation systems as measures. eg, add a extract fans to the measures list or whole house systems (MEV, Passive or MVHR) 

CARLOS TO ADD A LIBRARY IN THIS SECTION

MARIANNE NEEDS TO SEND A RUN DOWN OF LIBRARY ELEMENTS TO CARLOS

**Comment by cagabi** [comment]
Hi,

I am working right now, in *Energy Requirements* for *Fans and Pumps*. The SAP calculations take into account systems used for *Ventilation*. I have added support for it when calculating the *Energy Requirements* so I think this could be the next issue i deal with. 

Can you please forward the **list of Ventilation Systems**. Not great rush but would be good at some point next week if you are not in Christmas jolly hols ;)

Thanks,

   Carlos

**Comment by cagabi** [comment]
Notes for Carlos:

- Ventilation systems to be stored in: data.ventilation.systems
- Each ventilation system has to specify its annual energy use (kWh/year) in: data.ventilation.systems[system].annual_energy_use
- Energy System page to fetch and display Energy Requirements for Ventilation

**Comment by cagabi** [comment]
Sorry for bombarding you with comments,

Right now i can get the *annual energy use* for *Ventilation* from the *Select ventilation type:* in the *Ventilation* page and match it with the table 4f in the SAP document (page 213). Two questions:
- The user can choose MV or MVHR, but they are not in the SAP table. I guess they are both *Mechanical extract ventilation*, can you confirm this please?
- Thinking about the implementation of measures for Ventilation, how will it work? Will *Apply Measure* get rid of the *Ventilation Type* chosen by the user? can we think a way of combining them?? This question doesn't need to be replied now.

  carlos

**Comment by marianneURBED** [comment]
Hi Carlos, 

I'm still working at the start of next week, so I'll get onto this and any other comments and queries then. 

Thanks,

Marianne

**Comment by cagabi** [comment]
HI again,

I am having another a look at this.

There is not a unique formula for calculating  the *effective air change rate*. The formula is dependant on  the *Ventilation type* (SAP2012, p. 180). Therefor the systems in the *Ventilation systems library* can only be the ones we have already got.

It still makes sense to add them from a library because this will make applying a measure (replacing the ventilation system) easier. 

A Ventilation system will be defined by:
- Name
- Air change rate (being 0 for natural ventilation)
- Heat recovery efficiency (being 0 for every system except MHVR)
- SFP: specific fan power (being 0 for natural ventilation)
- IUF: applicable in-use factor (being 0 for natural ventilation)

What i am not sure is how we can combine this with any other type of measures you are thinking (like adding extra fans). If this measures don't affect the *effective air change rate* and only affect the *Energy requirements* and *Internal heat gains* maybe we could add another section to the *Ventilation* page called something like *Extra elements*. There could be a different library for these ones and the elements here will be defined by:
- Name
- SFP: specific fan power (being 0 for natural ventilation)
- IUF: applicable in-use factor (being 0 for natural ventilation)

This could also allow us to add elements that don't affect the calculations (SFP and IUF = 0) like *laundry* and *clothes drying facilities* as specified in [issue 20](https://github.com/emoncms/MyHomeEnergyPlanner/issues/20)

  Carlos

**Comment by cagabi** [comment]
Carlos to implement the library from the *measures list document*.  Ventilation systems will be matched with the ones in that list

With regards to number of fans, vents... An *Apply measure* button to be added to allow to change the number as measure

   Carlos and Helen

**Comment by lowwintersun** [comment]
@marianneURBED and I will look at resourcing @gervasemangwana to populate this library

**Comment by cagabi** [comment]
**Forget comments above**

Apply measure to *ventilation type* from library. Fields for library items:
- Typical ones
-  Ventilation type
- Air change rate : displayed if type is *DEV, MEV *or *MVHR.
- Heat recovery efficiency: if type is *MVHR*
- Intermitent fans: 0 or  +1 (Apply measure fiunction must understand the meaning of +)
- Passive vents

**Comment by cagabi** [comment]
Done!!!

Look out for the option to use *+* when applying a measure to increase the number of passive vents and/or intermittent fans. You will not believe the pain that *+* has been.

  Carlos

**Comment by cagabi** [comment]
Just noticed *VS_08: Stack ventliation - reduced overheating risk* and *VS_09*, will these ones keep the current ventilation type?

  Carlos

**Comment by marianneURBED** [comment]
Hi Carlos,

We were having a debate as to where these should be.

They are 'summer' ventilation measures, intended to help prevent
over-heating.

They won't affect the calcs as they stand - though if we ever got into
calculating over-heating risk they would.

They're not needed for the current release anyway - they're a 'nice to
have'.

I'd say either keep this issue open for them, or start a new one on
overheating measures and mark it as medium priority ( would do this myself
but am answering this on my phone on the train to Manc).

Thanks,

Marianne.

On Friday, April 1, 2016, carlos Alonso Gabizón <notifications@github.com>
wrote:

> Just noticed *VS_08: Stack ventliation - reduced overheating risk* and
> *VS_09*, will these ones keep the current ventilation type?
>
> Carlos
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/emoncms/MyHomeEnergyPlanner/issues/16#issuecomment-204358624>
>


-- 
*Marianne Heaslip*
Architect/Sustainability Consultant

*URBED (Urbanism Environment Design) Ltd *a. 5th Floor, 10 Little Lever
Street, Manchester, M1 1HR
t. +44 (0)161 200 5500
e. marianne@urbed.coop
w. www.urbed.coop

Fire destroys Toxteth Food Central - we need your help!
<http://us6.campaign-archive1.com/?u=47ce46e3ee9278b42c90d7d62&id=a927286bfc&e=e1c312350a>

URBED is 40 and hosting 7 unique events over 2015 to celebrate.
<http://urbed.coop/events>
Urban Design Group Awards 2015 - Winner in the Best Practice Category for
Trent Basin
Wolfson Economics Prize 2014 - Winner: Uxcester Garden City Proposal
Community Land Trust Network Awards 2012 - Awarded for excellence in
community engagement 2Up 2Down / Homebaked
URBED (Urbanism Environment & Design ) Ltd is a limited company with
co-operative rules registered in England and Wales NO. 5741006. Please
access the attached hyperlink for an important electronic communications
disclaimer: http://www.urbed.coop/emaildisclaimer
<http://www.urbed.coop/emaildisclaimer.>

**Comment by cagabi** [comment]
Ok, i am closing this issue and have created a new one #126 
  carlos
