### ISSUE TITLE
Review CarbonCoop Apliances & Cooking library

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#160]
In order to:
- Add the DHW ones
- Check the efficiency, I have added this to every Appliance but put 100% to all of them

**Comment by cagabi** [comment]
I have started a new sheet in the *My Home Energy Planner - Libraries Elements Naming Conventions* GSheet

**Comment by marianneURBED** [comment]
Subsumed in general libraries review.
