### ISSUE TITLE
LAC, Carbon Coop Calc - ticking A+ 

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#161]
1. When you tick A+ for an appliance on the Carbon Coop calculator, it changes the Energy Demand figure, but not the fuel input figure (which should go down proportionally). 

2. Should utilisation factor always be 1? (Think so in this case, as we haven't allowed for condensation dryer etc) If so, we can remove it from calc, as will always just multiply by 1. (Though won't do any harm to keep in case for future). 

 3. Think 'efficiency' prob not needed here, as already accounted for in figures given for each appliance, so again will always be 1 and can be removed? (Though also won't do any harm to keep in case for future).

**Comment by marianneURBED** [comment]
sorry - ignore the bit about efficiency - just remembered your other comment in relation to DHW and appliances.

**Comment by cagabi** [comment]
A+ bug fixed.

I haven't done anything about *utilisation factor* as it sounds it may become handy.

   Carlos
