### ISSUE TITLE
Energy for 'fans and pumps' of Warm Air Systems

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#166]
From the GDoc: the value is a calculation *SFP x 0.4 xVt*

I understand the logic but we need to put a number there and find the way of telling the assessor to be calculated when using one of these systems.

**Comment by cagabi** [comment]
Marianne this one is for you

**Comment by marianneURBED** [comment]
Ok. From digging around previously I'd suggested in the gsheet a standard SFP value of 1.5. 

Then presumably we can calculate the volume of the property from the measurement data already entered? 

Don't think we need to do more than this - we come across these so rarely, and they're likely to be so old, that we can stick with a standard figure for the SFP, and not ask assessors to do any other faffing.

**Comment by cagabi** [comment]
This finally works very well and sorry i could have worked it out myself. Now when the "Warm air systems" category is chosen the input for _Fans and _pump_ is replaced by a _SFP_ one. Then the energy for _Fans and pumps_ is calculated later.

  Carlos
