### ISSUE TITLE
Measures for hot water - Hot water use

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#17]
Need to be able to display descriptive items for this in the measures list for the report, eg 'low flow shower head', 'low flow taps'. 

CARLOS TO ADD A LIBRARY IN THIS SECTION

MARIANNE NEEDS TO SEND A RUN DOWN OF LIBRARY ELEMENTS TO CARLOS

**Comment by cagabi** [comment]
Add coefficient to be used instead of _data.water_heating.low_water_use_design_

**Comment by marianneURBED** [comment]
This is now done - though hot water calcs etc may be reviewed in future.
