### ISSUE TITLE
Cost of measures

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#174]
For carlos: do it properly:
- Add _cost_units_ to all the measures in library
- Do calculation in CarbonCoop report accordding to the type  of _cost_units_

**Comment by cagabi** [comment]
Marianne: to change the ventilation system (applying a measure) to IE has a cost according to the GSheet of £500 but then adding _intermettent fans_ as measures are £150 per unit. Is this right? Should the change to IE cost 0 so that all the cost is calculated from the addition of fans?

The same thing applies to _Passive stack_ and _Passive Vents_

**Comment by marianneURBED** [comment]
Hi, 

Yes, sounds sensible to change it so the costs for IE are associated with the number of fans - especially as quite often we're suggesting people just add one fan as a first simple step to improve ventilation and air quality. (People often have an extract in the bathroom but not kitchen or vice versa). Given that there should also be some cost small allowance for trickle vents to supply the inlet air (which people might have already, or in some cases might need to install) I'd suggest actually bumping that up to £250 per fan. Can update the description to make this clear. 

For passive stack we could do the same, but it should be costed at £450 per extract, which again allows some money to also sort the inlet. We can estimate the number of extracts pretty quickly (one per 'wet' room), but we won't have time and info to be able to estimate the inlets required, so this can be a ready-reckoner. 

I'll update the g-sheet to show this. 

Thanks, 

Marianne.

**Comment by cagabi** [comment]
Done
