### ISSUE TITLE
Fabric efficiency

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#178]
I thought there was an issue for this but there isn't.

We are calculating Fabric Energy Efficiency wrong: annual heating demand / floor area

Shoud be done as per SAO2012 section 11 p. 31

I see we use it in the report but nowhere else, should this bi tagged as For Release??

**Comment by marianneURBED** [comment]
Hi Carlos, 
I think this is an incorrect terminology thing. It would make sense to change the wording in the report to 'space heating demand' rather than re-doing or adding to the calcs so they accord with SAP's definition of fabric energy efficiency (*relieved face*)

**Comment by cagabi** [comment]
_Relieved face too_

In fact in the report it is called as you say _Space heating demand_ and it is expressed by square meter.  So it is wrong the name we use in the calculations.

Sorted _(more relieve face :p_
