### ISSUE TITLE
Check text in report - clarify and make transparent assumptions about energy costs and income. 

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#179]
Mainly because it says (at least on the section 1.00 many times that we are implementing SAP, it may be enough adding a line saying that we have done some changes to the SAP model.

   Carlos

PS: by the way, I am already making changes in the report. I am not opening issues for them as I am dealing with things as I find them. I will open issues, as this time, that are not for me or that need more opinions

**Comment by cagabi** [comment]
Should we say in figure 10 that income due to renewables is substracted from the _Energy cost_?

**Comment by marianneURBED** [comment]
Agree. In we should add this somewhere in the methodology section. 

And if you mean Feed in Tariff income from renewables is subtracted from energy costs, I don't think it does do this. It just makes an assumption about what you use on site (so don't pay for) vs what gets exported. Probably worth checking this in detail though.

**Comment by cagabi** [comment]
Ok, I'll wait for some text for the methodoly section.

About the figure 10, you are right, we are not taken into account the FIT only the saving for onsite use of renewable. I still we may need to tell  it too when explaining hte figure

**Comment by marianneURBED** [comment]
Ok. Have added in PDF at #211 so closing this issue now.
