### ISSUE TITLE
Measures wihout impact in calcs - Fabric / ventilation

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#18]
Loft Hatch and access hatches - new or refurbished; eg loft storage

TO BE APPLIED UNDER ROOF; ELEMENTS TO BE GIVEN AN AREA AND ADDED AS AN ELEMENT AND A MEASURE;

MARIANNE NEEDS TO SEND A RUN DOWN OF LIBRARY ELEMENTS TO CARLOS

NO IMPACT ON CALCS

**Comment by lowwintersun** [comment]
@marianneURBED  and I will look at resourcing @gervasemangwana  to populate this library

**Comment by marianneURBED** [comment]
Loft hatches now fully integrated as measures.
