### ISSUE TITLE
Show error bars in fig. 6

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#180]
For Carlos: _variance_ property of data object is not displayed for a weird reason that i cannot find

**Comment by cagabi** [comment]
The information below the graph says _Figure 6 includes error bars with a 30% positive and negative range_

With this type of graph we cannot use _error bars_ , each stack is the addition of Gas, electricity and Other,  and the graph plugin is not able to calculate the error.

Two options:
- Remove the text and forget about error bars
- change how the data is displayed and instead of one stack per scenario we display 3

**Comment by marianneURBED** [comment]
Remove the error bars I think. 

I know showing three stacks for each scenario would achieve the same effect, but I think it would be confusing. Will just have to rely on caveats in text, reminding people that it's a model for testing options, not an accurate predictive tool.

**Comment by cagabi** [comment]
Ok, I prefer you giving me the text. Can you tell me what to replace this with?

_Figure 6 includes error bars with a 30% positive and negative range. These error bars are included because the model is only ever an approximation of reality. Your actual energy use is affected by factors such as the external climate and the way you use energy in your home – so it will change over time._

**Comment by cagabi** [comment]
Sorry, I have just seen you provided the text in pdf issue 211
