### ISSUE TITLE
CO2 saved due to generation in figures 8 and 9

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#181]
The data shown in figures 8 and 9 already takes into account the generation. I mean we are displaying 
`CO2 generated - CO2 saved`

Would it be better to show all the emissions displaced as we do in figure 7 (primary energy)??

**Comment by marianneURBED** [comment]
Yes! If that's not too much trouble - does make things more transparent. Though I think it's lower priority, and we don't necessarily need it for the release.

**Comment by marianneURBED** [comment]
Think there's a review of the whole report format due - but in the meantime, this is quite important.

**Comment by cagabi** [comment]
Hi, I have implemented this. 

This is the text already there for figures 7, 8 and 9

> If you have existing on site electricity generation equipment, such as solar panels, any electricity you generate and then use yourself will not be shown on your electricity bill. This is because you have not paid to import this electricity from the national grid. As such, your bill data can suggest that your electricity usage is lower than reality, and this in turn affects your total Primary Energy Use figure. Where import, export and generation of electricity is not metered separately, we have to make some assumptions to give a more accurate representation of electricity use in your home now. In the graph below, we assume that you use a certain proportion of the electricity you generate yourself (usually around 50%, though we adjust this depending on how you occupy your home). We then add this to the figure given in your bills for electricity usage to give a more accurate picture of your total electricity use [or carbon, depending on the figure].

That text was wrong in terms of Bills data because what we do (for Current Energy and the scenarios) is to deduct the emissions saved with generation  from the total emissions, proper offsetting. So what about something like:

> If you have existing on site electricity generation equipment, such as solar panels, any electricity you generate and then use yourself will not be shown on your electricity bill. This is because you have not paid to import this electricity from the national grid. As such, your bill data can suggest that your electricity usage is lower than reality, and this in turn affects your total Primary Energy Use figure. ~~Where import, export and generation of electricity is not metered separately, we have to make some assumptions to give a more accurate representation of electricity use in your home now. In the graph below, we assume that you use a certain proportion of the electricity you generate yourself (usually around 50%, though we adjust this depending on how you occupy your home). We then add this to the figure given in your bills for electricity usage to give a more accurate picture of your total electricity use [or carbon, depending on the figure].~~ In the graph below, the savings due to generation are shown as negative giving you a better idea of how much primary energy you are really using.

**Comment by marianneURBED** [comment]
Hi Carlos,

I think I understand what you’ve done here, but the implementation of graphs in new reports seems to be broken at the moment, so I can’t check it.

I built a new model last week, but when I go to the report, the graphs aren’t populated. Have just shared the assessment in question with you (id249). Though something seems to be broken in the sharing too – when I open the share assessment dialogue box, it says’ assessment is shared with ‘null’, and then when I add your name and click the button, it seems to jump and indicate something has happened, but still says ‘null’.

M

(And yes, I’m looking at this on a Sunday cause I’m currently on a train through very flat and boring countryside in the south east of England. Rather look at a computer screen to sort this than get freaked out by the lack of hills 😉. )

**Comment by cagabi** [comment]
That assessment didn't have anything in the household questionnaire and the report was breaking when trying to fetch that.
It's fixed now so you should be able to see the graphs

**Comment by marianneURBED** [comment]
Done.
