### ISSUE TITLE
Party wall library

### ISSUE THREAD

**Issue by helen-urbed** [emoncms/MyHomeEnergyPlanner#186]
Unable to add a party wall because the library doesn't appear. Can create a new item (and see relevant wall tags when selecting 'copy from existing library'), but even after saving this isn't visible either.

**Comment by cagabi** [comment]
Right now, there is no PartyWall in the library, so it is not that the library doesn't appear, it's just empty

Did you make the _PWUS_01_duplicate_? If so, you made it as a Wall.

I think this is not a bug, it is that you are not changing the _Type_ of the element when you create it.

Please give it another go. In the pop up window where you add the info about the element you need to select _Party wall_ from the drop down. I know it is very annoying, Gervase did complain about this in the past but there is no solution for it.
