### ISSUE TITLE
Fuel requirements

### ISSUE THREAD

**Issue by helen-urbed** [emoncms/MyHomeEnergyPlanner#188]
Ability to delete if added in error. Not urgent as fraction can be reduced to 0. 
![screen shot 2016-10-28 at 15 06 51](https://cloud.githubusercontent.com/assets/15141180/19809839/006296b8-9d23-11e6-8dcd-7835438a40e3.png)

**Comment by marianneURBED** [comment]
Similarly, on appliances page - ability to delete fuel if added in error for Lighting.

**Comment by marianneURBED** [comment]
My comment now dealt with. Helen's still to do.

**Comment by cagabi** [comment]
Done
