### ISSUE TITLE
Report: listing of windows in scenarios

### ISSUE THREAD

**Issue by helen-urbed** [emoncms/MyHomeEnergyPlanner#189]
We may need a more streamlined way of presenting windows - currently each individual window is inserted into the scenario - we commonly recommend replacement windows as a package so the ability to group these and only insert the measure once would be useful. 

![screen shot 2016-10-28 at 15 28 27](https://cloud.githubusercontent.com/assets/15141180/19809972/83483ac4-9d23-11e6-98e1-ff7ef22c0173.png)

**Comment by cagabi** [comment]
From #190 we need the _Ability to do a bulk 'apply measure' would be useful for windows._

Both things can be combined, so the in bulk measure would only be applied once, therefor logged once and finally added to the report only once.

**Comment by cagabi** [comment]
Done
