### ISSUE TITLE
Measures for Ventilation - Fabric / ventilation

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#19]
eg Filling chimneys with insulation

ADD TO VENTILATION MEASURES

MARIANNE NEEDS TO SEND A RUN DOWN OF LIBRARY ELEMENTS TO CARLOS

NO IMPACT ON CALCS

**Comment by marianneURBED** [comment]
Done.

**Comment by cagabi** [comment]
Jejeje, it's great to see 2 years old issues closed :)
