### ISSUE TITLE
Review default library Wall elements

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#192]
Only one Solid wall. Do we want two?

**Comment by marianneURBED** [comment]
Yep, good idea. Have added some solid stone walls to the g-sheet. Using values/calcs from SAP for now - though I think they may be on the high side. Think this will come out in forthcoming update to SAP with evidence from STBA/SPAB etc.

**Comment by cagabi** [comment]
Done
