### ISSUE TITLE
Add Double glazed Aluminium frame window to default library?

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#193]
Only single glazed there.

**Comment by gervasemangwana** [comment]
WWAD_01 added to windows

**Comment by gervasemangwana** [comment]
WWAD_01 added to windows

**Comment by gervasemangwana** [comment]
WWAD_01 added to windows

**Comment by gervasemangwana** [comment]
WWAD_01 added to windows

**Comment by gervasemangwana** [comment]
WWAD_01 added to windows

**Comment by gervasemangwana** [comment]
WWAD_01 added to windows

**Comment by gervasemangwana** [comment]
WWAD_01 added to windows

**Comment by gervasemangwana** [comment]
WWAD_01 added to windows

**Comment by gervasemangwana** [comment]
WWAD_01 added to windows

**Comment by gervasemangwana** [comment]
WWAD_01 added to windows

**Comment by gervasemangwana** [comment]
WWAD_01 added to windows

**Comment by marianneURBED** [comment]
Is in G-sheet, so just needs added to online version.

**Comment by cagabi** [comment]
Done with issue #198
