### ISSUE TITLE
No Doors and roof lights in the library

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#195]
Need some to be added to GSheet?

**Comment by marianneURBED** [comment]
Have added them to g-sheet  - existing and measures. 

Is a question over how to treat doors where u-value and ff will vary by proportion of glazing. Would it be acceptable to approximate this do you think? So have a solid door, one with <25% glazing, one with 25-50% glazing etc - or similar?

**Comment by gervasemangwana** [comment]
that seem sensible

I had similar idea


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by marianneURBED** [comment]
Grand. Added to g-sheet with a hopefully sensible split of glazing areas. See what you reckon.

**Comment by cagabi** [comment]
I have added them to the library.

The doors as measures (the ones with glass) have not got a value for ff, I have put 0.7 to have something but it is pretty random as I know it depends on how big is the glazing. What shall we do?

**Comment by marianneURBED** [comment]
Hi. My mistake - I thought I'd picked that up. 

Could we set it as 0.4 please - i.e. 40% glass? (have updated this in the g-sheet). And also add a bit on assumptions for glazing proportions to the description/ name)

On the basis that we're not going to know when carrying out the assessment what style of door someone will eventually choose, and this is the middle of the range. If it's a solid door, there's an option for that. If it's likely to be a 'patio/ french door style thing that's mostly glazed, it can be treated as a window (and this is how GBS cost them too - 'entrance doors' are at a different price point to glazed patio doors).

Hope that makes sense, but let me know if not. 

M

**Comment by cagabi** [comment]
Thanks
