### ISSUE TITLE
No New Gas Combi Boiler with Rads without storage

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#196]
This seems like an important one to be in library I am adding to default but need to double check some of fields

This exists as a measure as CMBB6

CMBB5 is New gas Combi with Rads and Storage

Carlos concludes that heating system measures should be included in the heating system library

**Comment by cagabi** [comment]
I have copied over all _heating systems measures_ to _heasting systems_ library.

My original idea was to fetch and display the measures every time we display heating systems library. But that was not a good idea as there may be more than on measures library, so which one would we pick. Finally i just added the measures to heating system libraries.
