### ISSUE TITLE
When Master Scenario is copied Primary Energy demand and SAP rating changes 

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#197]
63 Nicholas Rd goes from SAP 49 to SAP 48. PED goes up from 371 to 375

**Comment by gervasemangwana** [comment]
The reason is that Fuel requirements for Fans and Pumps has disappeared from original master but is there when a copy is made.

**Comment by cagabi** [comment]
Strange behaviour. I haven't been able to replicate.

I know you texyed me to say that Fuel requirements for Fans and Pumps came back, even more strange.

I leave issue open just in case it happen again

**Comment by cagabi** [comment]
As it doesn't seem to have happened again and I couldn't replicate it, I am closing this issue
