### ISSUE TITLE
Secondary Glazing as a measure?

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#198]
Could be good for Scenario 1

**Comment by marianneURBED** [comment]
Yep. Have added to the g-sheet - highlighted in red on left hand side as not yet added to online libraries. 

Have also added a change of glazing units - single to double in timber, and double to triple in uPVC. Can add more as we go.

**Comment by gervasemangwana** [comment]
Great


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by cagabi** [comment]
added to library
