### ISSUE TITLE
Can not add Window as measure

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#199]
When I click apply measure after selecting one in the pop up measures library nothing happens.

**Comment by gervasemangwana** [comment]
Ok Working now. Not sure what was going on there. Refresh sorted it,

**Comment by cagabi** [comment]
The library helper was not reinitialized when going from _libraries manager_ to _fabric_. Tha's why it was working after refresh.

Fixed now
