### ISSUE TITLE
Measures for ventilation - Ventilation

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#20]
Laundry and clothes drying facilities

AP! CARLOS TO ADD UNDER 'VENTILATION AND INFILTRATION' WITHOUT EFFECTING MODEL

MARIANNE NEEDS TO SEND A RUN DOWN OF LIBRARY ELEMENTS TO CARLOS

**Comment by marianneURBED** [comment]
Done.
