### ISSUE TITLE
When I open a brand new assessment the fields in Overview e.g. 'Space Heating Demand' show 'NaN'  

### ISSUE THREAD

**Issue by beaylott** [emoncms/MyHomeEnergyPlanner#201]
If nothing has been calculated yet they should probably show a '-' with an explanation of why they do not show a number yet...
![screenshot_2016-11-10_11-32-58](https://cloud.githubusercontent.com/assets/654056/20175272/d1c1fd00-a739-11e6-8e0c-ccbcedd4bfa9.png)

**Comment by cagabi** [comment]
Done
