### ISSUE TITLE
empty libraries

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#204]
When you apply a fabric measure,if the library is empty, it tries to display walls but the list of leasure is empty. The reason is that the library is empty no that there is a bug. Anyway adding a message saying _This library is empty_ would look nicer

**Comment by gervasemangwana** [comment]
I think it would be good better if it would allow you to add an element to a library from this point rather than having to go to library manager first.

**Comment by marianneURBED** [comment]
Rejigged on new framework.
