### ISSUE TITLE
After adding PV to scenario SAP number became 1297

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#205]
<img width="1016" alt="screen shot 2016-12-09 at 10 48 29" src="https://cloud.githubusercontent.com/assets/16294193/21046576/46280f48-bdfd-11e6-9f4c-db2f0d23df68.png">

**Comment by gervasemangwana** [comment]
This is to do with how it works in Fuel requirements and costs.
<img width="884" alt="screen shot 2016-12-09 at 11 20 48" src="https://cloud.githubusercontent.com/assets/16294193/21047421/ad1f90be-be01-11e6-8e38-6c093598f656.png">

**Comment by gervasemangwana** [comment]
Also is treating electricity cost in the unit cost field for generation as pounds not pence.

**Comment by cagabi** [comment]
Fixed
