### ISSUE TITLE
description field is not saved when creating an item in fabric measures

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#207]
I guess it happens with all the other libraries

**Comment by cagabi** [comment]
Only happened to that one as there were two descriptionn field, the first one was the one saving

**Comment by gervasemangwana** [comment]
Actually the first one it happened to was this one. Where there wasn’t anything in the first description.

I tried to add a few times including by editing in the libraries manager but it still shows empty there. 

It seems to me it may be copying the empty field from the first description.

Issue closed so I can’t do this in Github


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk
