### ISSUE TITLE
Report figure 7

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#208]
The report says: _Where possible this is also broken down by use. Where renewable technologies have been proposed, the primary energy they displace is shown as a negative quantity to your total (gross) energy use, and then subtracted from this total to show the net energy use for Your 2050 Home._

We cannot substract generation and at the same time keep the breakdown by use

![fig 17](https://cloud.githubusercontent.com/assets/7636325/21055163/3c5ada74-be28-11e6-8325-61d61df4f425.png)

**Comment by marianneURBED** [comment]
Ok. Two options then: 
1. ditch the text..."and then subtracted from this total to show the net energy use for Your 2050 Home", and just don't have a stack for net primary energy. In which case we'd have to ditch or alter the 'target' level. 
2. Add a stack that doesn't show uses, but has only a single stack for net primary energy. This is what we currently do in the spreadsheet - means we could keep the target line. 

I'm not fixed on doing it either way, so will take suggestions. Will be a question of which is clearest to read, and which is possible. Suspect Option 1 might be clearest - though maybe we should ask someone other than me to check? Maybe show it to Aneaka and see what she reckons.

**Comment by cagabi** [comment]
I think one of the best things of this graph is to have the target level as it gives a good picture of the situation. So I don't like option 1

What about displacing the stack itself when there are renewables? The text could simply read: _Where renewable technologies have been proposed, the stack has being displaced to negative values allowing your house to get closer to the 2050 Home._

**Comment by cagabi** [comment]
Bigger mission than expected but very happy with the result if you think it works ok.  Finally I have displaced the whole stack. Do you think it is easy to understand?

Are you happy with the text? _Where renewable technologies have been proposed, the stack has being displaced to negative values allowing your house to get closer to the 2050 Home_

![figure 7](https://cloud.githubusercontent.com/assets/7636325/21848499/fa702f70-d7f8-11e6-81f7-69076a8c0691.png)

**Comment by gervasemangwana** [comment]
That’s great Carlos. I think the text is clear. I think it would help understanding if in some way on the graph itself there was some kind of flag or note to link to the text. 


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by marianneURBED** [comment]
Hi Carlos, 

Yep, that looks great. 

Just a minor amendment to the text: 
"Where renewable technologies have been proposed, the stack has _been shifted down the negative  axis, so the graph shows your net total primary energy, once the contribution of renewable energy generated on site has been accounted for"._ 

M

**Comment by cagabi** [comment]
Ok, just changed the text. Thanks
