### ISSUE TITLE
Measures for appliances - Appliances

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#21]
eg monitors and master-switches

AP! CARLOS TO ADD UNDER APPLIANCES UNDER 'Appliances CarbonCoop calculation' NEW SUB-HEAD WITHIN APPLIANCES

MARIANNE NEEDS TO SEND A RUN DOWN OF LIBRARY ELEMENTS TO CARLOS

NO IMPACT ON CALCS

**Comment by marianneURBED** [comment]
We don't do this anymore - instead a general recommendation for people to buy more efficient appliances wherever possible, but sits outside the 'measures' libraries etc.
