### ISSUE TITLE
Report Format and Editing Various Issues 

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#211]
I've been through the report - see attached PDF for details and some text edits etc.

A few issues noted with the first (simplified) suggested measures table in report (figs 17-19):
- 'Performance Target' not showing. It needs to I think. 
- Label missing from 'Disruption' Column in printed PDF (see attached).  
- We definitely need to do something about how windows are displayed - either merging them into one, or labelling each with number/location. It's confusing to see them all listed out, especially when there's no discernible difference between them. 
 - Total cost for each scenario not currently being displayed - we definitely need this. 
 - Would be good to show title for each scenario if possible - gives them more meaning. 

Section 3 - Routes to Retrofit - please delete. Info now available elsewhere. Rename Section 4.  

Appendix (A?): Full table - needs formatting/display changes so shows up properly, as discussed previously. 

Appendix A (B?): Comparison table. Scenario 3 missing - not sure why. A couple of bits that look dodgy/ like they're pulling from elsewhere. Worth checking out why - is it looking at the right place? See PDF for detail. 
[20170110_My Home Energy Planner.pdf]
(https://github.com/emoncms/MyHomeEnergyPlanner/files/696523/20170110_My.Home.Energy.Planner.pdf)

Other than that, all looks good!

**Comment by lowwintersun** [comment]
Looks good - I wonder if it would be useful to stage the implementation of the comments ie get in essential changes first, improve the formatting as we go. 

I know Loz is up for advising on tweaking the formatting but I think that comes later.

**Comment by marianneURBED** [comment]
I think the issue is that for it to be understandable and usable by the average punter, the things listed above are essential. There are just a couple of minor comments on formatting in the PDF itself that are lower priority.

**Comment by lowwintersun** [comment]
Yes, I guess so. 
Thinking about future improvements too and hoping not to scare Carlos too much!

**Comment by cagabi** [comment]
Jajjajaja, I am ready for the action, There is nothing in MHEP that can scare me nowdays :PP

**Comment by cagabi** [comment]
I have done everything shown in the pdf except but:
- Fig 4: Mariane said _This will reduce in absolute terms when triple glazing etc is fitted - though should also increase as a total proportion. Would it be worth saying this? _ What shall i do?
- Section 1.5: Marianne said _I think we need to update the assumptions in SAP - electricity should be lower, biomass should prob be higher (but need supporting evidence in each case). _ I haven't done anything
- Fig 11: for FieldWork (see below)
- Tables in general have layout switched
- Window measures: I have been very reluctant to implement new functionality but in this case I am going to create this measure because it will make assessor's life easier and will make the table more readable

The look of the report is ok in the online version but the printing is terrible. I think that making it look nice is something that FieldWork will do better and quicker than me. They don't need to do any coding and will it be just playing with the layout and styles

**Comment by marianneURBED** [comment]
Hi Carlos,

I've attached an updated version of the annotated PDF, which includes the comments from Gervase and a few other bits and bobs. Mostly just text edits etc. Hopefully all makes sense, but let me know if not. 

In response to your queries above: 
Fig 4: Marianne said _This will reduce in absolute terms when triple glazing etc is fitted - though should also increase as a total proportion. Would it be worth saying this? _  **- I've added some text to the attached PDF on this.** 
Section 1.5: Marianne said _I think we need to update the assumptions in SAP - electricity should be lower, biomass should prob be higher (but need supporting evidence in each case). _ I haven't done anything - **Don't do anything yet. Looking at this at issue #226, and to do with assumptions in tool, not report itself.**
Fig 11: for FieldWork (see below) - Tables in general have layout switched - **Fair enough. Have made a note of this in the PDF.** 
Window measures: I have been very reluctant to implement new functionality but in this case I am going to create this measure because it will make assessor's life easier and will make the table more readable.  -  Ok I think this also relates to issues #189 and #190. 
[20170114_My Home Energy Planner.pdf](https://github.com/emoncms/MyHomeEnergyPlanner/files/705993/20170114_My.Home.Energy.Planner.pdf)

**Comment by marianneURBED** [comment]
Sorry, updated version of PDF - have checked and average UK Space Heating demand is now also down to around 120kWh/m2.a.

**Comment by cagabi** [comment]
I have done all the changes in the pdf except for the figure 2: at the bottom of the figure there is a legend with the colors for each scenario (so no need to add the scenario names to the graphs, which would not be straight anyway)

**Comment by cagabi** [comment]
I am closing this issue as eveything in pdf was made.

For any new Report issue, open a new issue
