### ISSUE TITLE
Names of Scenarios should appear in report

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#212]
List of places where they currently show as "Master, Scenario 1... etc"

Figure 2. Performance Summary

**Comment by gervasemangwana** [comment]
Figs 3 and 4

**Comment by gervasemangwana** [comment]
It is all figures

**Comment by marianneURBED** [comment]
Agree basic name 'Your home now', 'scenario 1' etc should appear (and currently don't on figure 2) - but not full name as this could become quite cluttered, depending on the names given by the assessor. Have made a note of this on the PDF at issue #211 so am closing this issue now.
