### ISSUE TITLE
Should "Internal" be referred to in text

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#216]
Btwn Fig3 and 4 it says
It’s not all bad news though. These heat losses are balanced by the heat generated by you and activities in your home, such as cooking. Heat is also provided by sunlight entering your home – this is known as passive solar gain.

Suggest it says 

It’s not all bad news though. These heat losses are balanced by the heat generated by you and activities in your home, such as cooking (Internal). Heat is also provided by sunlight entering your home – this is known as passive solar gain (Solar).

**Comment by marianneURBED** [comment]
Agree. Have edited text in PDF attached to issue 211. Closing this issue now.
