### ISSUE TITLE
Summary of measures descriptions to be removed and note about appendix added

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#224]
Associated works and Special considerations are not in these tables.

Add a note saying full descriptions are in Appendix A

Add descriptions of other headings to Appendix A including those above and Risks, Maintenance and maybe the how much.

**Comment by marianneURBED** [comment]
Have made note of this and how to tackle it in PDF, attached to issue 211. Closing this issue as think it's better to keep all report formatting/text stuff in one place.
