### ISSUE TITLE
Figure 10: Show energy cost as negative value for savings from renewable energy used on site. 

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#227]
This is NOT URGENT but it might help transparency if on the costs graph we were able to show the savings made by using directly generated electricity as a negative value on the graph - will help make clear the relative benefits of energy efficiency vs generation for different households (as it does with the primary energy chart). 

I realise this might mean we lose the error bars here - but I'm not convinced that they help much anyway for those not used to reading scientific graphs. 

If and when we do this, we'd need to update the associated text.

**Comment by cagabi** [comment]
I am doing this issue next.

I have realized about something wrong in the text. I am changing it:

> The fuel costs for your home will be affected by the level of insulation, the efficiency of services and lighting, the type of fuel used and the fuel tariff you have with your supplier. ~Figure 10 uses the standard fuel unit costs per kWh, which are based on national averages. These may differ from your actual costs – but means that the model is not affected by different energy deals and allows clearer comparison across time and between properties.~ If you provided bills, Figure 10 uses your actual fuel unit costs per kWh. If you didn't, Figure 10 uses standard fuel unit costs per kWh, which are based on national averages. This allows clearer comparison across scenarios but as it doesn't take into account energy deals the total costs have to be taken as an orientation.

Is that ok?

**Comment by cagabi** [comment]
I have added the negative bit for savings due to the onsite use of renewables.

I have also added something to this paragraph (what is in bold):

> We have shown the benefits of the estimated amount of energy you generate if it is used directly in your home – for example by running appliances whilst solar panels are generating electricity. We generally assume that you will use around 50% of the energy you generate on site, though can adjust this depending on how you use your home. This is an estimate, whether you are able to make use of this energy. You can maximise your savings from on-site generation like solar panels by using more of it directly yourself, but this may require a change in your household’s habits. **Figure 10 shows as negative values the estimated savings due to the onsite use of renewables.**

**Comment by marianneURBED** [comment]
Hello. Assigning myself to this to check. Have to do some other stuff today and tomorrow, so this will remind me to have a look next week. 
Thanks.

**Comment by marianneURBED** [comment]
Subsumed in report format review.
