### ISSUE TITLE
Review display of measures in report

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#228]
Hi

Wasn't sure where to put this but had an idea about another format that the info could be presented in which might avoid all the empty spaces and countless pages.
Will try to mock something up.

**Comment by gervasemangwana** [comment]
Ok it doesn't look pretty as I did it really quickly in Excel but I hope you get the idea. It would work even better for the full description I think. Just needs a bit of thinking about how to group the boxes with small data fields.
<img width="506" alt="screen shot 2017-01-16 at 11 42 05" src="https://cloud.githubusercontent.com/assets/16294193/21981756/e34abf7c-dbe0-11e6-82b7-73e5cee29267.png">

**Comment by marianneURBED** [comment]
I can definitely see how that would work better. 
It's a formatting issue, so will probably need input from Fieldwork. It's not urgent urgent, but would be good to see if something like this was possible for the release.

**Comment by cagabi** [comment]
I agree I like this more. I'd prefer to implement this myself as Fieldwork would be better at focusing just in the look of it.

I'll do this one soon

**Comment by cagabi** [comment]
I have implemented a similar table to the one proposed by Gervase. The list of measures still looks massive but at least it is not ugly.

I'll close thi issue now
