### ISSUE TITLE
Problem applying draught proofing measure

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#230]
In Vicars road scenario 1

When you press apply nothing happens (basic draught proofing)

**Comment by gervasemangwana** [comment]
Actually it doesn't do nothing. Behind the pop up the original boxes about construction/ floor sealing etc disappear and the q50 box come up but it's grey. If you close the pop up the q50 box stays but you can't put anything in it,

**Comment by cagabi** [comment]
Fixed
