### ISSUE TITLE
Link gas fires between Ventilation and Heating Systems Pages

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#238]
All in the g-sheet: 
 
- Loft hatches etc (LRA codes) - These are in the G-sheet but don't appear to be in either library. All types of loft hatch need to be in both libraries (existing and proposed measures). Need to be in same section/ accessible from windows and doors  - allowing you to add them and then state which wall they're in. 

 - SWIN_03: New measure related to existing internal solid wall insulation. This is a bit of a one-off - so may need a bit of finagling. 

 - Triple Glazing: both uPVC and timber versions need to be in baseline library (currently only in measures library).

 - Underfloor electric heating: Added to G-sheet as ROMHT11, needs to be added to baseline library (I doubt we'll ever suggest it as a measure).  

 - VS04 - dMEV needs to be in baseline library (currently only in measures library)

**Comment by marianneURBED** [comment]
Also - 

Need to add measure for 'remove gas fire'. Currently only have 'remove flueless gas fire' - but also need one for removing gas fire with flue.  - But this gets a bit complicated - need to also remember to remove it in the heating system page. Worth a chat about how best to do this.

**Comment by cagabi** [comment]
Hi, I have added all the items in first comment above.

But what about the walls in blue in the GSheet, it says to add them to library but they look like measures in which case they are missing some information.

About the "remove gas fire", that is bringing more questions to me. There is not a "gas fire" at all in the heating systems (with or without flue) and as you say, removing them from one place should remove them also from the other (the same applies when adding them) but this would be messy to implement.

**Comment by marianneURBED** [comment]
Hi, 

The walls in blue are definitely just things we'd potentially come across in an existing condition, not measures (there isn't enough insulation in them for us!). So please do just add them to the elements library. 

The gas fires are in the heating systems, under room heaters - listed as 'decorative effect' 'old' and 'new'.  You're right that the issue is that these haven't yet been tied up between the ventilation page and the effect they have there, and the heating page. 

There is a 'remove gas fire' on the ventilation page. We might for now just have to rely on assessors remembering to also remove the fire from the heating supply page if they remove it here, as we also don't want the same thing to appear twice in the measures list - but obviously would be good to better coordinate so we're not leaving something in that might result in human error. 

See what you reckon - would it be possible to automate it so if you removed the gas fire on one page, it also removed it on the other, but only one measure appeared in the report? 

Never damn simple is it?

M

**Comment by cagabi** [comment]
Hi,

I have added the walls in blue and the "remove gas fire" measure in Ventilation (Copied description and everything else from "Remove flueless gas fire", without the fuleless)

I'll keep this issue open as I am not doing anything yet about "linking" gas fires between Ventilation and Heating Systems. I think I know how to do it, but prefer to wait for you Marianne to set the priority of this issue and if it is _for release_

**Comment by cagabi** [comment]
Having a look now, I think the linking between Ventilation (Intentional vents and flues) and Heating systems applies not only to gas fires but also to the other ones: 
- IV_03: Flueless Gas fire: I understand this one is a _'decorative effect'_ room heater too
- IV_04: Wood Burning Stove with Flue: this would be _ROMHT9: Closed fires burning solid fuel_
- V_06: Other Gas appliance with Flue eg Old Boiler: this matches too many heating systems so cannot be linked
I am going to give it a go in my rain journey

**Comment by marianneURBED** [comment]
I think this needs to be sorted somehow, but not necessarily for the release. Will have more of a play with it and test on some current assessments, and have a think while doing this as to the smoothest way to do it. Needs to be assessor proof, and not too complex.

**Comment by cagabi** [comment]
Ok, I prefer this way, I'll remove the _For release_ tag now and set the priority to Medium?

**Comment by marianneURBED** [comment]
That's fine. Think high priority maybe rather than medium, but agree not needed for release. 

Ta

Mariannne

**Comment by marianneURBED** [comment]
Subsumed into separate future ventilation and heating pages review.
