### ISSUE TITLE
Householder questionnaire minor formatting/bugs

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#240]
Just a couple of things:

Assessment date:
To be consistent with how report date is shown in report, prompt should be DD-MM-YYYY

Q3b - Showers:
'Frequency of use' - should state 'per day'. 

Q6b - Question here and display in report not consistent. Q covers all lighting, in report refers only to 'daylighting'. Suggest in report change to 'Any problem locations for lighting?', omit daylighting. 

Q7a - When you refresh the page, or go away from the page and go back, this reverts to 'short term', after you've already changed to long term (done this on two different assessments now).

**Comment by cagabi** [comment]
Done
