### ISSUE TITLE
Ventilation Systems Guidance

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#243]
Need to provide some guidance (on the page?) on the meanings of the different types of ventilation system available.

**Comment by cagabi** [comment]
I have added a little question icon that you hover to show the info.

This is the text I have put, it's not very complete, do you think it is enough?

> SAP only considers 4 type of ventilation systems:
    - a: Balanced mechanical ventilation with heat recovery (MVHR)
    - b: Balanced mechanical ventilation without heat recovery (MV)
    - c: Whole house extract ventilation or positive input ventilation from outside
    - d: Natural ventilation or whole house positive input ventilation from loft
    
> But MHEP considers:
    - NV: natural ventilation (type 'd' in SAP)
    - IE: Intermittent Extract Ventilations (type 'd' in SAP)
    - PS: Passive Stack (type 'd' in SAP)
    - DEV: Decentralised continous mechanical extract ventilation (type 'c' in SAP)
    - MEV: Centralised Mechanical Continuous Extract Ventilation (type 'c' in SAP)
    - MV: Balanced Mechanical Ventilations without heat recovery (type 'b' in SAP)
    - MVHR: Balanced mechanical ventilation with heat recovery (type 'a' in SAP)

**Comment by marianneURBED** [comment]
To be made clear in library.
