### ISSUE TITLE
When typing directly into commentary box changes not saved

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#247]
If you're typing into the commentary box for a while, and not clicking anywhere else, changes aren't saved - potentially losing a lot of typing. It is possible to get round this if you know it's an issue - and the warning gives you the chance to copy text before it's lost if you think about it - but may cause frustration if you don't.

**Comment by cagabi** [comment]
I don't seem to have the problem, i type something and then reload the page and it's there

**Comment by marianneURBED** [comment]
this is the same as #311 , where most of discussion has happened, so closing this issue.
