### ISSUE TITLE
Economy 7 - Current Energy

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#25]
Unclear as to how economy 7 type tariffs can be taken into account here - need a second/ third mains electricity field so different tariff can be entered for day/night electricity. 

This still needs resolving - if you have already selected 'electricity - economy 7' you can't then select it again in order to add another rate.

**Comment by cagabi** [comment]
Trystan thinking of 'Economy 7' as night time electricity, and then use standard electricity as 'day' rate. Trystan to check this and label as 'Economy 7 (night)'.

**Comment by cagabi** [comment]
Carlos to simplify the Economy 7 section and only have *Economy 7 - day rate* and *Economy 7 - night rate*

  Helen and Carlos

**Comment by cagabi** [comment]
I have removed all the Economy-7 options and put  *day rate* and *night rate* ones.

I think it is simpler this way but now we are missing what is the use of the electricity (heating, water-heating, heat pump, electric-car), this means all the electricity use has to be inputted together. I think this is even simpler but wonder if it is what we want.

I'll leave this issue open for a bit.It'd be ideal if somebody gets back to me saying we are totally happy with this change. If not i'll send an email ;)

  Carlos

**Comment by helen-urbed** [comment]
Hi Carlos

The majority of people won’t have data about electricity use at such a fine grain - usually just their overall consumption from bills. So I personally don’t seem a problem with simplifying it. 

Thanks,
Helen

**Comment by marianneURBED** [comment]
Hello,

Agree with Helen, most people don't have enough information on their
electricity use to be able to attribute it to different purposes like that.
It would require each of those systems to be metered - highly unlikely. The
SAP model also doesn't/can't consider use by electric cars.

I know this is something that Trystan is looking at with the Open BEM
system - and we probably need to think about the relationship between the
assessment model and BEM, but I suspect that what will happen is the
outputs/ assumptions of the model will simply be compared with the outputs
of BEM - with adjustments having to be made for things like electric cars
etc that are less easy to accommodate in the model.

The assessment itself does model different electrical and energy uses - for
heating, fans and pumps etc - using slightly more standard categories, so
making comparisons across houses/projects a bit simpler.

So in summary - all fine, carry on!

Marianne

On 5 February 2016 at 09:14, helen-urbed <notifications@github.com> wrote:

> Hi Carlos
>
> The majority of people won’t have data about electricity use at such a
> fine grain - usually just their overall consumption from bills. So I
> personally don’t seem a problem with simplifying it.
>
> Thanks,
> Helen
>
>
> > On 4 Feb 2016, at 17:06, carlos Alonso Gabizón <notifications@github.com>
> wrote:
> >
> > I have removed all the Economy-7 options and put day rate and night rate
> ones.
> >
> > I think it is simpler this way but now we are missing what is the use of
> the electricity (heating, water-heating, heat pump, electric-car), this
> means all the electricity use has to be inputted together. I think this is
> even simpler but wonder if it is what we want.
> >
> > I'll leave this issue open for a bit.It'd be ideal if somebody gets back
> to me saying we are totally happy with this change. If not i'll send an
> email ;)
> >
> > Carlos
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/emoncms/MyHomeEnergyPlanner/issues/25#issuecomment-179948914
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emoncms/MyHomeEnergyPlanner/issues/25#issuecomment-180262437>
> .
>



-- 
*Marianne Heaslip*
Architect/Sustainability Consultant

*URBED (Urbanism Environment Design) Ltd *a. 5th Floor, 10 Little Lever
Street, Manchester, M1 1HR
t. +44 (0)161 200 5500
e. marianne@urbed.coop
w. www.urbed.coop

Fire destroys Toxteth Food Central - we need your help!
<http://us6.campaign-archive1.com/?u=47ce46e3ee9278b42c90d7d62&id=a927286bfc&e=e1c312350a>

URBED is 40 and hosting 7 unique events over 2015 to celebrate.
<http://urbed.coop/events>
Urban Design Group Awards 2015 - Winner in the Best Practice Category for
Trent Basin
Wolfson Economics Prize 2014 - Winner: Uxcester Garden City Proposal
Community Land Trust Network Awards 2012 - Awarded for excellence in
community engagement 2Up 2Down / Homebaked
URBED (Urbanism Environment & Design ) Ltd is a limited company with
co-operative rules registered in England and Wales NO. 5741006. Please
access the attached hyperlink for an important electronic communications
disclaimer: http://www.urbed.coop/emaildisclaimer
<http://www.urbed.coop/emaildisclaimer.>

**Comment by cagabi** [comment]
Thank for the commments. I'll close this issue now :)

  Carlos
