### ISSUE TITLE
Errors in SHD etc Bars

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#250]
See attached file

Have I missed something. Thought I'd filled whole assessment in,
<img width="468" alt="screen shot 2017-03-22 at 15 43 38" src="https://cloud.githubusercontent.com/assets/16294193/24206603/a18556b0-0f16-11e7-9da0-8b74dff309bd.png">

**Comment by cagabi** [comment]
Hi,

I obviously see the _\<sup\>_ stuff that should'n't be there.

But what do you mean with _Thought I'd filled whole assessment in_?

**Comment by gervasemangwana** [comment]
Just wondering if the reason the <sup> is due to assessor error as in bad data entry.

I’ll share the assessment with you. It happened on the last one I shared with you but that was a very partial one I did so assumed it was incomplete data entry.

	
Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by cagabi** [comment]
Oh my friend, don't blame yourself, it's me. I wanted the 2 to be small but those graphs don't allow it

**Comment by gervasemangwana** [comment]
You are a beautiful man


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by cagabi** [comment]
Ok, refresh the page and they are gone ;)

**Comment by gervasemangwana** [comment]
Hmmm

After refreshing a couple of times


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by cagabi** [comment]
Jajaja, not good understanding between us today. What do you mean with the _hmmm_?
Is it fixed? I cannot see the things anymore

**Comment by gervasemangwana** [comment]
Oh. I attached another picture. I refreshed but it still wasn't fixed. 

G

**Comment by cagabi** [comment]
Ok, I have reopened this issue for two reason

- Gervasse, I cannot see the errors any more, can you?
- @marianneURBED, I have just realized that the graph auto resizes the x axis depending on the number to represent. This was happening in the graphs in the report and you said that it's better to keep the size fix to make it easier to compare them with just one look. Do we want the same behavior here?

**Comment by gervasemangwana** [comment]
Hi Carlos

It’s still the same for me on Chrome

Hope you can see the attached 

I’ve shared the assessment 8 Royston Avenue with you


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by marianneURBED** [comment]
I'm not seeing them in firefox or chrome. 

I know, not helping.... ;-)

**Comment by cagabi** [comment]
I cannot see it either, so I think it is sorted and poor you, Gervaise, have the problem :p 

You may have to clear your cache: when you are in the page press Shift+F5, hopefully that will do a full reload of the page.

This is how it looks for me.

By the way, I think that for attaching images to your comments in the issue you need to use the web interface

![issue 250](https://cloud.githubusercontent.com/assets/7636325/24245708/db2c937e-0fbb-11e7-8239-9a771155b9cd.png)

**Comment by gervasemangwana** [comment]
Woop woop. Clearing cached data worked although not with shift F5. In chrome I selected clear browsing data then checked only clear cached data. 

Thanks superstar.


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk
