### ISSUE TITLE
DRD04 has wrong U-Value

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#251]
Double glazed 70 door U-Value 4.2 same as Single Glazed
Other Double glazed doors descending U-value as glazing increases e.g. 50-70 2.68 W/m2/K

**Comment by marianneURBED** [comment]
Sorry. Typo in the g-sheet. My fault. Should be 2.66 W/m2K

Now corrected in g-sheet. 

Marianne

**Comment by cagabi** [comment]
I have changed it in the default library and also updated the elements library of every user
