### ISSUE TITLE
Ability to annotate pictures, and also to add more pictures to Carbon Coop report

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#252]
It would be really useful to have the ability to add a line of annotation to the images in the gallery - so you know what they are/ what they're showing. 

Similarly, to have a section in the report where these annotated pictures could be added. 

Would be especially useful to explain complicated bits of geometry/small areas that can't be easily explained in the text, and also for adding thermal images where available.

Will require some thought on formatting in the report - whether it goes alongside the commentary, in the Appendix etc.

**Comment by cagabi** [comment]
I have added the annotation feature to the images.

About adding them to the report:
 - Tell me where you want them, in my opinion it makes sense as an anexe
 - Which images do we add? Simplest option is to add all of them but another option could be to have a check box next to every picture and when ticked that picture will go into the report
