### ISSUE TITLE
Changing number of bedrooms and number of storeys also changes the other in Questionnaire

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#253]
So if you put 2 storeys in it puts 2 beds in. If you then put 3 beds in it changes the storeys to 3 too! In Assessment 8 Royston. Chrome.

**Comment by marianneURBED** [comment]
Does this to me too in firefox and chrome.

**Comment by marianneURBED** [comment]
Actually, this is superfluous - if we're doing measured plans, and adding floors into 'basic dwelling data' we don't need the question on the number of storeys, so this can just be deleted. 

The question on the number of bedrooms is still useful, so should remain.

**Comment by cagabi** [comment]
I have removed the question about Number storeys. 
I guess the one about number of bedrooms is useful for the assessor but just in case I tell you  that it is not used for the calculations.
I'm closing this issue now but open it again if you need to talk about number of bedrooms
