### ISSUE TITLE
Creating and scenario after deleting another

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#254]
From email conversation with Gervase:

G:  I want to delete the scenario and start it again. BUT. If I do that and copy another from master or Scenario 1 will it be scenario 2 or will it now become scenario

C: I have just tried myself and creating a new scenario after deleting one, doesn't work, the new scenario is created but once you refresh the page, it's not there any more :( I'll open an issue now.  I'll do it in the way that the first vacant scenario is the one to create(in your case it would be scenario 1)

**Comment by gervasemangwana** [comment]
Hi Carlos

Thanks. 

Just to be clear it is scenario 2 I want to delete. But I think I understand that it will be the next vacant so that should work.

Best wishes

Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by cagabi** [comment]
Ah yes sorry, tha's my typo: you delete scenario 2 and have master,1 and 3 left. Creating a new one would be scenario 2.

I see the need of this for CarbonCoop report where each scenario is predefined

Gervase only one thing, I don't think I'll be able to do it today what about restoring the backup from 23rd March

**Comment by marianneURBED** [comment]
Just to say that I've done this - but only when deleting scenario 2 and 3 and redoing both. Didn't have a problem with disappearing scenarios - but then wasn't trying to 'insert' scenario 2 between 1 and 3, so could be the reason.

**Comment by cagabi** [comment]
yeah the problem is only when deleting and scenario which is in the middle

**Comment by cagabi** [comment]
Fixed
