### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#255]
From email conversation:

G: So I wanted to test this by making a copy of the assessment but I can’t seem to get that to work either. I clicked import/export in the original and copied everything there. Then went to the copy deleted everything in that field and pasted the data from original then clicked import and save. Nothing. Just a blank assessment with a single scenario. Tried refreshing. Nada. Nyett. Rien. Bu She (that’s mandarin). What Am I doing wrong?

J:  I'll let Carlos reply but when Marianne and I exported/imported, we had to create a new scenario for the assessment to become visible.

**Comment by marianneURBED** [comment]
Hi. 

From experience it takes a little time to work. After you click 'import and save' give it a few seconds, then go to the mater scenario and refresh the page. 

Just done this and it worked on an assessment, so hopefully should work.

**Comment by cagabi** [comment]
I have fixed the problem with the import. But better than that now you can download a file and keep it as a backup of the project, on the other side it is also possible to import a project from a file.

It has taken some time but it is a very neat solution, I like it.

**Comment by gervasemangwana** [comment]
I like it when you like it.


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk
