### ISSUE TITLE
Overview only shows Master data when in Household questionnaire.

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#256]
Not sure this as an "issue". It just means that when you want to compare figures for the scenarios you have to go to fabric or another option in the scenario.

**Comment by marianneURBED** [comment]
You're right that it would be helpful to be able to see these as you write. As a work-around, you could open the scenarios in a separate tab/window? Though this may lead to confusion....

Setting as low priority for now - would be a nice usability fix if you could see different overviews, but prob not a deal breaker right now.

**Comment by cagabi** [comment]
I think the "coherent" thing to do would be to not show the Overview graph when you are in any of those Project views as they are common pages to all the scenarios and showing the overview may be confusing when you don't know to which scenario it belongs to.

In terms of comparing figures, we could add to the list under Project a "Scenarios overview" that would show in one page the graphs for all the scenarios

**Comment by cagabi** [comment]
I have added the overviews for all the scenarios to the Commentary page. They are below the commentary.
I first added them with the same size than the overview on the master scenario (top) but looked very ugly so now they are half the size which seems to be quite small but enough in my screen. Can you have a look and tell me if you like it, if not we can also try with the whole size and you decide

**Comment by marianneURBED** [comment]
Looks fine. Useful addition.
