### ISSUE TITLE
Ability to 'revert to master/other scenario' on an element after applying a measure

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#259]
It would be helpful within any scenario to be able to 'revert to master/ other scenario' on a particular element would be helpful for those times when you apply a measure, go away and do something else, then come back to it and realise that's not what you actually want. 

At the moment, the only way to deal with this would be to delete a scenario and start again - which is much quicker than it used to be, but is annoying as you have to redo things that were otherwise fine.

**Comment by marianneURBED** [comment]
After speaking to Andrew at CAfS the other day, moving this up the priorities list.

**Comment by cagabi** [comment]
Can this be linked to #302

**Comment by cagabi** [comment]
Done :)

**Comment by marianneURBED** [comment]
Brill!
