### ISSUE TITLE
Figure 3: Carbon Coop Report - Rename 'Infiltration' as 'Draughts (Infiltration)' and 'Ventilation' as 'Planned Ventilation'.

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#260]
Hoping this is relatively simple/quick. 

It's definitely useful to keep the two elements described separate in Figure 3 - but 'infiltration' is a term most people probably won't be very familiar with. 

Renaming as 'draughts' should help make this a but more understandable. And calling ventilation 'planned ventilation' makes things clearer. 

Thanks!

**Comment by marianneURBED** [comment]
While we're at it, 'Windows' here should be renamed 'Windows and Doors'.

**Comment by cagabi** [comment]
Done
