### ISSUE TITLE
User access to myhome.carbon.coop

### ISSUE THREAD

**Issue by lowwintersun** [emoncms/MyHomeEnergyPlanner#262]
* Set up moderation for myhome.carbon.coop implementation so that we can control who has access. (Makes less sense for it to be open access now that OEM have a version running). 

* Review user privileges with @marianneURBED and @helen-urbed - I think, ideally, for householders who have had an assessment, there would be a locked version of the URBED assessment but they would also have the ability to create new scenarios. 

But needs thinking about!

**Comment by cagabi** [comment]
As a starting point I can easily remove the option to register from the login page.

I understand what you say about the _ locked version of the URBED assessment_ as the user wouldn't have the option to even unlock the master and 3 scenarios. Implementing this would be a major thing.

I am going to look at #255 issue. I think that just in case everytime an assessment is completely finished, the assessor should export it and save it as a backup

**Comment by lowwintersun** [comment]
Yes, I would remove that register from the login page - but please send us the login url so we can direct people who need it. 

I've noticed that you can add multiple user accounts for the same email - all that is needed is a unique user name.

**Comment by marianneURBED** [comment]
This is linked to the libraries issue, but also to the ability to generate branded reports. Sending it up the priorities ranking, as I think this is important. 

Only trained assessors should have access to the Carbon Coop library - this is being dealt with as I control permissions for this, and am in the process of editing the standard libraries that each user gets when they sign up for an account (#331). 

Equally importantly, we need to control access to the Carbon Coop and CAfS format reports, so untrained people can't generate reports with our logos on them (I'm all for sharing as much as possible, but am nervous about amateurs adding measures without fully understanding them, and also the risks of version control if anyone can generate something with a Carbon Coop logo on it). I thought we'd done something on this - but creating a new account to edit the standard libraries it seems that's not the case. 

Suggest the permissions should be something like:
- Trained assessors - full access to see and generate reports for the organisation they are a member of (at the moment just CAfS and Carbon Coop) and access to Carbon Coop Libraries. 

- Carbon Coop Householders/ people who have had assessments: Ability to see locked versions of reports/scenarios and not unlock them. Ability to generate new scenarios? (Though to my knowledge only a couple of people have done this so far - all EcoHome Labbers). Reporting on this needs to be clear that it is self-generated, and not part of the main report. Access to libraries here more questionable? Not sure how you'd manage libraries? Could provide access to basic library only (which I'm editing to be as 'white label' as possible), but this may cause confusions and conflicts. 

 - Others/ general public: Ability to log in and generate basic report only (like old MHEP report) with basic library. 

As a temporary measure, til we work this out, could we restrict the ability to register for a new account? The level of access we're providing to the world at large at the moment is arguably quite risky.

**Comment by cagabi** [comment]
Ups, I added the "register" option again for something i had to do for CarbonCoop Dec social. I have removed it now

**Comment by cagabi** [comment]
Hi,
I have implemented 2 of the 3 cases that Marianne summarises:

- Trained assessors - full access to see and generate reports for the organisation they are a member of (at the moment just CAfS and Carbon Coop) and access to Carbon Coop Libraries (this was already working as the library has to be shared with the assessor).
- Others/ general public: Ability to log in and generate basic report only (like old MHEP report) with basic library.

So now if I log in I can only see Carbon Coop report, **@marianneURBED can you please add me to the CFS or ganization?**

I am leaving this issue open because I still need to implement householder access to the locked assessment, which TBH I haev no idea how can be implemented without making a big mess

**Comment by marianneURBED** [comment]
This all changing with new framework.
