### ISSUE TITLE
Rearranging Project menu

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#263]
Just to let you know, I have split the Project menu into "Project input" and "Other", it was botherinng me very much having everything mixed together. If you can think better heading for them let me know

**Comment by marianneURBED** [comment]
That's fine. Could also be called 'reporting and libraries' but I'm not too fussed tbh.

**Comment by cagabi** [comment]
I leave it as it is now. I don't like the  'reporting and libraries' as we also have the "import/export"
