### ISSUE TITLE
PV Apply measure not working in Chrome

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#264]
I'm tending to use Chrome at the moment because I know I need to print it in there (so not really necessary). 
It works great in Firefox where I applied it and it seems to work ok in Safari.

**Comment by cagabi** [comment]
I have no problem doing it in Chrome, can you try with another assessment, please

**Comment by marianneURBED** [comment]
Just checked - I'm not having this problem either. 

Fluke?

**Comment by cagabi** [comment]
Gervase, can you please check this is still happening and if not close the issue. Thanks

**Comment by gervasemangwana** [comment]
Yup working now

Thanks


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk
