### ISSUE TITLE
SAP occupancy number a bit too accurate in Report

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#268]
I think 2 or 3 significant figures will do. 17 seems a little excessive. Maybe it's just me.
<img width="543" alt="screen shot 2017-04-10 at 09 46 29" src="https://cloud.githubusercontent.com/assets/16294193/24853395/d16ebf68-1dd2-11e7-98bb-be1ea528f21d.png">

**Comment by marianneURBED** [comment]
Override by inputting actual occupancy figure in 'basic dwelling data' page.

**Comment by cagabi** [comment]
Done. For the report and so quick, I though it would be useful.
