### ISSUE TITLE
Change Number in Brackets on each scenario from SAP to Carbon

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#271]
Hello, 
Given we're not actually that interested in SAP, can we change the number given in brackets in the header of each scenarios from the SAP number to the CO2 emissions rate? Or even space heating and carbon? Will be more useful, as these are the numbers we're actually worried about.

**Comment by cagabi** [comment]
I have changed it to CO2 rate, adding the space heating was a bit too crowded in my opinion, but can do it if you want.
