### ISSUE TITLE
Number incrementation erratic behaviour

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#274]
Changing numbers like thermal bridging and PV fraction with the incrementor doesn't always work. Sometime it reverts back to some other number. This happened in Chrome I think.

**Comment by cagabi** [comment]
The problem with the PV fraction was a bug only replicable in scenarios where you haven't ticked the "use calculator", after that it was working ok. The bug wouldn't allow you to manually set the  annual generation reverting it always to 0. It's fixed now

With the thermal bridging, I think it is a visual effect as it displays 2 decimal numbers except for the last number is a zero (it goes from 0.29 to 0.3 and then 0.31)
