### ISSUE TITLE
Infinity% for PV

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#275]
Since going from no generation (zero) to some the improvement % is infinity.

Also do we want to do something about generation income being 0

**Comment by cagabi** [comment]
I have done replaced the "infinity"  with "N/A"
About the generation, I guess you dind't put anything in "Feed in tariff" input. ANyway there is another issue   (#35) where I have to deal with FIT

**Comment by marianneURBED** [comment]
Hi. As per comment on #35 - good that this is sorted, but for assessments at least, we probably shouldn't enter anything for generation or export tariff - as it's so liable to change between people getting assessments done and them commissioning works. Different argument if you're using the tool for another purpose.
