### ISSUE TITLE
Any interest in including batteries?

### ISSUE THREAD

**Issue by beaylott** [emoncms/MyHomeEnergyPlanner#279]
It is outside the scope of SAP at the moment, but I have been thinking a lot about making an online tool which will give you an idea about costs/effectiveness of installing a battery alongside a solar system. Instead (or in addition to) making a whole separate website we could look at adding something to my home energy planner.

**Comment by gervasemangwana** [comment]
Hi Ben

As it happens I could do with making use of such a tool this very week. Or at least an idea about a good way to calculate. At the moment I’m not sure I can see the value in adding one in that it won’t pay back.

Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by cagabi** [comment]
I think this is a great idea. 

How it works now is that in Fuel Requirements we have the Annual Generation (kWh). This comes from the inputs in the Generation view. I guess we could add the batteries to the PV calculator that is already there. Although it would be great to make it possible to add the batteries to a wind system too.

When thinking in the U-value calculator for floors at #246, my idea was to make a stand alone open source script that does all the calculations (maybe also add a simple user interface as a _how to use_ example). Then use the script as a library in MHEP. I think we could do the same for your batteries idea.

**Comment by marianneURBED** [comment]
Yep, happy for battery calcs to be included - if we can be reasonably sure about the modelled outcomes. I can see it will be something that people ask about more and more. 

Probably not a massively high priority right now, vs getting some other bits of reporting etc sorted so the tool functions properly for what it can do now, but definitely something to include in future development.

**Comment by beaylott** [comment]
@gervasemangwana : at the moment I would be surprised if you come across a case where it was economical!  

@marianneURBED : the method is the question... you have the monthly average production ...but for the simplest model you really need a monthly self-consumption figure as well . That gives you a rough daily consumption profile so you can see what balance goes to the battery and grid depending on capacity and therefore how it effects overall self-consumption and then finally the carbon emissions due to lower grid use (ignoring embedded emissions etc.). 

As to priorities, i wasnt proposing any of you do this, I would be happy to tackle it in my own time.

@cagabi: for wind you can not really do a simple model like the above - you have to use a detailed time step calculation and do a sort of markov simulation to determine the most probable result under different initial conditions. Multi source / load problems are complex optimisation problems and dont really lend themselves to parametric models. You would use something like the software I used for my thesis (could do with an open source version of that!).

**Comment by beaylott** [comment]
@gervasemangwana if you have an idea of consumption profile and array size you can estimate the monthly averaged daily amount stored , then you can either calculate the increase in self-consumption (and therefore reduction in carbon emissions from reduction in grid use) or a cost of energy for the electricity from the battery given the annualised NPV of the system. Thats the simplest way to do it.

**Comment by lowwintersun** [comment]
@beaylott I like the fact that the model could run off something as simple as a self consumption %. I think this is something that could be either estimated or monitored and so is a good aid to decision making. 

It would also be an excellent resource for Carbon Co-op members. 

What kind of timescale were you looking at - is this a long term plan or something that we could see sooner?

**Comment by marianneURBED** [comment]
Subsumed in planned SAP10 related updates in 2020.
