### ISSUE TITLE
100% green electricity tariff - Current energy

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#28]
Not clear where primary energy factors of 2.4 and 1.3 are from - most up to date factors are 1.22 for gas and 3.07 for electricity. See table 12 of SAP 2012 (this relates to issue 43 above about ensuring correct version of SAP is being used).

The text also needs to be clearer. By selecting this option it somewhat defeats 'fabric first' objectives (and means someone can go zero-carbon by switching to 'Good Energy' but doing nothing else, which is a bit of a nonsense). Householders need to be aware of this.

**Comment by cagabi** [comment]
Energy factors sorted. Nothing done about Green Electricity tariff

**Comment by cagabi** [comment]
Helen a Marianne to send new text for the green box

  Helen and Carlos

**Comment by marianneURBED** [comment]
This feature has been removed - repeat after me  - "There is no such thing as zero carbon electricity from the mains grid" (at least, not yet!). 

Closing this issue.
