### ISSUE TITLE
Add guidance and definitions - Heating page

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#280]
Hi, 
A few things came up from the work with CAfS in the last couple of weeks, highlighting areas where we need to add explanatory notes (under ? signs as before) to aid understanding:

- Living area: Add note - "The 'Living Area' is the floor area of the lounge or living room or largest reception room in the home, including any rooms not separated from this by doors. It does not, however, extend over more than one storey, even when stairs enter the living area directly"

- Heating off for whole summer: Add note stating what months we have assumed for "summer". E.g. "Summer is defined as May to August, inclusive". (This is important for somewhere like Carlisle, where "summer" lasts for approximately 2 weeks in July ;-) ). 

- Space heating system fraction: Add note "This defines what proportion of the space heating or water heating for a home is provided by the system listed. For example, a standard assumption might be that a gas boiler provides 90% (0.9) of the space heating, and an open fire or room stove provides 10% (0.1). However, this can be adjusted using assessors informed judgement as required - and as many systems as are present can be included. If there are two main heating systems identified, the proportion of heat provided by each system should be taken as the relative heated floor area served by each system"

- Main heating system: Add note on identifying main vs secondary systems: "The main heating system is that which heats the largest proportion of the dwelling, and often provided hot water as well as space heating. If there is more than one main heating system identified, main system 1 always heats the living space. Secondary heating systems are room heaters - such as open fires or wood-stoves. If portable room heaters are used, they should be included in the calculations (note this is a deviation from standard SAP - ref p.40 SAP 9.92)" 

- Space heating controls: Add note  - "refer to Table 4e, p.210 SAP 9.92". 

- Responsiveness: Add note - "refer to Table 4d, p.209 SAP 9.92". 

- Define WWHRS: On headings for hot water storage, currently asks "Contains dedicated solar storage or WWHRS volume?" - add a note somewhere that explains that WWHRS stands for 'Waste Water Heat Recovery'.

**Comment by cagabi** [comment]
One day this week I'll go throw all the "guidance issues", They are all easy to do

**Comment by cagabi** [comment]
DOne
