### ISSUE TITLE
Libraries Management

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#281]
So we had a conversation ages ago on the management of Libraries, and I've finally had time to think about it. 

Essentially, I think there should be three 'levels' of library - illustrated in attached diagram. [EPSON032.PDF](https://github.com/emoncms/MyHomeEnergyPlanner/files/951977/EPSON032.PDF)

**1. User's own library:** That they can do whatever they want with - add to and edit etc. Not shared. Not integrated with Carbon Coop reporting. 
**2. 'Open' MHEP Library:** With limited generic data based on rdSAP or similar, controlled by the opensource community running OEM.  Shared with all MHEP users. Not integrated with Carbon Coop reporting. 
**3. Carbon Coop Library:** A closed library, shared only within Carbon Coop, containing detailed information, fully integrated with Carbon Coop reporting. Closed nature important not so much for intellectual property proptection, but because the more detailed info available could do harm if wrongly applied - so needs to be only accessed and used by 'approved' and trained people. This needs to be easily editable by one or two approved 'librarians' - so we can update prices and technical details in a responsive fashion - but then shared with all assessors. From conversations with Andrew at CAfS, suggest we share a single library with them, and just add to it as new circumstances are discovered - they'll have more stone walls than us, but we do come across them from time to time, so makes sense for us all to share the base data. NEF may simply want to join this too - but we'd need to check with them. 

Carlos - I know we might need to talk this through some more, so maybe mull it over and then give me a call later in the week. 

A second issue, which I know I've mentioned before - I'm increasingly convinced that the split between 'elements' and 'measures' in the libraries is a false one. In assessments we're often coming across existing 'elements' that have so far only been listed as 'measures' - as people have already done some work to their homes. It's really frustrating to know when you're building a 'baseline' scenario that what you need is in the 'measures' library - but you can't get to it. I'd like to propose that we merge the 'elements' and 'measures' libraries, to allow maximum flexibility - so that 'measures' are accessible from the baseline and 'elements' are accessible from scenarios. Otherwise we're restricting and second-guess things in a way that has already proved to be pretty annoying. This is true in both 'fabric' and heating systems. 

Be good to know what others think.

**Comment by gervasemangwana** [comment]
First thing that comes to mind about merging elements and measures is that elements do not have all the text associated with measures. So hella work there. But yes it is frustrating and would be good to just choose what you need. 

Does an element aver need to be measure though? 

So maybe it’s not so hard.


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by marianneURBED** [comment]
Right. After playing around with the libraries have realised I can edit a library and share it with chosen assessors (sorry Carlos, you probably told me this before!) - so will do this as part of libraries review I'm doing now to create the Carbon Coop library. 

@cagabi  - the thing you'll need to do is amend the 'standard library' that appears when you create an account, so that it's the open MHEP one, rather than the closed 'Carbon Coop' one. Will make a start on creating the MHEP one so you can do this too. 

Thanks.
