### ISSUE TITLE
Image Upload problems

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#282]
Hi Carlos,  

Both myself and Andrew couldn't upload a jpeg image in Chrome. Tried in firefox and it worked. Strange because it was the photo that didn't work - but Andrew had been able to upload the image of the house plans earlier. 

Assessment 'HEA020Tuffin' - shared with you now.

**Comment by cagabi** [comment]
Can you please upload the picture here?

**Comment by marianneURBED** [comment]
Yep. Here you go. 

![house image](https://cloud.githubusercontent.com/assets/16305707/25346085/8cc53846-290e-11e7-863b-693a0ffecab5.jpg)

**Comment by cagabi** [comment]
Sorry, better email it to me, i wonder if the problem has to do with the name

**Comment by marianneURBED** [comment]
Still having this issue with different assessments and photos. Can upload image in firefox but not chrome. Takes a few goes before it accepts the * has been clicked to select it as the image for the front of the report.

**Comment by cagabi** [comment]
Update: This is very weird, I can randomly replicate the issue. I have tried to upload this very same image in several test assessments with Chrome and sometimes it works and some others it doesn't :( Also I haven't been found very much searching.

**Comment by gervasemangwana** [comment]
I am unable to upload images into the 10 manor hill rd assessment in chrome, safari or firefox. Although it behaves differently in each. Definitely less than 1mb files.

**Comment by cagabi** [comment]
Gervase was still having problems to upload some plans pictures.... So I tried to upload them myself and it was not working. Then I have done some changes in the code that seem to do the job and I have been able to upload the pictures, good.

What I don't know is if this is the random behavior of the upload functionality (sometimes working sometimes not) or if it is totally fixed.

Keep me informed with your uploads please.

**Comment by helen-urbed** [comment]
Hi Carlos - just to update you on this, I was able to upload images in firefox, but not chrome. 
I could only select the featured image for the report once they appeared in chrome (assessment is Roussel, Mona Cottage, 2 Stockton Rd)

**Comment by cagabi** [comment]
Ohhhhh, the randomnesss of this issue. I don't know what to do with it tbh :(

**Comment by marianneURBED** [comment]
Happened again today - image could be uploaded in firefox, but not in chrome.

**Comment by marianneURBED** [comment]
Hello, having these issues again - on an assessment I'me doing for issue before xmas. Get the following message on the image gallery page: "There has been a problem creating the directory for these images, check permissions!"
Am able to select the image I want from the browser, it looks like it does something, but then get that message.

**Comment by marianneURBED** [comment]
Same issue in chrome and firefox.

**Comment by cagabi** [comment]
Hi, the problem is different than before. I recently did some permissions changing in the server and didn't realise I would break the image upload.
I have done a quick fix now but need to do it properly. Let me know when you have done the upload so I don't interfere.

**Comment by marianneURBED** [comment]
Ok - report done and issued. Do your worst!

**Comment by cagabi** [comment]
jeje, I will

**Comment by helen-urbed** [comment]
Hi Carlos - I'm still having trouble with this. Can't get any images to appear on my latest assessment (CC21_HT_M6 8JG), in either Firefox or Chrome. When I try again in Firefox I get a message saying 'file already exists' but nothing visible.

**Comment by cagabi** [comment]
I have checked in the server and there isn't any image for it. Also I have been able to upload a random image. Can you please send me the picture you are trying to upload.

**Comment by marianneURBED** [comment]
Superseded in new platform - hopefully bugs won't replicate!
