### ISSUE TITLE
Change element name

### ISSUE THREAD

**Issue by ajnorthcott** [emoncms/MyHomeEnergyPlanner#287]
It would be very handy to be able to reselect an element type.
Eg change from CWF_2 to CWF_03 without having to delete and re-enter the dimensions.

Andrew

**Comment by cagabi** [comment]
Right now when "editting the element in the master scenario it's not possible to change the element, only the name and source

**Comment by marianneURBED** [comment]
this is the same as issue #342, so closing here.
