### ISSUE TITLE
Layout - column headings in fabric section

### ISSUE THREAD

**Issue by ajnorthcott** [emoncms/MyHomeEnergyPlanner#289]
It could be better, and reduce error, if the headings are repeated for each subsection of data input.
So under Fabric input, under 'Walls' the following headings appear: 

Element	Label/Location etc etc    Length (m) Height (m) etc   etc

This heading could be repeated under Party Walls, Roofs and Lofts etc for each subsection.
At present I have to scroll way to the top to see what to put in each box.

Andrew

**Comment by cagabi** [comment]
Done
