### ISSUE TITLE
Total energy income - Energy system

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#29]
Need to be clear on exactly what this is. Given current climate, and fact FIT rates are soon to be demolished, may be best to just omit any reference and base calculations solely on energy used on site vs imported from grid. (Another loose apostophe here too!)

**Comment by cagabi** [comment]
I think i disagree on this one but obviously it is up to you.

Shouldn't we keep the FITs until they are totally gone??

  Carlos

**Comment by cagabi** [comment]
Action for Helen, Marianne and Jonathan to discuss ;)

  Helen and Carlos

**Comment by cagabi** [comment]
We want to remove the FIT Total Energy Income element from the calculator and report
We’d like to direct people here, in the report: http://www.pvfitcalculator.energysavingtrust.org.uk/

  Jonathan, Helen and Marianne

**Comment by marianneURBED** [comment]
Ok - thinking this through again, we should leave it in as an option to fill out, but it's not something we'll use in formal Carbon Coop assessments for now, as it's so likely that the rates will change/drop between us doing an assessment and people actually getting an install. 

At the moment though there is only one 'FIT' rate to enter on the 'Generation' Page- when actually need to calculate generation and export tariffs separately. This is then really a duplication of issue #35 labelling of generation and export tariffs - so marking this as duplicate and closing.
