### ISSUE TITLE
Correction to Carbon Coop Appliances Calculation

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#290]
The calculation for 'Small Consumer Electronics' has gone awry, after a conversion from watts to kW in the normal demand. 

A decimal point has been shifted, so that we're predicting only 0.13kWh of use for this - which is a bit hopeful. 

Please amend the frequency to 550 (from .55) to account for this for this item. 

Thanks,

Marianne

**Comment by marianneURBED** [comment]
Have amended this in Carbon Coop Library - please make sure you're using the right library everyone!

**Comment by cagabi** [comment]
I have changed it in the default library (the hard coded one used to create new ones when a new user registers). 

Also just in case anybody used a different library than the CarbonCoop one, I have run a script that has modified the "Appliances and Cooking" library of every user. So no need to worry.

**Comment by gervasemangwana** [comment]
Oh good. I was worried you know. A bit.

Thanks


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk
