### ISSUE TITLE
Householder Questionnaire - Heating Periods

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#292]
Entering a third heating period in the householder questionnaire seems to do something strange to the calcs - reduces space heating demand and makes the 'hours heating off' nonsense

Error in calculation somewhere here.

**Comment by cagabi** [comment]
Fixed it, 

Goodness the algorithm to calculate the periods of _heating off_ from the periods of _heating on_ is mental. 

To make things clearer for the assessors so they know things are correct I have added a line undeneath the "on" periods telling the amount of hours of heating off
