### ISSUE TITLE
Householder Questionnaire Updates

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#294]
Hello, 

After watching Andrew fill out the householder questionnaire the other week, I've noted some changes to it. 

These are mostly about format and adding a bit of context to the questions to make it easier to use. 

All noted on the attached PDF. Let me know if any questions. 

M 
[20170501_Householder Questionnaire Amendments.pdf](https://github.com/emoncms/MyHomeEnergyPlanner/files/968244/20170501_Householder.Questionnaire.Amendments.pdf)

**Comment by gervasemangwana** [comment]
Hi Marianne

Is he filling it out directly into the tool?


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by marianneURBED** [comment]
Yes - though I think it would be good to have the option to do both fill it in direct, and put into a form that can then be transferred/imported. Amendments here mostly about text updates and formatting. 

M

**Comment by marianneURBED** [comment]
Marianne to check changes in upcoming assessment and let Carlos know re edits.

**Comment by marianneURBED** [comment]
Hi Carlos, 
I think if you can hang fire for now, and I'll check it in the next week or so. 
I think there are some changes that need to be made that are linked to the hot water page that need a bit of thought.

**Comment by marianneURBED** [comment]
I'm working through some additional changes on this now.
