### ISSUE TITLE
Report Figure 11 - Updates

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#295]
The format of Figure 11 in the Carbon Coop report needs to be updated, now that we've incorporated the ability to alter heating periods and thermostat settings. 

This needs some thought - probably for me (and Gervase and Andrew) to ponder on.

**Comment by marianneURBED** [comment]
Having thought about this, I think the best thing to do is to simply omit it. 

The line on Living Room thermostat temperature is redundant, as this is something we can now adjust in the model. Though it does raise questions on how we deal with someone who has the thermostat on an unhealthily low setting, I think this can be covered in how we model scenarios (never setting thermostat at less than 18oC) and in updated text for the Space Heating Demand section (and possibly by introducing a separate graph for Fabric Energy Efficiency, that makes standard assumptions for space heating controls and settings, but that's a bigger task). 

The appliances calculation is now irrelevant, as we use the figures generated by the Carbon Coop appliance calculator in the model, rather than SAP. 

The number of habitable rooms heated/unheated is hard to ascertain in a survey - so again, can just add something on this to the text for the space heating demand graph, where it's most directly relevant and most likely to be read and understood.

**Comment by marianneURBED** [comment]
Carlos, are you ok to just omit this section and then re-number the figures that follow on from it?

**Comment by cagabi** [comment]
Done
