### ISSUE TITLE
PV not counted in calculation unless 'generation' ticked in main menu

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#297]
This could be a bit confusing. You can add PVs as part of a scenario, but if you don't tick 'generation' in the main menu on the left hand side, it makes no difference to the calculations. This is a bit confusing and could easily be missed.

**Comment by marianneURBED** [comment]
Suggest that instead 'generation' is automatically included if present.

**Comment by marianneURBED** [comment]
This tick box is a bit 'sticky' generally too. Sometimes, when you've ticked it, it doesn't show as being ticked until you refresh the page - which can lead to confusion and second guessing when you look at the carbon targets.

**Comment by cagabi** [comment]
This is done.

I have removed the tick box and moved the Generation menu item outside the _Extended input_.
