### ISSUE TITLE
Warning to indicate that master scenario has changed - and ability to 'revert' to master/other scenario

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#302]
From an email conversation with Dom,

> Ah, I can see what is happening with scenarios; if you update the Master but have existing scenarios then the scenarios themselves do not change. In other words the scenarios carry over the “old information” from the original master rather than the modified master – I hope that makes sense.

So it is probably best in those instances to delete the scenarios and start again (as you suggested). Maybe it could be possible to add a flag or warning indicating the master has changed?

Best regards

Dom

**Comment by gervasemangwana** [comment]
Agreed

**Comment by marianneURBED** [comment]
What's got lost in the linking here is that we still can only revert to the master - we can't choose to revert to scenario 1 from scenario 2 for example. 

Have also discovered that it is not possible to revert to the master (or tell a measure has been applied) if the 'bulk measure' tool is used. This seems to have led to some confusion and bugginess. For example, after bulk measures has been applied, measures were applied again - leading to them appearing twice in the report. See id=183.

Would be very useful to sort these to avoid future errors, so bumping this up the priorities list.

**Comment by cagabi** [comment]
Hi,

I have:

-  Added the "revert to other scenario" functionality
- Fixed bug of having more than one measure applied to the same element. So now if you apply a measure (as a bulk measure or as single measure) to an element we first check if a measure was previously applied to it (bulk or single). If so then we delete the previous measure and apply the new one.

For the assessment 183, I think the best option is to delete the scenarios and redo them. If you don't want to do so (so you can keep other measures aprt of the fabric ones), you will have to revert every single fabric measure to its original and then reapply them.

**Comment by cagabi** [comment]
I have added the warning to show that the original scenario (the one copied from when creating a new scenario) has changed. I was not sure what was the best way to display the warning, now it's just a * next to the _(From master)_, when you hover with the mouse it displays a message saying that the original one has changed.

This functionality is only for scenarios created from now. This can be a bit confusing in existing assessments :(

I'll close this issue now, but feel free to reopen it if anybody can think of a better way of displaying the warning
