### ISSUE TITLE
Carbon Coop Report Figure 4 - last bar of graph skinny/ falling off page?

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#305]
The bar for scenario 3 in figure 4 in the report is displaying differently to the others - much skinnier? 
<img width="1440" alt="screen shot 2017-06-16 at 14 08 36" src="https://user-images.githubusercontent.com/16305707/27227909-663e681a-529d-11e7-9c6d-8a32ccda5ac4.png">

**Comment by cagabi** [comment]
Fixed
