### ISSUE TITLE
Bars - Current Energy

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#31]
The bars at the bottom need to be clearly labelled so that people can understand the difference between the set of information at the top of the page and the set below their actual usage figures.

**Comment by marianneURBED** [comment]
They also need to be updated so they're using the same terminology and targets as the main bar chart used as the header.

**Comment by marianneURBED** [comment]
The targets on bar charts for current energy need to be updated so UK average figures for CO2 and Primary Energy match the ones above in the main header (the ones in the main header are correct).

**Comment by cagabi** [comment]
I have updated the target bars.
Also added the following text to make it clearer:

> The figures shown below are the totals for your actual energy use. If the inputted data is accurate, these figures represent real values.
> The figures shown in the overview above are the result of running your house through the model. According to the characteristics of the building, your target temperature, your type of fuel, etc. the model calculates the theoretical amount of energy you need to run your house.
> Comparing your Current Energy figures against the model ones can give an idea of how well the model works.

Marianne if you are happy with the text,please close the issue

**Comment by marianneURBED** [comment]
I think it’s good – I would just amend the last line to:

“ Comparing your Current Energy Figures against the model ones can give an idea of how well the model represents your specific situation”.

**Comment by cagabi** [comment]
Done
