### ISSUE TITLE
Adjustment to costs for small area measures - fabric measures only

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#313]
When applying a measure to a very small area, because costs are worked out per square meter, can give a skewed impression of total costs. 

Can cost on each per sq m or per ln m etc measure be adjusted so that rather than calculation being:

total cost = area x unit cost

is instead

total cost = minimum cost + (area x unit cost)

Could for now put a minimum cost of £100 for each measure (the 'get out of bed' fee). 

Thanks, 

Marianne

**Comment by cagabi** [comment]
This is doable but quite complicated:
- To do it properly requires to add a new field to all the elements in the libraries (massive) and then change the calculation of total cost (quick)
- To do it as proposed (just to add to the calculation) would not be clear in the report as we don't show the minimum cost so it may look like the calculation is wrong.

I'll do the proper solution then, hopefully soon.

**Comment by cagabi** [comment]
Done.
Beware that the total cost calculation of a measure will only take into account the minimum cost for Measures you apply from now
