### ISSUE TITLE
In report, explain treatment of existing PVs and FITs

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#316]
ref #304

**Comment by marianneURBED** [comment]
_New Text for Figure 6_: Figure 6 shows the total amount of energy used in your home, in kilowatt-hours per year and by fuel type..... works. **If you have existing on site electricity generation equipment, such as solar panels, any electricity you generate and then use on site will not be shown on your electricity bills. This because you will not have paid to import this electricity from the national grid. This can be misleading, as your bill data can then suggest that your electricity usage is lower than reality. Where import, export and generation of electricity are not metered in a way that allows us to see this separately, which is in most houses, we therefore have to make some assumptions to be able give a more accurate representation of energy use in your home. We assume that you use a certain proportion of the electricity you generate on site - usually around 50%, though we can adjust this dependent on how you occupy your home. We then add this to the figure given in your bills for electricity usage to give a more accurate picture of electricity demand.**

**Comment by marianneURBED** [comment]
Note - New text in bold for identification purposes, doesn't have to be in bold on the report. 

Also - please can we change the heading here from "1.3 Energy Demand" to "1.3 Energy Usage"

Thanks.

**Comment by marianneURBED** [comment]
Carlos - I've sent you an email with the other text changes. for Figures 6,7,8,9 and 10. 

Thanks.

**Comment by cagabi** [comment]
Hi Marianne,

In figure 6 do you want to keep this text?

_Your actual energy use is affected by factors such as the external climate and the way you use energy in your home – so it will change over time. Please remember that this graph is based on a model - so is more useful for making comparisons between different scenarios than making absolute predictions._

**Comment by cagabi** [comment]
Looking at the rest of the document you sent me it looks like what you want is exactly what you sent me. Forget the question. Sorry

**Comment by cagabi** [comment]
Done
