### ISSUE TITLE
Display somewhere which scenario or master each scenario is 'duplicated' from.

### ISSUE THREAD

**Issue by ajnorthcott** [emoncms/MyHomeEnergyPlanner#318]
When creating a new scenario we select which previous scenario or master the new scenario should duplicate. However it is not possible to see later which one was selected. This makes checking and identifying errors impossible.

**Comment by marianneURBED** [comment]
Agree - this would be very helpful. Could perhaps be displayed in brackets below the title for each scenario on the left-hand panel? 

As a work-around for now, we could adjust how we name scenarios. So for example, if a scenario builds on anything other than the master, say Scenario 2: "Next steps (+priority measures)". With the explanatory text Carlos has automated in the report, this should make things obvious).

**Comment by cagabi** [comment]
This was a quick one, so I have done as you say Marianne
