### ISSUE TITLE
Report to show which scenario or master each scenario is 'duplicated' from  - Linked to #318

### ISSUE THREAD

**Issue by ajnorthcott** [emoncms/MyHomeEnergyPlanner#319]
In the clients report, in the list of measures for each scenario - it would be much better if it had appropriate wording if relevant "In addition to the measures in scenario 1 ....." etc.
So that it is clear to client that the measures are in addition to, or in some cases instead of the list of measures in above scenario(s).
 
Linked to #318

**Comment by marianneURBED** [comment]
Carlos has done this under #315  - unfortunately not possible to do this retrospectively, so will only be applied in new assessments.
