### ISSUE TITLE
EWI areas correction

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#320]
The adjustment made to area when EWI is applied should only affect cost calculations, not the actual dimensions of the energy model. 

At the moment, because applying EWI is affecting the total surface area for the energy calculations, it is introducing a minor error in the calcs (so when you apply EWI the heat loss surface area gets bigger, and so the air-tightness/ infiltration heat loss figures are affected). Probably only makes a noticeable difference on houses that are detached with large surface area. 

Andrew noticed this one when applying EWI to a big house!

**Comment by cagabi** [comment]
Done

**Comment by marianneURBED** [comment]
Carlos - this doesn't seem to have made a difference to an existing assessment - id 169. Is it possible to resolve this?

**Comment by cagabi** [comment]
Oh yes, sorry I didn't say i didn't make it for previous assessments, it would be super messy.
A workaround you can do in this case or any other previous assessment: in all the scenarios:

- Change the dimensions of the wall to the original one.
- Apply the measure again: this will overwrite the previous measure (wrong area after EWI) applying the new one (increased wall area taken only into account for costs calculation).

Please, try the workaround and close the issue if everything ok. Let me know if not

**Comment by cagabi** [comment]
Closing this now as there are no comments
