### ISSUE TITLE
Improve layout, clarity of left hand side panes for Master, Scenario 1 etc

### ISSUE THREAD

**Issue by ajnorthcott** [emoncms/MyHomeEnergyPlanner#323]
It could improve greatly the usability of the tool and avoid inputting into the wrong scenario by improving the design of the left hand side pane / options. So it is much clearer which scenario is being entered.
Eg the panes could be colour coded - or made into clearer windows with tabs at the top.
Additionally the button to apply measure - could be dynamic and show "Apply measure to Scen 1".

Overall the tool good be clearer about applying and viewing the measures applied. Without having to create a report each time to view the outcome.

**Comment by marianneURBED** [comment]
This is a bit of a design issue that it might be worth getting some design input for - possibly from Fieldwork or someone similar?

**Comment by cagabi** [comment]
Could be enough with making the text of the selected scenario a bit bolder, adding a border and/or fading the scenarios not slected

**Comment by cagabi** [comment]
Hi,

> It could improve greatly the usability of the tool and avoid inputting into the wrong scenario by improving the design of the left hand side pane / options. So it is much clearer which scenario is being entered.

I have been thinking on this for a while and (despite I don't use the tool as much as you both) and I cannot think on how changing the panes on the left would help. What I have done so far is: 

- added the scenario name to the top of the page, 
- automatically scroll to the top when a new scenario is created or deleted
- collapse the left menu when a scenario is created or deleted

The apply measure button becomes too big when adding the text to it: "Apply measure to Scen 1".

> Overall the tool good be clearer about applying and viewing the measures applied. Without having to create a report each time to view the outcome.

The "revert to master" text kind of does the job but it's not implemented for everything item that can have a measure applied to. Do you think it is worth to do the "revert to master" from everything or would it be enough just adding a text saying "Measured applied"?

**Comment by cagabi** [comment]
The "Measure applied" feature was also requested in #119

**Comment by cagabi** [comment]
I have added the "Measure applied" everywhere.
Can you please check if you are happy with the changes I did with regards to identifying the scenario

**Comment by marianneURBED** [comment]
Superseded - general UI review to take place in V3 by April 2020.
