### ISSUE TITLE
Space heating demand and thermal bridging error on case HEA016 Grange

### ISSUE THREAD

**Issue by ajnorthcott** [emoncms/MyHomeEnergyPlanner#324]
Not sure if related to #320
With this case HEA016 where we encountered issues previously I observe that :
1. Scenario 3, the space heating demand increases, despite the measures applied
2. Scenario 3, Thermal ,Bridging rises from 42W/K to 43 W/K

Scen 3 includes IWI, pitched roof ins, glazing, etc

Andrew Northcott
andrew@cafs.org.uk

**Comment by cagabi** [comment]
Hi Andrew,

Sorry for delay in my reply, I have found the problem and sorted it for the assessment: the thermal mass parameter value was missing so the calculation of useful gains was resulting in 0 so the heat requirements went up.

This is not the first time that happens, I remember trying to replicate the problem in the past but I was not able to do it. I have opened an issue and will try to sort it.

All the best,

    Carlos
