### ISSUE TITLE
Losing some inputted data (not saving latest work)

### ISSUE THREAD

**Issue by LorenzaURBED** [emoncms/MyHomeEnergyPlanner#329]
Coming out of an assessment to check another assessment, and when returning finding that last 20 minutes or so of inputted work has vanished (I was working in "Fabric" section). This has happened on assessment CC10_PR_M19 2EZ. I will re-input the lost data but bug needs fixing. I don't know what made this happen. I got no warning of any kind. @cagabi #

**Comment by cagabi** [comment]
Hi Lorenza, can you please share the assessment with me.

I'll have a look but there is not enough info for me to think what can have been the problem. If you can think of any extra clues that may help

**Comment by cagabi** [comment]
cagabi

**Comment by cagabi** [comment]
I have had a quick look: I created a test floor and window, logged out and the in (several times). And it seems to be ok and no data was lost. This can be a difficult bug to replicate.

Another thought I am having, do you think you could have the assessment opened in two different windows, tabs or computers? This could be the reason for the lose of your new inputs. I'll explain myself: 

- you and me have the same assessment opened
- you do all your changes and they are saved
- you  close the assessment in your computer but the old version is still open in my one
- I do a change in the assessment in my computer
- that change is automatically saved
- your changes have been overwritten by the my old version of the assessment plus the last change I did

Do you think this could have happened?

**Comment by LorenzaURBED** [comment]
I don't think I did this, when I open/log in into website on Firefox I close down the window opened in Chrome etc. However I can see how that could happen, so I will make sure not to do that. 

If you think the assessment is not corrupted then I'll carry on. I am now a little paranoid it's going to do it again ;-)

Thanks,
L

**Comment by cagabi** [comment]
I think it should be ok, but I cannot really say.  Please keep me updated if you see anything rare.
By the way, do you know you can save your assessment in your computer? Go to "Export/import" (in the left menu) and click on "download project data". The you can import it in the same place on "Upload project"

**Comment by LorenzaURBED** [comment]
I didn't know I could save the assessment. I may do this as 'back up'. Thanks again for your assistance.

**Comment by lowwintersun** [comment]
I think @marianneURBED has commented in the past that refreshing the browser can sometimes iron out these bugs. Though I'd let her confirm that in case I'm suggesting something catastrophic!

**Comment by cagabi** [comment]
Talking with Marianne I realized about another option for this loose of data: maybe there was no internet connection and the assessment couldn't be saved, then you finished with the assessment, closed the browser and everything got lost forever.
I'd add a pop up warning that will display when there is no internet connection

**Comment by LorenzaURBED** [comment]
Thanks Carlos, will bear all this in mind.

**Comment by lowwintersun** [comment]
@cagabi for the Plymouth tool, we have implemented a 'save locally' option for times of no internet. It saves the java string in the temporary internet folder of the browser being used. It might be something to add as a feature and a nice fail safe.

**Comment by cagabi** [comment]
I like the "save locally" idea. How does that work? Does the assessor click a "save" button or does it work behind the scenes (saving locally when there is no internet and then uploading the assessment when internet is back)?

**Comment by cagabi** [comment]
Similar thing has just happened to Lorenza filling up the comment in household questionnaire

**Comment by LorenzaURBED** [comment]
Yes me again, similar on issue on same assessment. If you are able to find the lost text, that would also help. If it's not possible, don't worry I will write it all again.
Thanks.

**Comment by cagabi** [comment]
Hi,
Has this happened again?

**Comment by marianneURBED** [comment]
Not in any of the assessments I’ve done since January, so I’d say it’s safe to close.

M
