### ISSUE TITLE
Review solar thermal inputs and enable solar thermal as a measure

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#330]
Especially in off-grid locations in Cumbria, solar thermal is still relatively common. 

We need to check this for inputs for existing systems - it's not very usable at the moment - but also be able to apply measures for proposed systems.

**Comment by cagabi** [comment]
Hi I don't know how to tackle this.

First we need to review the inputs, have we got any expert we could ask for help?

Then we need to find the measures, Marianne is that something you can do?

**Comment by marianneURBED** [comment]
Subsumed in general hot water calcs improvements to be done in Version 4 - after April 2020.
