### ISSUE TITLE
Library item missing - scenario measure to flat roof

### ISSUE THREAD

**Issue by LorenzaURBED** [emoncms/MyHomeEnergyPlanner#333]
@marianneURBED 

For Dean Bank Avenue, M19 assessments, within the Apply Measure (for scenarios build up) I need another option to FRI_04 where it is Flat Roof insulated with 200mm within roof structure and below. This is because all roofs are continuous, and adding insulation on top would mean step change in roof line, more difficult to seal with roof covering (liquid roof membrane or single ply).

Thanks!

**Comment by LorenzaURBED** [comment]
With regard to property No.1, it currently has an old Gas boiler for space heating and then a **Gas Fired Balanced Flue water heater**, the latter is not in the library (or I can't see it if there is). 

Thank you.

**Comment by marianneURBED** [comment]
Roof done. 

The gas water heater is there - under 'hot water only systems' - most likely a multi-point gas water heater. 

Thanks, 

Marianne
