### ISSUE TITLE
Clarification on amending Master once a Scenario has been created

### ISSUE THREAD

**Issue by LorenzaURBED** [emoncms/MyHomeEnergyPlanner#334]
Hi @cagabi 
Can you confirm/clarify this for me?

I have inputted all data in the Master, so I go ahead and create Scenario 1. I fill in Scenario 1 with applied measures and then I realise that I forgot to add an element in the Master. So I go back to the Master and add such element. 

Now, the Scenario 1 box/title (left hand side) shows a little star symbol to make me aware that there is a discrepancy between this and the Master.
<img width="332" alt="screen shot 2017-11-20 at 18 10 22" src="https://user-images.githubusercontent.com/25234466/33034052-865e58e2-ce1e-11e7-88bb-2a5ab531ca22.png">

Can I go into Scenario 1 and add the additional item from the Master, to ensure the two model relate to each other and carry on? Or do I have to delete the whole of Scenario 1 and start again??

Thanks!
Lorenza

**Comment by cagabi** [comment]
Hi Lorenza
You don't need to start the scenario from the beginning. 
You can create the new fabric element in the scenario, this new element will have the same id (last element id + 1) than the one you created in master. So for the program they will be the same element.
Beware of:
- if you keep adding fabric elements to the master, you need to add them to the scenario in the very same order
- This trick is only valid for fabric elements, it maybe true for other bits of MHEP as well but I would need to think them one by one
- Even doing what I say, the little star next to the scenario name, will stay there
I leave this issue open just in case but please close it if you haven't got more comments

**Comment by cagabi** [comment]
Linked to #302

**Comment by LorenzaURBED** [comment]
Thanks Carlos. I have taken a screen shot so I can save it and refer back to it if I ever forget. 

Does sound like it's best to delete the scenario if possible and start again. But it's good to know if I realise I missed something in the Master and the whole report is finished, if I follow the steps above I can amend without having to start all over again.

**Comment by cagabi** [comment]
It's good you are self sufficient and that you know the tricks :)
But just thought about another option, sorry if it comes late: I can manipulate the data in the database and fix this kind of problem manually.
