### ISSUE TITLE
bug in Lighting SAP calculation 

### ISSUE THREAD

**Issue by LorenzaURBED** [emoncms/MyHomeEnergyPlanner#336]
@cagabi 

I think there's a bug when you apply the measure to "Replace all with LLE". In assessment CC10_PR_M19 2EZ I have 14 under LLE and 6 under L. When I apply the measure this changes to 6 "LLE" and 6 "L"... this doesn't look right? It should be 20 "LLE".

Thanks again for help provided. 

<img width="1064" alt="screen shot 2017-11-29 at 10 55 21" src="https://user-images.githubusercontent.com/25234466/33372039-94cfd0ae-d4f4-11e7-90a9-3c795afb28b0.png">
<img width="1065" alt="screen shot 2017-11-29 at 10 55 27" src="https://user-images.githubusercontent.com/25234466/33372047-9859a15a-d4f4-11e7-92fa-bab4d380b9b7.png">

**Comment by cagabi** [comment]
Hi Lorenza,
There is something wrong there: L is the total number of lights (not only the "high" energy ones). I know it's confusing, this is how SAP asks the question and we copied it over.
Basically in the household there are 6 lights of which 14 are low energy, jejeje, new maths.
When applying the measure, all the light become low energy, in your case 6 of them.

**Comment by cagabi** [comment]
I guess this means you have to change master and scenario. Do you want me to manually do it? 
Please take a back up first

**Comment by LorenzaURBED** [comment]
OK I get it! Thanks Carlos.

So the house has 20 lights of which 14 are low energy. So I put 20 in L and 14 in LLE. Right? 

I'll get there eventually, I promise ;-)

**Comment by LorenzaURBED** [comment]
I'll correct at my end. Thanks!

**Comment by LorenzaURBED** [comment]
Carlos. Sorry, but I have updated the Master, gone into Scenario 1 and it's not letting me update it. Can you then fix this at your end?

**Comment by cagabi** [comment]
Yeah doing it now

**Comment by cagabi** [comment]
Everything sorted :)
