### ISSUE TITLE
delete of all data from assessment

### ISSUE THREAD

**Issue by LorenzaURBED** [emoncms/MyHomeEnergyPlanner#340]
Hi @cagabi 

I had made a copy of CC09 assessment into a new one "Reference Adele" to use as reference while I was amending CC09.

It has just lost all data in there. It's not the end of the world, as it was only a reference and I would have deleted it at the end, but worrying it just erased everything from it.

I had two tabs open, one on "Reference Adele" and one on "CC09_PR_M19 2EZ". Still logged in, no timed-out issues. I went to refresh both pages and "Reference Adele" then became blank, erased the Master and all the Scenarios. While on "CC09_PR_M19 2EZ" it lost data I had entered in Fabric section for Scenario 3.

I can reapply measures in Scenario 3, it won't take me long. But thought it was best letting you know as this seems to be a re-occurring bug.

Thanks again!
Lorenza

**Comment by marianneURBED** [comment]
linking to #329 and closing this one, as suspect are related issues.
