### ISSUE TITLE
Can't delete items when editing libraries

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#343]
When editing standard library, was unable to delete some measures. Got the error message shown in the screen shot below. Tried refreshing etc, but to no avail. 
<img width="1440" alt="screen shot 2018-01-08 at 17 17 26" src="https://user-images.githubusercontent.com/16305707/34682830-0c7d6db0-f498-11e7-9aae-3e537effba42.png">

**Comment by marianneURBED** [comment]
I can't currently complete what's required to deal with #331 until this is sorted. High priority because this becomes more important as the tool is more well known - a lot of the measures in the current libraries should really only be chosen and used by trained assessors and aren't suitable for use by lay/inexpert users.

**Comment by marianneURBED** [comment]
Tried in firefox. Same problem.

**Comment by cagabi** [comment]
Hi,

I have fixed the issue but I know from before that you will not be happy with the solution as this came up before.
The problem were the apostrophes '''''''''''''''''''''''' in the description of some elements. Ages ago I made the code to remove them when creating/editing an element. I guess last time I updated the handcoded libraries I left some '''''''''''''''''''' there. Now there isn't any

**Comment by marianneURBED** [comment]
I forgive you. Needed done.

________________________________
