### ISSUE TITLE
Library Editing - Usability Issues

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#344]
Editing the libraries at the moment is a painful task. Lots of opening and closing dialogue boxes, and also not being able to see different elements and measures at the same time, so making checking for consistency very difficult. 

Is it possible to make a special 'editing' view, that shows all the data in table form to make comparison easier and bulk edits quicker?

**Comment by marianneURBED** [comment]
#152 same issue.

**Comment by marianneURBED** [comment]
Related - #123 When you delete an element in Library manager it closes the window, would be more convenient if you stayed in the same place.

**Comment by cagabi** [comment]
> Is it possible to make a special 'editing' view, that shows all the data in table form to make comparison easier and bulk edits quicker?

Yes, it's possible.

Would that table show items of one library or all the libraries of a kind. For the first option (items of one library) I think we could replace the pop up when cliking on _Show items_ with the one you say

**Comment by marianneURBED** [comment]
Hello,

The most useful thing would be to see, and be able to edit, all the items in once library from one view.

So you can see where there are common aspects that should be copied across different items, and be consistent in wording etc. Should also make editing quicker.

M

**Comment by cagabi** [comment]
Hi, I have done the new tables for editing the libraries. Some of them are massive, very wide. I have made the pop up so you can dragg them around and resize. Also I had to do the text boxes quite small so not all the text is visible, when you hover you can see it all. Have a look and tell me what you think, youmay have dieas how to make them more user friendly.
Also when you delete/create elements from/in library then you stay in the original pop up.

**Comment by marianneURBED** [comment]
Thanks Carlos.

I’m on trains or on site most of today, so will have a proper look at this tomorrow.

M

**Comment by marianneURBED** [comment]
Hi. 

Have been using this this afternoon. It's fine where items are short and the text pithy, but a lot of the descriptions are, as you suggest, hard to see. Agree it's best to be able to read across on one line, but that's probably only really most relevant for the TAGs. What if you were to turn the table round by 90 degrees, and then just restrict the column width? Then you could keep the top few lines of the column to one line each, but allow the descriptions to expand a bit?

**Comment by cagabi** [comment]
Hi Marianne,

I have implemented your idea of turning the table around, you can see it in the Heating system library only. If you like it I'll make it for all the others. I personally think it doesn't work any better. Some comments:

- It's not possible to freeze the first column/row so when you scroll in any direction you can not see what the column/rows are. But that was the same before
- I have made the height of the input "Name" bigger. I want you to think how this will work with long Descriptions. I can make the box to automatically set the height to fit the biggest one but then the table will be very odd. For now with the Name, the height is fixed to start with but you can make it bigger with the mouse dragging the corner of the box

For testing as well, I have tried the same thing about the Name input in the Heating System measures library but keeping the old table structure.

Please have a look at both and tell me what you think.

Be aware that editing those two libraries may not work properly.

**Comment by marianneURBED** [comment]
Thanks Carlos – I’ll have a look at this next week too.

M

**Comment by marianneURBED** [comment]
Superseded.
