### ISSUE TITLE
Create a new graph in the report that shows 'Fabric Energy Efficiency' rather than 'Space Heating Demand'. 

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#347]
This is required because we can adjust the settings of the heating systems and their controls in the model. This allows potential for the model to be 'gamed' - so you could hit the targets by simply not heating the house. This also makes comparison between houses more tricky, as heating patterns differ between homes - even where fabric/infrastructure is similar. 

Arguably the Carbon Coop target related to fabric should be applied to Fabric Energy Efficiency rather than Space Heating Demand - so it's about infrastructure, rather than usage patterns. (On the assumption that the housing stock is part of national infrastructure, and so gains are shared and often last longer than the time a particular occupant spends in a house). Note they're both measured in the same units. 

FEES is calculated according to the criteria listed on p.31 of SAP 9.92, copied below. I suppose this means replicating the model somehow in the master and each scenario - does this look possible, or a complete nightmare? 

_Fabric Energy Efficiency is defined as the space heating and cooling requirements per square metre of floor area, obtained at worksheet (109) when calculated under the following conditions:
- climate is UK average for heating and cooling **(MH note - I think we could not do this bit).** 
- natural ventilation with intermittent extract fans
- 2 extract fans for total floor area up to 70 m², 3 for total floor area > 70 m² and up to 100 m², 4 for total floor area > 100 m²
- for calculation of heat gains from the hot water system worksheet (46) to (61) inclusive and (63) are set to zero (equivalent to an instantaneous water heater)
- 100% low energy lights
- column (B) of Table 5 is used for internal gains in the heating calculation
- column (A) of Table 5 is used for internal gains in the cooling calculation
- overshading of windows not less than average (i.e. very little is changed to average)
- no heat gains from pumps or fans
- the heating system has responsiveness 1.0 and control type 2, no temperature adjustment, temperature and heating periods according to Table 9 irrespective of the actual heating system
- cooled fraction is 1.0

Other data items are those for the actual dwelling. The above are special conditions for calculation of Fabric Energy Efficiency and do not apply to other calculations._

**Comment by cagabi** [comment]
I totally agree with the reasons to use Fabric Energy Efficiency instead of Space Heating Demand.
There were some comments about this ages ago when we spotted we wwre calling SHD wrongly as FEE.
I'll do this now.

**Comment by cagabi** [comment]
I have implemented the calculation of the Fabric Energy Efficiency in the model. So this is ready to go in the report. 

@marianneURBED, do you want to replace figure 5 (Space heating demand) or add a new one? In any case I need the text that goes with it

**Comment by marianneURBED** [comment]
Hi Carlos,

I think keeping both will be good – though we do need to think quite carefully about how we explain them.

Assign it to me and I’ll work out some text/ edits.

Thanks,

Marianne

**Comment by cagabi** [comment]
Good, thanks

**Comment by marianneURBED** [comment]
Looks like FEES is being dropped as a concept, so we can drop it. Already report on heat balance which kind of does this job anyway.
