### ISSUE TITLE
Carbon Emissions and Primary Energy Assumptions - Double Counting? 

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#348]
Going through the calculations and their explanations, and following a few conversations I've had recently, I think there might be an issue with how Carbon Emissions savings from generation technologies are accounted for, (and this may be the same issue with PE). At the moment the calculation is simply:

Total household CO2 emissions = other fuels + (kWh elec used x grid carbon factor) - (kWh elec generated x grid carbon factor)

This means that all of the benefits of the energy generation from something like PVs accrues to the household. This seems odd when a lot of this energy (50%+) will be exported to the grid, and therefore will in reality be contributing (in a very small way) to the decarbonisation of the grid - and therefore should already be part of the carbon factor used in the calculation above. 

This doesn't seem fair - and can't be right. It seems like double-counting. On a single house, maybe this doesn't matter much, but if every house in the UK had PVs, and exported 50% of the energy generated, and we did the calculation in this way, it would completely skew things. 

I'd like to suggest that we change the way we do things, however there are definitely people at Carbon Coop who have a better handle on grid/ system wide issues than me, so would welcome comments (from Matt and Ben in particular). 

My simple suggestion would be to change the sum to either:

Total household CO2 emissions = other fuels + (kWh elec used x grid carbon factor) - (kWh elec generated x grid carbon factor x proportion used on site*)

* this may be an estimate, and we probably need better data to make a sensible estimate. At the moment the default is 50%. 

_or being even more conservative:_ 

Total household CO2 emissions = other fuels + (kWh elec used x grid carbon factor)

Any thoughts on this gratefully received!

(Also note that is we make a change like this, we're moving further from SAP - and it makes the whole idea of having SAP ratings in the assessments at all, even heavily caveated ones, problematic).

**Comment by cagabi** [comment]
@beaylott

**Comment by beaylott** [comment]
It is true that there have been dramatic falls in the average grid carbon intensity. These do vary across the course of the year as well.
