### ISSUE TITLE
Use Sankey Diagram in Report to explain systems wide issues....

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#350]
....this might be a better way of representing some of the issues rather than 'primary energy' graph. 

https://developers.google.com/chart/interactive/docs/gallery/sankey

**Comment by cagabi** [comment]
I have done it, see picture below. 

Comments:
 - I don't like very much how it looks but that is not really important ;)
 - We loose the sense of the totals for each scenario. This way it is clearer to compare energy requirements but impossible to compare the totals for each scenario
 - I don't know what to do with the effect of generation. In the bars graph we offset moving the stacks down. With this is not possible.
- Maybe we can display both types of graphs?

The graph is not available now online as I think I will be on holidays when you have a look at this and you may still need to print a report. So if you want to see it by yourself let me know and I'll make it available.

Note for Carlos: Carboncoop Report branch is "sankey_diagram"
![sankey diagram - primary energy](https://user-images.githubusercontent.com/7636325/43480868-5acf3304-94fc-11e8-99a7-fef4cb1efdc5.png)

**Comment by marianneURBED** [comment]
Thinking about this in a different way now - in context of 'zero carbon' discussions and future grid developments.
