### ISSUE TITLE
Ability to add more than three scenarios in the report

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#352]
Three is enough for most people, but sometimes there is an obvious set of 'projects' that tot up to 4 or 5 scenarios. 

Realise this could result in a fairly major reformatting of the report/graphs, so don't expect it will happen anytime soon.

**Comment by cagabi** [comment]
I have done it
By default the report will still load the first 3 scenarios but there is a list of scenarios on the top of the page and a button to reload it.

I need to copy it over to the CAfS report, so I'll close this issue when it's done

**Comment by cagabi** [comment]
Also done for CAfS report
