### ISSUE TITLE
Window Energy Balance

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#354]
It would be useful to have the gains and losses from the windows in the fabric page in the same units - for assessing the energy balance. 

(If possible, totalling up each at the bottom of the table would also be useful).

**Comment by cagabi** [comment]
I am googling with no result, how do you get to W/K from W for the gains? In fact it doesn't makes sense to me that light gains and heat losses can have the same units

**Comment by cagabi** [comment]
I have added the totals to the bottom of the tables

**Comment by marianneURBED** [comment]
Ok, can see why this would be confusing. Both gains and losses (which are both about heat) should really be in kWh/year - so you can make a comparison. Ideally per window and per orientation. 
This would allow you to make a judgement about the size of windows and amount of glazing. e.g. sometimes can be a good idea to decrease or increase glazing on a particular facade to improve the overall energy balance of the building. In any case, not a priority.
