### ISSUE TITLE
Library additions, Brick Historic England, Stone Historic Scotland 

### ISSUE THREAD

**Issue by TrystanLea** [emoncms/MyHomeEnergyPlanner#362]
Hello @marianneURBED, @cagabi 

I would like to add fabric element U-values for traditional buildings that have come out of recent in situ monitoring to the library. The elements below are from a historic england report. 

Im also thinking about the option to outline a range of U-values with a min and max, we could then potentially do an error analysis in future. 

I also wonder if we break down the standard library file so that there is a library folder with sub folders: elements, elements_measures, draught_proofing_measures etc, with files such as historic-england-brick.json etc to help with organisation?

Just a couple of thoughts for now.

Source: https://historicengland.org.uk/images-books/publications/research-thermal-performance-traditional-brick-walls/

        "SW1_UBm": {
            tags: ["Wall"],
            name: "Brick 300mm with internal plaster",
            description: "Measured U-value, ENGLEFIELD Brick 300mm with plaster + wallpaper or paint",
            location: "",
            source: "English Heritage 2013, Page 9, Table 3",
            uvalue: {min:1.2, max:1.6, mean:1.40}, kvalue: 150,
            notes: "Wet bricks increases thermal conductivity significantly"
        },
        "SW2_UBc": {
            tags: ["Wall"],
            name: "Brick 300mm with internal plaster",
            description: "Calculated U-value, ENGLEFIELD Brick 300mm with plaster + wallpaper or paint",
            location: "",
            source: "English Heritage 2013, Page 9, Table 3",
            uvalue: {min:1.5, max:1.7, mean:1.60}, kvalue: 150,
            notes: "Wet bricks increases thermal conductivity significantly"
        },
        "SW3_UBm": {
            tags: ["Wall"],
            name: "Brick 300mm, drylined",
            description: "Measured U-value, ENGLEFIELD Brick 300mm, drylined with plasterboard + wallpaper or paint",
            location: "",
            source: "English Heritage 2013, Page 9, Table 3",
            uvalue: {min:1.0, max:1.1, mean:1.05}, kvalue: 100,
            notes: "Wet bricks increases thermal conductivity significantly"
        },
        "SW4_UBc": {
            tags: ["Wall"],
            name: "Brick 300mm, drylined",
            description: "Calculated U-value, ENGLEFIELD Brick 300mm, drylined with plasterboard + wallpaper or paint",
            location: "",
            source: "English Heritage 2013, Page 9, Table 3",
            uvalue: {min:1.1, max:1.2, mean:1.15}, kvalue: 100,
            notes: "Wet bricks increases thermal conductivity significantly"
        },
        "SW5_UBm": {
            tags: ["Wall"],
            name: "Brick 225mm with internal plaster",
            description: "Measured U-value, SHREWSBURY Brick 225mm with plaster + wallpaper or paint",
            location: "",
            source: "English Heritage 2013, Page 9, Table 3",
            uvalue: {min:1.0, max:1.5, mean:1.25}, kvalue: 150,
            notes: "Wet bricks increases thermal conductivity significantly"
        },
        "SW6_UBc": {
            tags: ["Wall"],
            name: "Brick 225mm with internal plaster",
            description: "Calculated U-value, SHREWSBURY Brick 225mm with plaster + wallpaper or paint",
            location: "",
            source: "English Heritage 2013, Page 9, Table 3",
            uvalue: {min:1.8, max:2.0, mean:1.90}, kvalue: 150,
            notes: "Wet bricks increases thermal conductivity significantly"
        },
        "SW7_UBm": {
            tags: ["Wall"],
            name: "Brick 225mm with internal plaster",
            description: "Measured U-value, WALSALL Brick 225mm with plaster + wallpaper or paint",
            location: "",
            source: "English Heritage 2013, Page 9, Table 3",
            uvalue: {min:1.9, max:2.3, mean:1.25}, kvalue: 150,
            notes: "Wet bricks increases thermal conductivity significantly"
        },
        "SW8_UBc": {
            tags: ["Wall"],
            name: "Brick 225mm with internal plaster",
            description: "Calculated U-value, WALSALL Brick 225mm with plaster + wallpaper or paint",
            location: "",
            source: "English Heritage 2013, Page 9, Table 3",
            uvalue: {min:1.8, max:2.0, mean:1.90}, kvalue: 150,
            notes: "Wet bricks increases thermal conductivity significantly"
        },
        "SW9_IB": {
            tags: ["Wall"],
            name: "Brick 225mm, drylined, insulated plasterboard",
            description: "Measured & calculated U-value, WALSALL Brick 225mm, drylined, insulated (25mm) plasterboard  + wallpaper or paint",
            location: "",
            source: "English Heritage 2013, Page 9, Table 3",
            uvalue: {min:0.6, max:0.7, mean:0.65}, kvalue: 50,
            notes: "Wet bricks increases thermal conductivity significantly"
        }

**Comment by TrystanLea** [comment]
A number of provisional historic Scotland elements:

https://www.historicenvironment.scot/archives-and-research/publications/publication/?publicationId=16d0f7f7-44c4-4670-a96b-a59400bcdc91

        "SW10_HS_SP": {
            tags: ["Wall"],
            name: "Stonewall 600mm, plaster on laths",
            description: "Measured U-value, Stonewall 600mm, plaster on laths",
            location: "",
            source: "Historic Scotland 2011, Page 21",
            uvalue: {min:0.9, max:1.3, mean:1.1}, kvalue: 150,
            notes: "Damp walls increase U-value significantly"
        },
        "SW11_HS_SD": {
            tags: ["Wall"],
            name: "Stonewall 600mm, drylined",
            description: "Measured U-value, Stonewall 600mm, drylined",
            location: "",
            source: "Historic Scotland 2011, Page 21",
            uvalue: {min:0.7, max:1.1, mean:0.9}, kvalue: 100,
            notes: "Damp walls increase U-value significantly"
        },
        "SW12_HS_SS": {
            tags: ["Wall"],
            name: "Sandstone 550mm, bare",
            description: "Measured U-value, Sandstone 550mm, bare",
            location: "",
            source: "Historic Scotland 2011, Page 24",
            uvalue: {min:1.3, max:1.5, mean:1.4}, kvalue: 150,
            notes: "Damp walls increase U-value significantly"
        },
        "SW13_HS_SSD": {
            tags: ["Wall"],
            name: "Stonewall 600mm, drylined",
            description: "Measured U-value, Stonewall 600mm, drylined",
            location: "",
            source: "Historic Scotland 2011, Page 24",
            uvalue: {min:1.0, max:1.2, mean:1.1}, kvalue: 100,
            notes: "Damp walls increase U-value significantly"
        }

**Comment by marianneURBED** [comment]
From here on in the library available to get someone started will just have a few basic elements to get people started, and they can then add whatever they want to their own library. So this issue superseded. I'm updating the Carbon Coop library in next month.
