### ISSUE TITLE
Move openBEM (the model) out MHEP

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#368]
Create a new repository and add it to MHEP as a submodule

**Comment by TrystanLea** [comment]
Whats the idea for this?

**Comment by cagabi** [comment]
The model is a self contained piece of code which is not dependent on the rest of MHEP.  In fact, at some point we had the conversation (I can't remember with who though) of  bringing back the openBEM name for the model to differentiate it from MHEP. Also for practical reasons I think people should be able to clone just the model.

As an example of the above: MHEP is a user interface for openBEM in the same way that MyHomeEnergySalford, so it makes sense to me to that for both softwares we add openBEM as a submodule.

Finally, I am afraid that the value of the model is forgotten. So not only for the practicalities but also for openBEM's ego I think it deserves it's own space.

Having said all of that I don't feel super strong about it, so no need to do it if there are any other good reasons against it.

**Comment by marianneURBED** [comment]
Taking a different tack with this now - this is practically too difficult (too many interdependencies between the 'front end' and 'back end') and so instead to enable better version control we have instead integrated all aspects into a single 'version' of the tool.
