### ISSUE TITLE
Floor U-value calculations not 'sticking'

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#369]
When you use the floor U-value calculator, then press 'calculate' the numbers appear in red on the 'Fabric' page in MHEP, but if you click away to another page and go back, they've disappeared. 

It's possible to overcome this by remembering or noting the number, and then re-typing it - but this can't be a long-term solution, as it's liable to lead to assessor error, with '0' values being left for floor U-values by accident.

**Comment by cagabi** [comment]
Fixed
