### ISSUE TITLE
NaN value shown for B' in floor u-value calculator for slab on ground. 

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#370]
Not sure if this is an error in the calc (from those I've tested, don't think so) or just a display error.

**Comment by cagabi** [comment]
Wait I think I got it, 
When perimeter and area already in MHEP and you open the calculator NaN is shown. As you soon as you change any of them, the Nan goes. Even if you don't change them the calculation is properly made, so no need to worry for now, I think.

I'll fix it now

**Comment by marianneURBED** [comment]
Yes, that seems to have solved the issue. Thanks Carlos.
