### ISSUE TITLE
Report £ Measure cost figure 

### ISSUE THREAD

**Issue by ajnorthcott** [emoncms/MyHomeEnergyPlanner#373]
The measures cost on the first page of the report does not reflect the total costs of the measures highlighted in the report.
Suggest it 
- Describes which scenarios this is for. (ie all 3 scenarios?)
- Is rounded to nearest whole £ - currently it shows to many decimal places

**Comment by cagabi** [comment]
Just checked properly and the cost of measures shown inn the report page are the one from scenario3

**Comment by cagabi** [comment]
Sorted, now the Measures costs are only showed when the user is in a scenario page only (not in the reports)
