### ISSUE TITLE
Report blank pages

### ISSUE THREAD

**Issue by ajnorthcott** [emoncms/MyHomeEnergyPlanner#374]
The reports still contain blank pages that are not possible to remove easily in a pdf.

**Comment by cagabi** [comment]
Hi, I have removed the blank pages I have found, please have another look.

The only thing is that now there are some extra blank pages appended to the end of the report. I cannot work out why they are there and of course how to remove them. If you don't mind I'll leave it like that, being at the very end they don't break anything.

I'm closing this issue now but please open it again if there are more things
