### ISSUE TITLE
When applying measures or moving through the tool, keeps jumping back to main menu

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#375]
When you're in 'fabric' or 'ventilation' etc on a particular scenario, and then apply a measure or make a chance it jumps to all the scenarios in the left hand panel being collapsed/ back to top of page, so you then have to go and click back to where you were to carry on applying measures. 

This is a bit frustrating, but also liable to lead to errors. 

Didn't happen until very recently - so may be related to merging back with the main emon CMS code? 

I'm using chrome.

**Comment by cagabi** [comment]
Sorted
