### ISSUE TITLE
Report figure 2 clarity

### ISSUE THREAD

**Issue by ajnorthcott** [emoncms/MyHomeEnergyPlanner#376]
The labels in the tables in fig 2 could be a lot clearer. Particularly the labels for the vertical dotted lines showing Max and Min targets, Carbon Coop 2050 target, UK Average etc.
Its an issue currently as the text overlaps the bars and it is not clear what the text refers to in some cases.

**Comment by cagabi** [comment]
The problem here is that, due to the way the graph is drawn, the text has to be inside the graph, not sure what to try.
Any idea?

**Comment by marianneURBED** [comment]
Subsumed in report edits in Version 2 for Jan 2020.
