### ISSUE TITLE
Default MHEP report

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#377]
So far MHEP report does the summary of all the scenarios and comparison between master and other scenarios (this  is not working properly #300 though) 

Before I go into remaking the Carbon Co-op report to ensure we don't use MHEP code I would like to know what do we want in the default report.

FYI, I have been thinking how to do it and it is possible to make both reports to look as they do now without having any licensing problems ;) So this is also an option.

**Comment by cagabi** [comment]
As part of #119 I have added the tables with the summary of measures. In my opinion MHEP  report is looking pretty good now and I wouldn't change it unless you think different

**Comment by marianneURBED** [comment]
Think it's fine as it is.
