### ISSUE TITLE
Weird thing happening when refreshing pages in chrome. 

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#386]
When you refresh a page, the view of the main section of the page shifts so you can't see it properly, and the scrolling stops working properly. Happening in all sections of tool - heating, fabric, report etc. Like this:
<img width="1440" alt="screen shot 2018-05-30 at 16 26 57" src="https://user-images.githubusercontent.com/16305707/40730421-7e379248-6426-11e8-85f7-93d8adaa1be7.png">

**Comment by marianneURBED** [comment]
When you log out of assessment in question and go to overview page, then go back into the assessment, it fixes it, temporarily at least.

**Comment by cagabi** [comment]
Yes, that is weird.
I have tried with several assessments, opening them, refresing the page, navigating different sections, refreshing again and haven't been able to replicate the problem.
Can you give me an id of an assessment? And just in case, browser and version of it?
Thanks

**Comment by cagabi** [comment]
No need for you to send an id, working on next issue #387  I have replicated the problem when refreshing the report page. I wonder if they are related errors

**Comment by marianneURBED** [comment]
Ok. Thanks for looking at this.

I’m using Chrome – in case that helps (Version 66.0.3359.181 (Official Build) (64-bit)

Haven’t yet seen if I can replicate the issue in Firefox.

It did seem to start happening when I clicked into and then out of the report again – though I could be mis-remembering that, so don’t take it as gospel.

M

**Comment by cagabi** [comment]
Ups, I have just realised you already said Chrome in the title.
Sorry but I need to ask again for an id for an assessment. I was able to replicate this problem in id = 253 but once I have fixed issue #387 everything is ok. Was it happening in more than one assessment, if so, please check and send another id otherwise it has been fixed.

**Comment by marianneURBED** [comment]
No, it was just that assessment and I think that’s fixed it.

Will reopen the issue if it turns up again.

Thanks!
