### ISSUE TITLE
All formatting and graphics have disappeared from report!

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#391]
Hello, 

All the graphics and layout has disappeared! Is now just a stream of text as per the attached screenshot. 

I have to get a couple of reports out this week (and I'm not sure if this is affecting Andrew on the CAfS report too), so this needs to be fixed pretty urgently. Hoping it's a simple bug!

<img width="1440" alt="screen shot 2018-07-02 at 14 58 20" src="https://user-images.githubusercontent.com/16305707/42168319-8e3ac5ba-7e08-11e8-8f7a-a2865cdd3e23.png">

**Comment by cagabi** [comment]
Ups ups, I think I know what this can be. I am fixing something for Andrew first an then will sort this

**Comment by cagabi** [comment]
Sorry about that. It's fixed now

**Comment by marianneURBED** [comment]
No problem.

Only a minor panic!
