### ISSUE TITLE
HELP! Tool completely bust....

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#396]
Hello, 

On an assessment I'm doing the tool has completely broken. I can't see anything other than this screenshot, despite having entered lots of data!

Same issue in Chrome and Fire Fox. And I'm not able to capture the data via import/export to try it in another assessment. 
<img width="1196" alt="screen shot 2018-07-24 at 14 23 34" src="https://user-images.githubusercontent.com/16305707/43141277-740d9ee6-8f4d-11e8-8684-11cb7fe0425a.png">

Happened just after I added an item to the Library. 

Any chance you could save several hours of work!?! Help!

**Comment by marianneURBED** [comment]
It's assessment ref 256. Just shared with you. 
Thanks!

**Comment by cagabi** [comment]
Looking at it now

**Comment by cagabi** [comment]
It's working now.
The problem was that Scenario 3 had been created from Scenario 1 and then Scenario 1 was deleted. The tool was crashing when checking if it had to show the * that tells that the parent scenario has changed
