### ISSUE TITLE
SAP version 10 is here!!!

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#402]
https://bregroup.com/sap/sap10/

Skim read suggests there are some improvements (e.g. in lighting calcs and PV related issues) that we should incorporate in MHEP. Though needs a thorough review and consider whether for example, there are other better methodologies for some elements (e.g. BREDEM or something similar for hot water calcs). 

I'm happy to have an initial stab at this, and log each individual improvement/change as an issue on github for discussion/implementation. 

Sharing the full doc so everyone can see and comment on the whole too (suggest you look at the 'changes' doc first), or log an individual issue here in response. 

We also need to think about version control - How this affects older assessments could create inconsitencies/ confusions in older/completed assessments. Important when we now have an archive of older assessments that we need to keep accessible/understandable  (feeds into the 'log-book' discussion). Is there a way of isolating them, so you always have a version that runs on the calculation/report as originally produced, but also see the changes due to revised calc methods/ report formats etc?

**Comment by marianneURBED** [comment]
Useful article on carbon factors here: https://www.cibsejournal.com/general/sap-in-building-regulations/?utm_source=marketingcloud&utm_medium=email&utm_campaign=Journal%20Newsletter%20September%202018&utm_term=0032000001nA5joAAC

**Comment by cagabi** [comment]
I think for the implementation of the changes it would be useful to create one issue per change. Marianne, better if you create them as you say you may find that there are better methodologies. So I prefer you telling me what to do.

In terms of version control what our options depend on the nature of the changes we have to do in MHEP: 

1. If the changes are only made in the model (and the user interface doesn't change) we could have a tick box somewhere to choose which SAP version to use. In this case we would keep the files for SAP2012 and create new ones for SAP10 and run one model or the other according to the user's choice
2. If the changes are also done to the user interface, keeping the possibility to choose the SAP version would be more work and more difficult to maintain. In this case I think the best option would be to create an archived MHEP for the old assessments.

Things to consider:
- If the changes have to be done to the user interface this means that the inputs to the model have changed therefor some assessments done with SAP2012 may not be compatible with SAP10 and viceversa. This is the reason for option 2 above
- I have had a look at the list of changes and see that many of them are updates to the tables or addition of new options this would allow us to go for option 1 but I would need to look in detail each change. For example _The treatment of mechanical ventilation system heat recovery and aerodynamic
performance has been revised._ Is this just in the model or do we need to ask more info to the user.

So with all of this my proposal is:
- Create the archive MHEP and forget about it. 
- Start implementing the changes hoping we can keep only the new version of MHEP. 
- If we hit a wall and find out that the two versions are not compatible then we know that old assessment have to be run in the archived version of MHEP

**Comment by cagabi** [comment]
After implementing #410 I have realised there is no need to worry about the problems I say in point 2.

Now the version of the model gets saved with the assessment. All the assessment that share the major version (**10**.1.1) will always be compatible and the user will be able to choose between them. If the implementation of SAP10 requieres and increment in that major version (becoming 11.0.0) when rendering the user interface we can check the value of the major version and display the right inputs. 

There is no need to keep different MHEP sites for major versions of the model, phew.

**Comment by marianneURBED** [comment]
Procrastination has it's benefits - here comes SAP 10.1: https://www.bregroup.com/sap/sap10/

**Comment by gervasemangwana** [comment]
I hardly dare say it but ditch SAP and go PH?


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by marianneURBED** [comment]
Ha! I think you’ll make people’s hair fall out with fright.

The dream is to run both!

M

**Comment by marianneURBED** [comment]
SAP 10 calculation improvements separated into different issues and so this is superseded.
