### ISSUE TITLE
Site Down!??

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#403]
Can't access https://myhome.carbon.coop/ !!!

Both fire fox and chrome say the server IP address cannot be found.

**Comment by marianneURBED** [comment]
Message - 
This site can’t be reached
myhome.carbon.coop’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by cagabi** [comment]
I know we have recently changed our domain registrar and probably this is related. I'll get somebody to have a look

**Comment by beaylott** [comment]
The domain was transferred to a new registrar but the records for myhome did not move across properly. This was fixed on Tuesday and the site looks ok now. If there are any issues in future you should report it directly to me/Matt. You can also 'assign' additional people in github issues which results in them getting notifications.

**Comment by beaylott** [comment]
You should close this now
