### ISSUE TITLE
Reporting error on Infiltration

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#407]
Hello, 

On an assessment Gervase is working on there is an issue with the house graphic for structural infiltration. Assessment id 290. Have shared it with you Carlos. 

Strange thing happening: 
 - In scenario 2 the reported structural infiltration (on the ventilation page) is 0.1ACH, but the house graphic at the top of the page and in the report shows draughts as '0'. 
 - In scenario 3, which is more airtight and has better ventilation (MVHR) the reported structural infiltration is 0.04ACH, and on the house graphic it reports a 7W/K heat-loss from draughts/ infiltration. 

This isn't right! Based on the ACH figure, you'd expect the reported heat-loss on the house graphic in scenario 2 to be around 17.5 W/K. 

I've had a look around and can't spot what's causing this. Carlos - could you check the code to see if it's a bug? Or if it's some quirk of the calcs that I can't spot? Thanks.

**Comment by cagabi** [comment]
Hi, the reason why the infiltration losses are 0 in scenario 2 is because they are too little compared to the ventilation losses.
Please have a look at  worksheets p.180 SAP2012:

For the scenario 2 (MEV):
- 24c is the effective air change rate due to infiltration adjusted air change rate (22b) and ventilation system air change rate (23b)
- if infiltration acr < 0.5*ventilation acr   --->   effective acr = ventilation acr 
- else     effective acr = infiltration acr + 0.5 * ventilation acr 

For scenario 3 (MVHR): its formula 24a which always takes into account the infiltration.

Would it makes sense in 24c to always apply the formula that takes into account  both infiltration and ventilation?

**Comment by marianneURBED** [comment]
Hi, 

Sorry, only had time to review this now.

Ok that's another of the quirks of SAP - that will, if I'm reading it right, lead to an underestimation of heat losses from infiltration in some cases? I wonder why they've done that? What evidence its based on? I'm tempted to ask Diane about it - she's the infiltration in SAP expert. 

I'm quite happy in the case of MHEP to ditch that and instead at 24c and as you suggest always take into account the infiltration, whatever its relative size when compared to the ventilation losses. It otherwise does look quite odd. 

Do you think this is something that can be done quite simply, and then Gervase can issue this assessment?

**Comment by cagabi** [comment]
Hi, I have done the change and documented the difference with SAP.

**Comment by gervasemangwana** [comment]
Hi Carlos

Just noticed that in scenario 2 on CC_20 it still shows zero infiltration but 85 W/K ventilation. Is that right. 

I’ve tried exporting the assessment and importing to a copy and also tried applying a different measure then reapply MEV but still the same. 

thanks

Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by cagabi** [comment]
It's showing 18 for me.
You may have to clear the cache of your browser to load the file of the model again.
Try and let me know

**Comment by gervasemangwana** [comment]
Bingo!! Thanks. I even managed to work out how to just clear cache for that website only!!

OK, one more question. Why is ventilation loss zero for intermittent fan scenarios (master and scenario1? 

thanks


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by cagabi** [comment]
In master it's 6 W/K
In scenario1 it is 0.1328W/K, does that look right?

**Comment by gervasemangwana** [comment]
Hi Carlos

The ventilation strategy is identical in those two scenarios. 

I would have thought if it is 6W/K in master it would be 6 W/K in scenario 1. 

But this may be a SAP thing interweaving ventilation and infiltration?

cheers

Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by cagabi** [comment]
Again you have to look at worksheets p.180 SAP2012:

For these scenarios the calculation of the loses is 24m: in master we're in the case when (22b)m >= 1 while scenario1 is the other. So the results are a bit different.

I should have realised about it when doing the change for 22c. I guess we want to make the same change here and always apply the second formula??

**Comment by marianneURBED** [comment]
Yes please – makes sense to be consistent about it.

M

**Comment by cagabi** [comment]
I have done the change and now infiltration and ventilation are always taken into account.

**Comment by gervasemangwana** [comment]
Thanks Carlos

Even though I’ve trashed the cache ventilation is still showing as zero in master and scenario 1. 

I’ll leave it for this assessment I think. Maybe it won’t come out like this in the final report. 

cheers

Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by cagabi** [comment]
Ups, sorry again my mistake. Try again

**Comment by gervasemangwana** [comment]
Thanks C

That does seem to have reduced the infiltration quite a bit in scenario 1. But no problem. 

all good 


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk
