### ISSUE TITLE
Financial projection calculator

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#408]
After talking the other day about services and what happens after a household gets the report I thought that a financial projection calculator could be a good addition. 
The idea would be to use the cost of the scenarios as inputs plus other relevant info (loan interest, inflation, income from measures, etc) to show how long it would take to pay for the measures

**Comment by matt-carboncoop** [comment]
It would be useful if we could add an RHI calculator, similar to the (now defunct) FIT calculator in the current version.

**Comment by marianneURBED** [comment]
We can't do a financial projection calculator - we're not financial advisors and it's a beach of consumer law! 

Think the same might apply to RHI calculator - really you should be an MCS accredited installer to provide this. But we could add a link to the government RHI calculator to the report. I'll add that to the list of report edits I'm sorting in the next month. (This also means that if the govt update the rates for the RHI - or cancel it - we don't have to worry about it so much!).
