### ISSUE TITLE
Create assessment from EPC data?

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#409]
Could we offer MHEP assessments avoiding the site visit by using EPC data?
I'd like to look into how to build an assessment from an EPC

**Comment by marianneURBED** [comment]
Don’t even go there. EPC data is usually badly wrong!


________________________________

**Comment by cagabi** [comment]
Is that because EPC assessments are normally very old or because the procedure itself?

**Comment by marianneURBED** [comment]
All of the above - plus people are paid £30/time to do them, so we shouldn’t expect the data to be accurate in the first place.

I would use them for stock level analysis - with caveats - not for individual houses when suggesting improvements.


________________________________

**Comment by cagabi** [comment]
Ok, fair points.
I close this issue now

**Comment by marianneURBED** [comment]
No worries. And sorry if a bit harsh - Helen and I have just spent too much of our lives already wrangling with bad EPC data.

There is a role for something like this though I think - doing a rough assessment without a visit.

It’s what the  geovation tool is about - and we should probably look at that again sometime. (I trust OS maps and the person living in the house a lot more than I trust EPCs).

M


________________________________

**Comment by cagabi** [comment]
Jaja, don't need to apologise I can imagine your frustration
