### ISSUE TITLE
Archiving Facility - for good record keeping

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#410]
Before we make more major changes to the model we should make sure we can keep archive/record versions of old assessments - including the model data that was used to create them. 

This is so we can go back to assessments later when householders have queries and be able to adjust/check them. 

We need to be absolutely clear on things like the grid carbon intensities assumed at the time the assessment was done etc (could be very confusing to unpick if you have a PDF of an assessment that shows different results when this changes/ updates for example).

**Comment by cagabi** [comment]
Hi,

I have done this. 

Now the version of the model gets saved with the assessment and an assessment will always load that model. For previous assessment the version used is the current one openBEM v10.1.0.

I have added on the left hand side menu another item "openBEM version" where the user can choose another version of the model. Right now there is only more version available (v10.1.1) but it doesn't do very much (it logs a message in the developer console), it's just for testing purposes.

I'll close this issue now
