### ISSUE TITLE
ACH calculation tweak

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#411]
From Diane - They use a /20 approximation which should allow for exposure (it can be anywhere between /10 - /30 depending on the exposure (location rather than sheltered walls or average wind speeds)

**Comment by cagabi** [comment]
Right now in 18 we use /20 but first we convert 17 to ACH  
Would you like to allow to use /10 or /30 depending on the exposure? Sorry, I don't understand exactly the meaning

**Comment by marianneURBED** [comment]
Hello,

Don’t worry about this one for now – probably need to pick Diane’s brain a bit more to see how you’d best work this out. It’s a tweak/enhancement rather than a necessity.

M
