### ISSUE TITLE
Figures 6 and 7 in report not pulling bill data

### ISSUE THREAD

**Issue by helen-urbed** [emoncms/MyHomeEnergyPlanner#414]
Figures 6 and 7 in report don't seem to be pulling across bill data. Fairly urgent as we need to issue a report this week.
(See assessment CC21_HT_M6 8JG)

**Comment by cagabi** [comment]
Having a look now

**Comment by cagabi** [comment]
I have fixed this. 
Interesting enough the problem has been there at least since August 2018 :0
