### ISSUE TITLE
Libraries sharing problem

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#421]
Hello, 

The 'Carbon Coop' libraries are not currently sharing properly with assessors - when I go to 'manage users' it just shows a list of 'nulls' (see screenshot) and the library isn't appearing in an assessment Gervase is currently working on. 

This is pretty urgent - hopefully just something pointing at the wrong thing somewhere? 

<img width="987" alt="Screen Shot 2019-07-03 at 17 27 08" src="https://user-images.githubusercontent.com/16305707/60608829-42b1c280-9db8-11e9-88ef-7a98ebfbdce9.png">

**Comment by cagabi** [comment]
Hi, 
The problem here is not related to Gervase's one. Those libraries had not been shared with him that's why he couldn't see them ;)
I'll fix the names not showing tomorrow

**Comment by cagabi** [comment]
Fixed
