### ISSUE TITLE
If you click "Basic Dwelling Data", then "Add floor", nothing happens

### ISSUE THREAD

**Issue by paulfurley** [emoncms/MyHomeEnergyPlanner#426]
Steps to reproduce:

* create a new assessment and open it
* click `master`, then `Basic Dwelling Data`
![image](https://user-images.githubusercontent.com/254290/63084846-0be8d380-bf44-11e9-957a-08496fea6d65.png)
* Click `Add new floor`
![image](https://user-images.githubusercontent.com/254290/63084875-1dca7680-bf44-11e9-93a6-558c2b63bdfb.png)

We discovered the side menu link doesn't load `context.js` and so doesn't attach the event to the button. This is different behaviour to the other side menu links.

The workaround is to populating the floor data as soon as you open the assessment, as this information is on the 'front' page. But there is no navigation to let you return to this page.

**Comment by marianneURBED** [comment]
Hello. Yes, this always seemed a bit buggy. Generally it works once you refresh the page though. I've definitely been able to go back and edit floor areas in the past - either in the same scenario or in a scenario created from the master (for example to add an extension the householders were planing to build).
