### ISSUE TITLE
Clothes washing section - Household questionnaire - 4b - laundry, other appliances and small electricals

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#46]
The clothes washing section can go as this is covered under the main tool. However, please can we keep the clothes drying section - probably overkill to note the fraction? Maybe just tick boxes to note which get used instead?

**Comment by cagabi** [comment]
Clothes washing section removed.

I understand the reason to put the tick boxes but if i do the assessments that have something in the text boxes will lose the information. Do we bother??

  carlos

**Comment by helen-urbed** [comment]
I think it's fine if we lose some data for existing assessments - this is only needed for the report and will make it cleaner - I can easily go back in and amend (we have back ups of all the carbon coop assessments in spreadsheet format)

**Comment by cagabi** [comment]
Ok, so i have replaced the text boxes with check boxes, info is gone...

  carlos
