### ISSUE TITLE
Energy system puzzles -  What is going on with the electricity demand

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#50]
Hi

Looking at Calla’s assessment (63 Nicholas road). I can’t quite figure out what is going on with the electricity demand. I’ve ticked and filled the “Appliances Carbon Co Op calc” in the extended input. 

However in Energy System I can’t see how the figure for Appliances relates to that from the above calc. It seems way too much. But the figures at the bottom of the Carbon Co OP calc seem to relate to Primary energy only. So I’m not sure where its getting the number from.

In Core Input I have ticked sap calc for lighting but not for appliances and cooking. 

~~Ok now I’ve just gone to check something to write here and the entire assessment has gone blank. Totally empty. Nada. Nichts. Rien. Zip. It is, you might say, an ex-assessment~~

~~Tried refresh, closing tab and re-loading but still nothing.~~

~~I expect it is in there somewhere. Seems like a similar thing that happened to the assessment with my house.~~

~~There is a definite stability issue.~~

Best

Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by cagabi** [comment]
As far as i have seen in the assessment, this seems to be working ok but i agree it is confusing.

- If *Use SAP calculation* is ticked for any of them in *Lighting, Appliances & Cooking* the numbers in here are the ones that are taken into account. These check boxes are let say the ones that have preference
- If *Appliances CarbonCoop calculation* is ticked the numbers here will be the ones used unles any of the checkboxes in *Lighting, Appliances & Cooking* says to use SAP calcs
- If nothing is ticked then no appliances; lighting or cooking will be added to *Energy systems*

Tryinng to think in a way to make it more clear, the only think i can think would be to add in the *Energy Systems* next to the heading for Appliances... something saying which calculations are we using

  Carlos

**Comment by gervasemangwana** [comment]
Hi Carlos (Marianne see points 2& 3)

I understand the system and it is making more sense now the tick box system is fine.

However two issues one is bigger than the other:

1) The total figure for appliances is going into appliances section on energy system from the Ccoop appliances list. But also in the energy system is the cooking amount which is included in the ccoop calc. So it looks like cooking is counted twice and all as electricity 2nd time. Hope that makes sense. 

2) In the ccoop the total is called primary energy. But it isn’t primary energy I don’t think. It’s is the energy demand of the appliance. Primary energy I understand to be the energy used to make the electricity in the first place. 

3) Sorry actually another to mention. When selecting the energy supplier for cooking the only gas option is for the gas boiler with 90% efficiency. But actually the boiler does not supply that heat. It is direct from gas and my understanding is that the efficiency is much lower than that for cooking. One for Marianne.

Regards


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by gervasemangwana** [comment]
APOLOGIES!!!

I didn’t scroll down enough to find gas hob and electric oven.so please ignore comment 3 in my last comment.


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by gervasemangwana** [comment]
Comment 1 also not an issue

**Comment by cagabi** [comment]
*Primary energy * needs to be replaced for demand. In calculations we need to remove the coeficients and just add demand.

Also remove comlumns for Primary energy / m2, C02

**Comment by cagabi** [comment]
Done, changes will be uploaded by the end of the afternoon.

  carlos
