### ISSUE TITLE
Calla’s assessment (63 Nicholas road) has gone blank. Totally empty. Nada. Nichts. Rien. Zip. It is, you might say, an ex-assessment.

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#51]
Hi
~~Looking at Calla’s assessment (63 Nicholas road). I can’t quite figure out what is going on with the electricity demand. I’ve ticked and filled the “Appliances Carbon Co Op calc” in the extended input.~~

~~However in Energy System I can’t see how the figure for Appliances relates to that from the above calc. It seems way too much. But the figures at the bottom of the Carbon Co OP calc seem to relate to Primary energy only. So I’m not sure where its getting the number from.~~

~~In Core Input I have ticked sap calc for lighting but not for appliances and cooking.~~

Ok now I’ve just gone to check something to write here and the entire assessment has gone blank. Totally empty. Nada. Nichts. Rien. Zip. It is, you might say, an ex-assessment.

Tried refresh, closing tab and re-loading but still nothing. 

I expect it is in there somewhere. Seems like a similar thing that happened to the assessment with my house. 

There is a definite stability issue.

Best

Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by cagabi** [comment]
Hi There,

The assessment is back. Fully filled. Todo. Ja. All. It is, you might say, a resurrected assessment :p

It is a bit strange though as some energy systems had lost their summer and winter effieciencies.

Gervase, can you remember what did you exactly do before it died?

  Carlos

**Comment by gervasemangwana** [comment]
Hi Carlos

Great. Thanks. 

I was just moving between the 3 pages. Energy system, appliances carbon coop calc and lighting, appliances etc. 
Sometimes when I went to Ccoop calc it was empty. 
Sometimes the tick box next robot in extra input became untucked (this happened to Marianne with generation yesterday too. )

I may also have checked and unchecked use sap appliances or cooking calc. I don't remember exactly. 

All very odd. 

Gervase

**Comment by lowwintersun** [comment]
Let's keep and eye on this - resolved for the time being?

**Comment by cagabi** [comment]
I have been playing with a copy of the assessment and everything seems to stay as it is and not breaking.

I'll close this issue now. but pleasse reopen it if anything goes wrong again.

  Carlos
