### ISSUE TITLE
back compatibility 1

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#52]
I opened 63 Nicholas Road last week with Marianne and we found that in the Windows section of Fabric in the “subtract from” drop down every window had shifted up one in the drop down list. Also this list includes all elements including roofs and floors as well as walls. The selection glitch rotated through rotated through only the walls and floors. So "Front Brick” became “OUTRIGGER” and “Side Brick” became “Front Brick” etc.

**Comment by cagabi** [comment]
We have been able to replicate the issue: when deleting/adding a wall, it changes to which wall the windows are in.

**Comment by cagabi** [comment]
Fixed now.

Be aware that the windows *substract from* field has been messed up. So if you have any valuable assessment, you will have to reinput this info again.

  Carlos
