### ISSUE TITLE
Energy System and Carbon Coop appliance calc totals

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#54]

**Comment by cagabi** [comment]
Is this issue the same than 
https://github.com/emoncms/MyHomeEnergyPlanner/issues/50

**Comment by gervasemangwana** [comment]
Hmmmm

When I click it I can’t see what my original comment was on #54 only your comment.

Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk
