### ISSUE TITLE
Windows library

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#56]
Doors and Roof lights seem to be playing up. Specifically the parameters g,gl and ff disappear when using them in a different assessment (actually maybe in the same assessment in some circs. Then when you edit them other parameters drop out like Tag

**Comment by cagabi** [comment]
g, gl, anf ff can be edited when clicking on the edit icon. It shouldn't be possible to edit them there

**Comment by cagabi** [comment]
When editing a window element the original tag is changed to undefined

**Comment by cagabi** [comment]
Hi, i have fixed the three things.

With regards to the first one, i have only been able to replicate the problem when creating a new window element in  a library. I have tried every other possiblity: apply a measure to a window (replacing it, manual edit), edit it clicking in the icon; and found no problem. So, as said , i fixed the one i found.

Please keep an eye on those windows.

  Carlos
