### ISSUE TITLE
Energy System Gas Boiler glitch

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#59]
When choosing gas boiler for water heating, cooking and space heating the fraction and demand has become the same in all and is the space heating demand/fraction. This of course makes overall gas demand very high.

Definitely needs sorting this

<img width="1110" alt="screen shot 2016-01-27 at 15 54 31" src="https://cloud.githubusercontent.com/assets/16294193/12619053/5126771a-c50e-11e5-9349-36d4a2743220.png">

**Comment by cagabi** [comment]
Fixed now.

  Carlos
