### ISSUE TITLE
fuel costs

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#61]
Figures for fuel costs in current energy are different inputs than those in Energy system
Better if they are mapped together

**Comment by gervasemangwana** [comment]
Also standing charge in current energy is annual figure while that in energy system is daily
better both are daily

**Comment by gervasemangwana** [comment]
In the master scenario is it better that energy costs in "energy system" are populated from the "current energy" figures and can not be changed? While in new scenario the figures in "ES" are still populated from "CE" but can be edited.

**Comment by cagabi** [comment]
Standing Charge to be annual not daily

**Comment by marianneURBED** [comment]
This has now been dealt with by the introduction of the fuels manager - all now consistent and standing charge etc made annual. 

So closing this issue now.

**Comment by cagabi** [comment]
Well spoted
