### ISSUE TITLE
Applying Measures in Master scenario

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#62]
Does it make sense to remove the *Apply measure* buttons from the master scenario.

This makes sense if we see the master scenario as the real picture of the house, and then we apply measures to improve it in new scenarios

  Gervaise and Carlos

**Comment by cagabi** [comment]
For my notes,

Have tried to hide buttons adding
***
    if (scenario == 'master')
        $('button.apply-measure').hide();
***

to *UpdateUI* in *ui-helper-r3.js* but for some reason the event listeners are removed.

Also tried in *elements* and *systems* view *updateUI* functions and same behaviour.

  Carlos

**Comment by cagabi** [comment]
When implementing the Lock Master scenario #67 i found the solution for this one. SO did it.

Carlos

**Comment by gervasemangwana** [comment]
It seems that the solution to this issue may also have removed the ability to delete and edit elements in the master scenario. Maybe best I open a new issue.
