### ISSUE TITLE
Sharing assessment confusion

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#66]
When you share an assessment and click _Share_ nothing tell you that it has happened. It would be nice to have a message _Assessment shared with XX_ or just closing the window.

  Gervaise

**Comment by marianneURBED** [comment]
No longer necessary. Once shared, name of person/ organisation you've shared with jumps to list under 'shared with' - so you can see something has happened. 

Closing this now.
