### ISSUE TITLE
Surplus PV to C02 reduction

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#68]
Hi 

Meant to mention this last week but couldn't think of way to test my suspicion.

If I enter PV generation as 3000 and use factor of 0.5 I get same C02 emmissions as putting generation at 1500 and use factor 1.
This suggests to me that the exported generation is not included in the C02 calc. 
I did this in assessment 5Pev

**Comment by cagabi** [comment]
You are right: the exported generation is not included in the CO2 calc. But doesn't it make sense? I am having a hard mental twist with this one, jajaja.

The emissions that you are saving are the ones of the renewable electricity you are using onsite. What you are exporting are emissions somebody else will save.

When creating a new system in the library, you can use *greenelectric* as fuel type and this has a very low *CO2factor* (what we use to calculate emissions from the energy used). So if somebody else is using what you are exporting, it will be them the ones who get lower CO2 emissions.

Would it make sense to add another section in *Energy systems* saying something like "You are also exporting XXX from your renewable generation, this is saving this YYYY emissions"

  Carlos

**Comment by marianneURBED** [comment]
Hello, 

In theory it could be counted either way - i.e. against the carbon of the person generating it OR the person using it. And there is in all these things a risk of double-counting.  

However, the best and easiest way to avoid this is to simply do what SAP does and count it all against the house where it is generated. See page 35 of the SAP document: "CO2 emissions attributable to a dwelling are those for space and water heating, ventilation and lighting, less
the emissions saved by energy generation technologies." Also page 86 for a bit more detail. 

We shouldn't allow other houses to claim it for using a 'green' electricity tariff (which is a highly debatable notion, and is likely 'double counting' on its own, as the grid carbon intensity number already includes the contribution of all renewables in the country - and the next person to come along can easily change this, it's not 'fixed' infrastructure). In any case, it is the PVs on the house being considered that have allowed this energy to be saved. 

That way, there's still a strong incentive for renewable energy, whilst still acknowledging the contribution to the grid. 

Hope that's clear. 

Marianne

**Comment by cagabi** [comment]
This is clear, i'll do the CO2 calculationns taking into account all the renewable energy generated.

But should this mean we need to remove the *greenelectric* as a fuel option in systems??

   carlos

**Comment by marianneURBED** [comment]
Yes, I think so. Though we might end-up re-doing something similar once the effect of smart grids and the like is a bit clearer, I don't think it stands at the moment. 

Marianne

**Comment by cagabi** [comment]
Ok, great!!! 

Everything clear.

   Carlos

**Comment by cagabi** [comment]
Wow, this has been a major mission!!!

**Onsite fraction of Generation** was in the *Energy requirements* object so it was taken into account for the calculation of energy use, primary energy, fuel cost and CO2. **And that was VERY wrong**.

After spending some time with my new best friend SAP2012 i got to the conclusions that **Total Generation**:
- is not used for the calculation of *total energy used*, p32 section 12.1
- is used for the calculation of *Total delivered energy*, p187
- is used for CO2, p35
- is used for primary energy, p36

And something that was confusing me: the only purpose of the **Onsite Use Fraction** is for cost calculation: what is used onsite is *electricity costs saving* and what is exported is in our case *FIT income* (p86, Appendix M1.4)

So everything implemented and up there in a minute.

  Carlos
