### ISSUE TITLE
Edit and delete buttons gone from elements in Master

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#88]
Maybe when apply measure was removed?

**Comment by cagabi** [comment]
I can't replicate the problem.

Beware that if the scenario is locked those buttons are not displayed.

I'm working in the afternoon and can have a look.

   CCarlos

**Comment by gervasemangwana** [comment]
Ah. Ok that makes sense. I had the scenario locked.

You can close #88 ad #62

Cheers


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by cagabi** [comment]
Oh yes, the lock feature did its job ;)
