### ISSUE TITLE
Need to look at what happens when you tick Carbon Co op appliances box when SAP calcs are in use

### ISSUE THREAD

**Issue by gervasemangwana** [emoncms/MyHomeEnergyPlanner#96]
It unticks SAP appliances in lighting and appliances but not SAP cooking However it does not seem to include the SAP cooking value in Energy system totals..

**Comment by gervasemangwana** [comment]
When nothing is ticked needs to default to SAP (so SAP appliances does get ticked when others are unticked)

**Comment by gervasemangwana** [comment]
Only one tick box for SAP appliances and cooking

**Comment by gervasemangwana** [comment]
When detailed appliances is ticked SAP lighting, appliances and cooking should be unticked.

**Comment by cagabi** [comment]
Summary of the above comments.

There are three possibilities:
- Detailed Appliance list: everything (light, cooking and appliances) is inputted here and no other inputs are taken into account for the calculations. Should be called *Detailed list*
- AppCarbonCoop for appliances and cooking calculations but SAP for lighting
- SAP calculations for everything

Comments:
- I need to modify the *Detailed list* and add a column to choose a category for the item (lighting, appliance or cooking). Right now everything inputted there goes as *Appliances* in the Energy Requirements (in Energy systems)
- I think the current way of choosing how to do the calculations is too confusing. In my opinion it would be clearer if we remove the options from the *Extended input* and add a drop down list on top of the *Lighting, Appliances & Cooking* page for the assessor to choose which calculation (from the three options above) to use. The contents of the page would change according to the choice. **What do you think about this??**

Cheers,

   Carlos

**Comment by gervasemangwana** [comment]
Hi

I think it’s a good idea what you say about drop down. That way it could all be on the same page and would leave the relevant SAP Lighting section visible when choosing Carbon Co Op appliances. 


Gervase Mangwana

Waxwing Energy
07956378981
info@waxwingenergy.co.uk

**Comment by marianneURBED** [comment]
Ditto.

Think that's definitely the best way forward.

Marianne.

On Monday, March 21, 2016, gervasemangwana <notifications@github.com> wrote:

> Hi
>
> I think it’s a good idea what you say about drop down. That way it could
> all be on the same page and would leave the relevant SAP Lighting section
> visible when choosing Carbon Co Op appliances.
>
>
> Gervase Mangwana
>
> Waxwing Energy
> 07956378981
> info@waxwingenergy.co.uk
> <javascript:_e(%7B%7D,'cvml','info@waxwingenergy.co.uk');>
>
>
>
> > On 21 Mar 2016, at 15:32, carlos Alonso Gabizón <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > Summary of the above comments.
> >
> > There are three possibilities:
> >
> > Detailed Appliance list: everything (light, cooking and appliances) is
> inputted here and no other inputs are taken into account for the
> calculations. Should be called Detailed list
> > AppCarbonCoop for appliances and cooking calculations but SAP for
> lighting
> > SAP calculations for everything
> > Comments:
> >
> > I need to modify the Detailed list and add a column to choose a category
> for the item (lighting, appliance or cooking). Right now everything
> inputted there goes as Appliances in the Energy Requirements (in Energy
> systems)
> > I think the current way of choosing how to do the calculations is too
> confusing. In my opinion it would be clearer if we remove the options from
> the Extended input and add a drop down list on top of the Lighting,
> Appliances & Cooking page for the assessor to choose which calculation
> (from the three options above) to use. The contents of the page would
> change according to the choice. What do you think about this??
> > Cheers,
> >
> > Carlos
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub <
> https://github.com/emoncms/MyHomeEnergyPlanner/issues/96#issuecomment-199342103
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/emoncms/MyHomeEnergyPlanner/issues/96#issuecomment-199348689>
>


-- 
*Marianne Heaslip*
Architect/Sustainability Consultant

*URBED (Urbanism Environment Design) Ltd *a. 5th Floor, 10 Little Lever
Street, Manchester, M1 1HR
t. +44 (0)161 200 5500
e. marianne@urbed.coop
w. www.urbed.coop

Fire destroys Toxteth Food Central - we need your help!
<http://us6.campaign-archive1.com/?u=47ce46e3ee9278b42c90d7d62&id=a927286bfc&e=e1c312350a>

URBED is 40 and hosting 7 unique events over 2015 to celebrate.
<http://urbed.coop/events>
Urban Design Group Awards 2015 - Winner in the Best Practice Category for
Trent Basin
Wolfson Economics Prize 2014 - Winner: Uxcester Garden City Proposal
Community Land Trust Network Awards 2012 - Awarded for excellence in
community engagement 2Up 2Down / Homebaked
URBED (Urbanism Environment & Design ) Ltd is a limited company with
co-operative rules registered in England and Wales NO. 5741006. Please
access the attached hyperlink for an important electronic communications
disclaimer: http://www.urbed.coop/emaildisclaimer
<http://www.urbed.coop/emaildisclaimer.>

**Comment by cagabi** [comment]
Done.

  Carlos
