### ISSUE TITLE
Query over accuracy of appliances calculations methodologies.

### ISSUE THREAD

**Issue by marianneURBED** [emoncms/MyHomeEnergyPlanner#97]
From Gervase: 

I’ve been using the Carbon Co Op appliances calc for 63 Nicholas Road. We got a very comprehensive list from them at survey.

It gives appliance use as around 1580 kWh. (total including lighting and cooking is 2313kWh)

SAP calc at SAP occupancy (which is actually very close in this case) gives 3533 kWh (total 4267 kWh)

The average electricity use over 2 years there was 3800 kWh. 

Of course this is just one case but seems like SAP is much closer. 

Just wondering about a general approach here.

MH response: 

Hmm, 

Often also goes the other way too - suspect it's a function of assumed occupancy somehow and its relationship to house size (my feeling is SAP tends to overestimate use in smaller houses, but I could have that wrong). 

I know Nick Grant and others were looking at the appliances calc in PHPP and finding it wasn't totally accurate - though better in some situations than others. Prob more one for a bit of research, rather than a programming solution from Carlos.

**Comment by cagabi** [comment]
Closing this issue as it is not that the calculations are done wrong and depends more in the actual use of appliances
