### ISSUE TITLE
Combi loss for combi boilers tested to EN 13203-2 or OPS 26

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#98]
We are doing calculations of _combi loss_ for combi boilers not tested (table 3a, p. 199, SAP2012)

We should implement the calculations also for tables 3b and 3c

   Carlos

**Comment by marianneURBED** [comment]
We're going to move to much more generic assumptions about boiler efficiency, in looking at the heating pages. This no longer relevant.
