### ISSUE TITLE
FGHRS and WWHRS inputs in water heating

### ISSUE THREAD

**Issue by cagabi** [emoncms/MyHomeEnergyPlanner#99]
Flue Gas Heat Recovery Systems (FGHRS) and Waste Water Heat Recovery Systems (WWHRS) are not taken into account when additional inputs to *water heating*

See (63) in worksheets and appendixed G and H, SAP2012

  Carlos

**Comment by marianneURBED** [comment]
We won't ever specify WWHRS, so there is no need to implement that. (They're very difficult to retrofit, make much less of s difference than just using water more efficiently, and have a horrible tendency to clog with conditioner). 

We probably also won't ever specify a FGHRS. They're difficult to retrofit, and the savings suggested for them are highly questionable. 

So there's some work you don't have to do!
